### ISSUE TITLE
Multiple relations to the same contenttype

### ISSUE THREAD

**Issue by rarila** [bolt/bolt#1143]
It seems multiple relations to the same contenttype aren't possible now as the relations aren't named?!

I have a pool of employees and in the officess datatype I like to select a single person who's in charge of that office and I like to select multiple other employees, that work in that office.

Also the displayed name in the selection popup seems to be defined by the order atttribute of the relation. So `order: lastname` gives me something like `Smith (Nr. 23)` which doesn't seem to be insufficient. At least something like `order: lastname, firstname` would be preferable so that you get `Smith John`.

Any ideas?

**Comment by sbonardt** [comment]
@bobdenotter it's relevant for a project for us now. Let's see if we can have this implemented.

**Comment by rossriley** [comment]
For reference, it will be available with the current refactor of relationships. There will be a `key` option to store the relations on so as to support multiple keys for the same relation.

**Comment by luanlmd** [comment]
Nice too see this is going to be implemented; In my case I have events and entities. Entities can be organizers, sponsors or supporters of events. I need to list them separately. This feature will be perfect.

**Comment by ScreamZ** [comment]
Any news about that feature ? WIll still be available with 2.3 ? Thanks :)

**Comment by SahAssar** [comment]
@ScreamZ It's not among the implemented features for 3.0 AFAIK (the new 2.3, see here: https://discuss.bolt.cm/d/112-bolt-version-roadmap-changes/8 ) and since we've been in a feature freeze since quite a while back it will probably not land in 3.0. I'm going to open a RFC about this in the forums, and lets see if we can get it done for a 3.X. Forum thread here: https://discuss.bolt.cm/d/127-multiple-relations-to-the-same-contenttype-continuation-of-1143
