### ISSUE TITLE
[RFC] What should be in the Roadmap for 3.0 ?

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#1913]
Now that we're _almost_ ready to put out a beta for 2.0, it's slowly becoming appropriate to start thinking about what we should prioritize for 3.0. 

Under consideration: 
---------------------------

  - Multilingual content and/or storing revisions
  - Move to using an ORM (and refactor `storage.php` at the same time)
  - Events for all the things, and make more use of the event dispatcher (so that extensions can hook into them).
  - A full-fledged JSON REST API for backend / frontend communication. (probably as an extension)
  - Allow translations for extensions. 
  - Perhaps use something like Transifex for managing translations? 
  - Hierarchical content
  - A Media Manager of sorts, to streamline uploading, inserting, deleting and organizing the media in the website. (perhaps as an extension)
  - Drop support for PHP 5.3 (note: [piwik](http://piwik.org/blog/2014/10/announcing-piwik-will-end-php-5-3-support-six-months-may-2015/) )
  - Use Monolog instead of our own home-baked logging. 

Note: "under consideration" does not mean we _will_ implement these things. 

What we NOT will be doing for 3.0
---------------------------------------------

  - Add support for NoSQL. No CouchDB, No Mongo. 
  - Use Doctrine ORM
  - Use anything tied to CMF / PHPCR
  - Use anything that [requires annotations](http://theunraveler.com/blog/2012/php-annotations-are-a-horrible-idea/) or deals with code generation. 
  - Porting Bolt to Go. 

Finalizing
------------

  - M̳̲̣̜͚͍̤̘̝̿̈̇ͦ̀o͚͖̾ͪ̀ͫ̅̐͋̕͜r̻͓͈̆͂ḛ̟̪͔̩̆͑ͬͬ͊̈́́͠͡ ̛͔̰ͥ͗̍͛̀ͮ͑͐C̽͑҉̜̳t̷̺͚͕̬̺̟͒̊̋́h̴͑ͤ̾ͯ̋ͣͨ̂҉̣̘̩ͅu̔̐͗̋̽҉̖͚͍͓̯̬̥l̟͚̺̯̫͉̠͔̎ͩ͌́u̴̖̫̼̔ḥ̖̽ͭ̊̈́̿̔̇ủ̡̩̊̓ͯ̌͌ͧͩ͠ ̡̺͇̝̱̱͖̥͙̆̏ͤ̃ͪ-̷̢̭͕̥̻̮͚͍ͧ͊̓͞ ̆͏͈͕̘̖͙͞t̶̡̫̩͋ͬ̚͜ĥ̹͕̺̦͍͔͎͚̔̏̕èͩ̓ͪ̏҉͏̻͚̗͇̹̻̠̰ ̻̝̑̽͛̃̂͢ͅǏ̲̤̋ͪ̓̄c͐̈́̈̅̇͐̑ͪ͏҉̙͉͙̰͍̬ͅh̵̴̭̭̪̼͙̀ͥ͂ͫ̿̋̏̈́o̸͉͛͊̅͗ͬ͗̂̕ŗ̬̝ͪ̈́ͫ,̵̞͆ͩ̿ͣ ̸̧͙̖̭͍͇̬ͧ̒̇͑į͖̙͍̖̖̒̆͐ͤ͟͟t̊ͣ͋͗̍̚͏̟͙͈̻ͅ ͎̪̻̫̮̖͐̾p̼̭̖͍̦̺͔̜ͦͭ͌̏̋̔̈͘e̮̫̻̹̮̳ͥͥ͟r̥͓̥̭͊̅̕m̸͎̬͕̣̙͔̄͛ḛ͈̝̩̰̪͚̥ͪͬ̔ͫ̇̋ͨ̈́͟a͇̣͎̞͚͙̐ͨͫ͂͞t̆̅̂͏̼̯e̵̳͍͍̯ͭ̂ͥͤ̈́ś̡̧̛͕̫̊͋͊.̡̝̌ͬ̈́̒̑͝

**Comment by bobdenotter** [comment]
As an ongoing update to this: 

> Drop support for PHP 5.3 (note: piwik )

- Silex' 1.2.3 will be the last version supporting PHP 5.3.3. It's 5.3.9 onwards. ([source](https://twitter.com/fabpot/status/557582556649242624))
- Symfony 2.7 (due may) will probably do the same. ([source](https://twitter.com/fabpot/status/553204952802525184))
- Doctrine stopped support for PHP 5.3. ([source](https://github.com/doctrine/doctrine2/pull/1255))
- Symfony 3 (due november) will probably be PHP 5.5 minimum

> Move to using an ORM (and refactor storage.php at the same time)

This looks promising: http://phpdatamapper.com/ (no annotations, no code generation, works with existing database tables)

**Comment by abelafonte** [comment]
I'd vote for hierarchical pages

**Comment by tobias2k** [comment]
> Move to using an ORM (and refactor storage.php at the same time)

When you say "ORM", I hope you mean "an off-the-shelf database abstraction library", not "something like Hibernate that pretends the database doesn't exist".

Also, I'd vote for a *rewrite* of `storage.php` rather than a refactoring; and while we're at it, rewrite  `getContent` and its vassals with a proper plan and design behind them - a real parser, a clear separation of parsing, passing queries around, executing queries, mapping query results to records, and passing those around. Separating these stages is crucial to keeping things readable and maintainable IMO. Also, making stuff more rigid and writing better documentation so that when you wonder whether a certain value in a certain parameter to a certain function works as intended, you can just look it up.

**Comment by tobias2k** [comment]
> The only suggestion that I have which will be a major one is that we have a look at the data structure and think about moving to an Entity -> Attribute -> Value structure, one of the problems I've had with putting a Doctrine front-end in front of Bolt (which will be an issue if we do want to move to ORM) is that the joins can't be described in a normal ManyToMany way without writing custom join queries.

I've been playing around with EAV architectures myself (though not recently in PHP), and my conclusion so far is that if you want to do this, none of the existing ORMs is suitable, simply because the assumption that tables and rows should map to classes and instances doesn't hold true; an ORM that works based on this mapping wouldn't get us any further than put another layer of indirection between the "real" objects and the database. However, a database abstraction layer that *doesn't* try map to domain objects, but instead just faithfully models the (relational) database itself is a good thing to have, especially when you want to keep supporting several DBMS solutions.

Going from "objects that represent things in the database" to "objects that represent our actual data", however, is going to be a custom thing one way or another.

And one more thought; the more I play with this idea, the more I see how this would impact things all across the project, so it's not just a matter of "refactoring storage.php", but if you want to do this right, you'll be rewriting about half of Bolt. Not that I'm necessarily against that, but it's something to be aware of.

**Comment by tobias2k** [comment]
> A full-fledged JSON REST API for backend / frontend communication. (probably as an extension)

Yes, please. Also, HATEOAS and all that. Probably worth rethinking the frontend routing, too - most likely, each route is going to be a resource, so the JSON response and the HTML response can share most of their respective code, the only difference would be that the JSON response sends the data through a JSON formatter while the HTML response runs it through a Twig template.

**Comment by bobdenotter** [comment]
Here's the _current_ distribution of _**active**_ Bolt websites, as of january 2015. I've filtered out the 'one off' installs, as well as everything that runs on hostnames with 'dev' or 'local'. So, this is a fair view on the current version, as found in the wild. 

```
unknown      |    120 
5.3          |	 1265 
5.4          |   1723 
5.5          |   2419
5.6          |	  500
```

**Comment by danielbachhuber** [comment]
> A full-fledged JSON REST API for backend / frontend communication

As a lead developer on [WP-API](https://github.com/WP-API/WP-API), I'd be interested to hear how you're thinking to implement. And, your thoughts on exposing schemas for custom content types for https://github.com/WP-API/WP-API/pull/759

**Comment by bobdenotter** [comment]
Hi @danielbachhuber, 

We haven't gotten to that point just yet, but I just read through that thread you linked. I think it looks good. We'll definitely be looking at what you are doing with WP-API, and perhaps we'll even make sure to adopt the same standards and protocols, to get more interoperability between our projects.

**Comment by danielbachhuber** [comment]
> I think it looks good.

If you have opinions about what specifically looks good, you should weigh in :) We're in active discussion right now, and more opinions / perspectives are better.

> We'll definitely be looking at what you are doing with WP-API, and perhaps we'll even make sure to adopt the same standards and protocols, to get more interoperability between our projects.

This would be lovely :)

**Comment by bobdenotter** [comment]
See also here, for shorter term Roadmap: https://github.com/bolt/bolt/wiki/Bolt-2.x-Roadmap

**Comment by psren** [comment]
:+1:  Hierarchical content
:+1:  Multilanguage
:+1: Events for all the things

**Comment by cooperaj** [comment]
Alongside hierarchical content its be great to have navigation providers such as menus and breadcrumbs that hook into that.

**Comment by rossriley** [comment]
While we're refactoring the storage and field layers of the app this might be a good time to discuss how everyone sees hierarchical content being implemented, in an ideal world what would a developer do and how would an editor interact with this type of content.

**Comment by CodeBrauer** [comment]
A bit late, but #3267 seems to be a very nice feature for building *todays typical* websites

**Comment by GawainLynch** [comment]
Continuation of this topic should now occur on the new [forums](https://discuss.bolt.cm/t/rfc)
