### ISSUE TITLE
Feature Request: Contenttype Array

### ISSUE THREAD

**Issue by Largo** [bolt/bolt#2261]
Hi everyone.

I love bolt and the idea of contenttypes, but recently I found something which is lacking, that would make it possible to create things like online shops with bolt.

A control and contenttype that allows the user to add array data.

Here's a control, that is similar to what I'd like. I only need 2 columns tough.  http://www.jqwidgets.com/jquery-widgets-demo/demos/jqxgrid/#demos/jqxgrid/createremoveupdatedata.htm

Usecase:
1. User wants to add a variation of an article. The information blue hat and 5€ needs to be stored.
2. User adds the row "blue hat", "5€" 
3. This gets serialized in the database in a field called variation.  ([{"blue hat" : "5€" },{"green hat" : "6€" }]
4. Template designer can get this as an array with an twig helper function or it's outputted directly as an array: record.variation

Currently, It's possible to create an new contenttype variaton and then make a relation. It's a more normalized way, but it adds more clutter. The contenttype variaton gets an url and appears in the search by default. Not really userfriendly.

What do you think about my idea?

**Comment by jeff-h** [comment]
I'm nervous that the discussion in this issue is focussing on a very simple use-case. In my current use-case, I need a "Group registration" contenttype with a repeating set of fields to be filled in for each person in the group (e.g. Name, Address, email address).

In the above discussion, I'm unsure whether "blue hat" and "5€" are "Bolt fields" which (via extensions) could be quite complex (e.g. a Google Map field), or whether they're trivial fields such as text fields?

**Comment by tobias2k** [comment]
The one reason why JSON in MySQL can be problematic is performance.
Unlike PostgreSQL, MySQL does not understand JSON data structures, and
you cannot index "into" your JSON fields - MySQL pretty much just sees
them as opaque blobs. This means that if you want to search by anything
inside that JSON field, MySQL will have to perform a full table scan on
your contenttype - for something like a web shop, this can become a
serious problem, especially once the thing starts to live in the wild
for a while and content starts to accumulate. It's basically a matter of
O(n) vs. O(log n) - no problem when you have 10 records, but completely
unacceptable when you have 10 million.

I can see three solutions to this issue.

One, use something like full-text indexes. This isn't going to give us
correct results directly, so we'd still need some extra code on the web
server side, but at least it would allow us to filter out the obvious
non-matches, and partially get around the O(n) problem. OTOH, full-text
indexes aren't supported in InnoDB, so we'd lose any hint of transaction
support we might otherwise get, as well as Inno's more efficient
locking, and the code on the PHP side isn't going to be great either.

Two, maintain indexable rows alongside the JSON blobs. This would
require some extra code on the PHP side, too, but a bit less hairy, and
it would mostly affect inserts, not selects. It would also require users
to explicitly specify which sub-values in the JSON columns to index.
E.g., if the contenttype says "foo.bar.baz" has to be indexed, Bolt
would add an extra column foo_bar_baz, and whenever anything gets
inserted or updated, .bar.baz would be extracted from the foo JSON
content and added to that column. Selects would require some extra
logic, but the performance overhead would be mostly on the insert side
of things.

Three, store JSON trees in a relational data structure, i.e., a
full-blown EAF (Entity-Attribute Framework). This is going to be a lot
of work, particularly on the design side of things, particularly getting
the abstractions right, finding a good way of mapping between relational
data and tree structures that performs and scales well, and making it
robust enough to keep things consistent and manageable. Another downside
is that the relational data structures are going to be hard to
manipulate directly.

On Wed, Dec 03, 2014 at 03:31:39AM -0800, Andreas Wildi wrote:
> Thanks @rossriley for pointing me to that discussion.
> 
> I worked in a startup, where we put some less important user configuration values together as json data directly into a mysql db (datatype varchar). It works and we didn't have any issues. I see that there are some downsides to using json for that and Bob called it hackish. 
> However I'm in favour for that, because the alternative is to flood the database with many tables.
> That will make everything more complex and lead to bigger problems.
> 
> Also I think this shouldn't get to complicated. There's no need for another drupal / typo3 etc.
> I think, that can be achived by using serialization and sticking to just key value arrays.
> 
> Ok, I'll try to come up with something. I'm not sure if it's feasible, because I haven't studied the internals properly. Don't count on it tough. :)
> However I just saw that and it makes me hopeful: 
> https://docs.bolt.cm/v20/extensions/customfields
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/bolt/bolt/issues/2261#issuecomment-65394318

-- 
Tobias Dammers - tobias@twokings.nl - 070-3457628 - www.twokings.nl
Maandag t/m donderdag van 9.00 tot 17.30
Voor dringende vragen, mail naar support@twokings.nl

**Comment by rossriley** [comment]
Going to close this issue since more up-to-date discussion can be found in #3267.
