### ISSUE TITLE
Multi-language site support

### ISSUE THREAD

**Issue by gido** [bolt/bolt#234]
Hi,

I just discover your project, nice job !

There is a missing feature that I need: site content in multilanguage.

Do you already have thinked about it ?
Maybe I can help...

**Comment by giorgionetg** [comment]
Hello world, I'm actually develop some websites and I have to make these sites multilanguage.. So, I read about documentation (contenttypes' duplication).. Anyway I think is not good idea when you have a lot of contenttypes and.. yes, I have a lot in some cases.
So, I think, but it's only idea or a little sketch, we need to have a Routing component that thinks in multilanguage, a TemplateChooser too, at the end it's really big implementation (considering Test and bug fixing)... So right now, is it still in progress or is it stop?

**Comment by SahAssar** [comment]
Just an FYI regarding this: Me and @madc have worked on AnimalDesign/bolt-translate (first madc, then me), and it's currently in a state where I think it solves most of the issues mentioned here. I am trying it out with clients on production sites.

**Comment by SahAssar** [comment]
Closing this issue since it is either solved by an extension or by the method described by the docs. If anybody has any bright ideas about how to solve it in core please reopen, but this seems like an extension thing to me.

**Comment by frostymarvelous** [comment]
I almost lost all hope till I saw @SahAssar post on AnimalDesign/bolt-translate.
After almost a year away, I'm back to find that Bolt has matured well and is becoming everything I knew it would be (so happy S3 support is now available).
This is one last hurdle that needed to be crossed.

**Comment by q2apro** [comment]
Hi everyone, after ModX for years, I have tested many CMS over the last weeks and found Bolt CMS and Processwire the candidates to use for future projects. However, the missing multilingual part of Bolt makes it unusable since nearly every website I develop externally is multilingual. 

To create multilingual sites I mostly go for the same slugs, e.g.

    - en 
       - team
       - services 
    - fr 
       - team
       - services 
    - de 
       - team
       - services 

This way it gets very easy to link the files. The parent container is the language and the children match each other. 

Of course, there could also be a module where the user has to put the according page ids of the other language pages (or choose by entering page title or slug etc.). 

Just my thoughts to help Bolt and its development.

PS: Great job you have done.

**Comment by madc** [comment]
Did you have a look at [bolt-translate](https://github.com/AnimalDesign/bolt-translate)? It's an extension to bolt that tackles this issue quite successfully, I'd say. Development is mostly done by @SahAssar and myself.
If you miss some features or encounter anything, feel free to post an issue.

**Comment by bobdenotter** [comment]
The mentioned Translate extension coupled with [Labels](https://extensions.bolt.cm/view/bolt/labels) will solve most of your problems. :-)
