### ISSUE TITLE
CsrfTokenManager deprecated

### ISSUE THREAD

**Issue by opb** [bolt/bolt#2373]
Hi there

I installed bolt via `composer create-project bolt/composer-install ca-blog --prefer-dist`. When accessing the site via Homestead (Laravel flavoured Ubuntu vagrant box) *OR* via plain old `php -S` on my Mac (Yosemite, php 5.5.12, homebrew), I get the same message:

```
Deprecated: Symfony\Component\Security\Csrf\CsrfTokenManager was deprecated in version 2.4 and will be removed in version 3.0. Please use 
Symfony\Component\Security\Csrf\TokenStorage\SessionTokenStorage instead. in /Volumes/UserHomes/oliver2/Development/repos/ca-blog/vendor/symfony/form/Symfony/Component/Form/Extension/Csrf/CsrfProvider/SessionCsrfProvider.php on line 14
```

I completely deleted my project folder and created the project again, with exactly the same effect. Screenshot below:

![screen shot 2014-12-30 at 18 10 52](https://cloud.githubusercontent.com/assets/778850/5581297/934ae828-904f-11e4-928c-939f1dc3a09e.png)

Happy to provide any additional info.

Thanks!

**Comment by bobdenotter** [comment]
Pinging @opb 

Any more info on this?

**Comment by opb** [comment]
sorry, not had time to look at it yet. will have a go today.

**Comment by GawainLynch** [comment]
This is coming from Symfony itself, and there have been two updates to Symfony 2.5 and three to Symfony 2.6 components since this was opened and I dare say they have done some housework on their own stuff in the process.

So I am going to close this. If you're still seeing problems, please feel free to reopen with additional information that we can use to track this down further.
