### ISSUE TITLE
Errors in search results front end

### ISSUE THREAD

**Issue by peterboorsma** [bolt/bolt#2409]
It seems the Bolt 2.0.2 front end search engine has some issues with two character words in search results.

here's an example:
http://kickingthehabit.nl/search?search=le+guess+who returns lots of errors
http://kickingthehabit.nl/search?search=guess+who returns (lots of) normal results.

Another example:
http://kickingthehabit.nl/search?search=de+kift returns lots of errors
http://kickingthehabit.nl/search?search=kift returns normal results

**Comment by bobdenotter** [comment]
Yeah, I'm guessing that's because we use some sort of "OR" search scoring. If you search for `de`, there's a lot of articles that contain it. Articles that contain it a bunch of times will score higher than an article that contains `De Kift` by itself.

**Comment by peterboorsma** [comment]
Ok, but that's not really a solution. It's not that people search just two characters, it's a search with multiple words and one of the word is a two character word.
I mean, you can't say to your site visitors: go search but no two character words please...

**Comment by GawainLynch** [comment]
I have to agree with @peterboorsma on that one...

**Comment by GawainLynch** [comment]
Just to track this.

The error is being generated from `Storage::executeGetContentQueries()` in this part:
```php
                    $countStatement = sprintf(
                        'SELECT COUNT(*) as count %s %s',
                        $query['from'],
                        $query['where']
                    );
```

The conditional is the size of MySQL's `max_allowed_packet` parameter. To work around it, you just need to increase the value.  Working on a record set of 10,000 records for a single Contenttype, I was able to use `max_allowed_packet = 1M` and **not** get the error.  That said, I started with `max_allowed_packet = 128K` to generate it in the first place.

**Comment by GawainLynch** [comment]
Bumping this to 2.2 as fixing the core problem requires (at a minimum) the upcoming refactor of Bolt\Storage.

**Comment by GawainLynch** [comment]
@rossriley does the new storage code cover this now?

**Comment by bobdenotter** [comment]
Ok, once more: 

 - This is not a bug, strictly speaking. It behaves exactly how it was developed
 - The results are different than you (or most people, for that matter would expect. 
 - It has nothing to do with the _lenght_ of any of the search terms, but rather how frequent these words show up. So, 'de' is _not_ the problem. 

What _is_ the problem is the following. If you currently search for "de kift", you'll get _all_ records that contain `de` and/or `kift`. De fact that you'll get a **lot** of cruft and potentially an out of memory error, is not because `de` is a two letter word, but that you'll get all records that contain `de`, which is probably a lot. Since you were searching for `de kift`, it's most likely that search results containing _both_ those words should be favoured.
