### ISSUE TITLE
Taxonomy and datepublished

### ISSUE THREAD

**Issue by Pinpickle** [bolt/bolt#2446]
Currently our only options for Taxonomy sorting are `DESC` and `ASC`. Fair enough, because all contenttypes have different columns so picking something to sort by would be difficult. Why can't we, though, have the option to sort by `datepublished`? Surely, this is all that would need to happen:

- Add `datepublished` column to taxonomy table
- Set this column for every time the `datepublished` field in the record changes (including first set)
- Sort by this when fetching content by taxonomy

It's a little bit WET, but it's either this or getting into sticky JOIN queries which aren't fun.

The only problem I can forsee is uploading old databases could take a little bit of time with sites that have a lot of records and lots of taxonomies per record (think 20 tags, or something ridiculous).

**Comment by bobdenotter** [comment]
I agree that the current solution is a bit weak, but your proposed fix would only solve it for a specific case.  Perhaps it might be possible to add a field "sorting", and fill that with whatever field is set in the contenttype?  
On the other hand, sorting taxonomies on 'datepublish' would be the most common sorting order by far.

> It's a little bit WET, but it's either this or getting into sticky JOIN queries which aren't fun.

Yes, that's what kept us from fixing it already. Also, simpy JOINing wouldn't work, because depending on the contenttype you don't know which table to join on.

**Comment by Pinpickle** [comment]
I thought as taxonomies were already being sorted by the order that they were added in (roughly), a sort on `datepublished` would just be a more robust implementation. I am all for a solution that lets you select which field to sort by, though.

**Comment by SahAssar** [comment]
Imma gonna let you finish... Oh, sorry, this is over a year old ;)

I'm going to close this, and I'm guessing that this is one of those features that when it is needed or makes sense for one of the bolt members it will be implemented. So, I'm closing, but I'm hoping that this get's done sooner or later :)
