### ISSUE TITLE
Image caching

### ISSUE THREAD

**Issue by nlemoine** [bolt/bolt#2451]
I'm facing a problem with thumbnails and image caching. 

I ran into this issue trying to optimize bolt website images folder with `jpegtran`. I set the config option `save_files` to `true` and ran the command on the whole `thumbs`directory (once the thumbnails were generated of course). I checked directly on the server, file size has decreased, the files had consequently been optimized. But when I visit a page containing an image and check the file size again, I noticed all images went back to the original size, non optimized. So I dug into the code, to check how thumbnail creation, cache was handled. 

Looks like even when you set `save_files` to `true`, files are saved again and again on each request no matter what. This issue is a bit related to issue #1506.

I think this a not very efficient thumbnail/caching strategy considering that one or more files are written on disk each time they are requested. Regarding my original issue, this system doesn't allow me to optimize them with a command line tool as they are always overwritten. 

Maybe cache file path would be a better value to be cached than the whole image content? Adding the original `filemtime` timestamp to the cache key would make it easier to regenerate thumbnail when original file is updated.

**Comment by rossriley** [comment]
Hi @nlemoine.

Are you sure your cached images are being served correctly by the web server?

If they are then a request to `/thumbs/150x150c/xxx.jpg` will literally only serve the image file located at that url, the request won't hit Bolt and no regeneration of that image will happen. 

The fallback will only kick in if that url would ordinarily throw a 404 and in that case the request is handled by Bolt which will indeed try and recreate the resource, because at this point it assumes a cached version does not exist.

**Comment by nlemoine** [comment]
Hi @rossriley,

Thanks for your reply. I actually figured out why images were still going through the PHP process. 
I still had the rule below in my htaccess file:
```
RewriteRule ^thumbs/(.*)$ ./app/classes/timthumb.php [L]
```
Taken from here: https://docs.bolt.cm/installation
Because no htaccess file is copied from the repository when doing a composer install. 

I'll propose a PR on the doc repository.
