### ISSUE TITLE
[RFC] We should only include locales for locales that we actually support.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#2585]
Ref. 61bdb96f1a6a2dc7e174633bbb34a4e44e833ad3

Bolt ships with a few external packages/modules that come with a _bunch_ of locales. CKEditor, Codemirror, Moment.js and Jquery UI's datepicker. If we included all of their locales, we'd have about ~400 extra files in our distribution, and I think it would only confuse users. For example, they could set the locale to Georgian, and the entire backend would be in english, except for a few random strings in the datepickers. 

So, I propose that we only include those external language files for languages that actually have a Bolt translation. 

Or, to turn it around: If somebody complains that CKeditor should be in latvian, he/she should provide a translation file for Bolt in Latvian, and from that moment on, we'll include the latvian files for the Datepicker, Moment.js, CKEditor and Codemirror.

**Comment by GawainLynch** [comment]
I was backward and forward on this in IRC, but the selling point for me in favour of this is your final paragraph.

**Comment by cdowdy** [comment]
Another thing that might help is moving toward a package manager.  

This would normalize the folder names so that a version isn't attached (ie magnific-1.0.0 would become magnifc-popup). You've already moved moment js and their locale libs to their own folder without a version number.   

This would also help with updating. For instance I've started a move to [Bower](http://bower.io/) in a branch [here](https://github.com/cdowdy/bolt/blob/convert-to-bower/app/view/bower.json) to update any of these js libs you'd run ```bower update ```  

An issue I see with a setup with bower is having devs use bower on their machine but seeing as how grunt is used already I don't think that's too much to ask buuuuuut that's completely my opinion and some may not want to add another layer into their process. You'd also have to commit the ```bower_component ``` directory or have a build script to include these on a download or composer install.  

Back on topic I like your solution to include once a translation has been made

**Comment by rarila** [comment]
Ok …

- If a user sets locale to Georgian I guess he would more wondering about having English everywhere than having some dates in Georgian. If he has a problem with this mix he would probably either start translating or switch back to English if he's not completly dumb.

- Having a translation and having a (almost) complete translation are two things. Does having translations files lying around means we support that language? Without checking it (and I haven't been there for quite some time now) I would guess that at least half the translations we "support" are totally out of date and perhaps a hand full reaches a 95% completeness. So following this logic would mean removing them, too?

- Even if someone provides a translation does mean nothing. Need some proof? – Our CkEditor has only DE, EN, FR, and NL locale although we "support" all this other locale. (See #2526). So I prefer having in what's possible as it makes it easier for us (e.g. we don't have to check if there's a locale to be added from libs if theres a new translation file or if there's a new locale in a libs update that wasn't there before and could be used)

- If we would try not to confuse users we would restrict what can be entered in config, e.g. check what is entered and show a warning. I guess we don't even check anything there, so that you could even enter "klingon_mars" there. So we give the user full power and don't pamper them anyway. The user has to live with the consequences.

- Ok, there are a few files more, but they are rather small and they need no maintainance as everything is handled automatically. This is nothing compared to the perhaps >1000 files in vendor that are never used by Bolt.

- We give our users a build in tool to add their own translations without any programming knowledge. There's also no requirement to give that translation back. I think it is more annoying for users to be able to add their translation and then to have find out that dates are wrong. I remember that it took quite a few hours to find out how to add German to CkEditor. And that although I think I have some knowledge. Now multiply that time for the other libs… I think it's better to supply what's possible and have a good out of the box experience. Otherwise we could also remove the build in translator and make an extra package just for translators out of it.

- Someone providing a translation file for Bolt brings us quite nothing as it get's outdated quite fast. There has to be someone that feels long term responsible for one translation otherwise we can't speak of we support that language. (Even one quite involved as I hasn't touched the German translation for a while yet and I'm sure there's a bunch of strings missing). So better have those external things in out of the box.

We could perhaps add a page in the translation part where we list available locale and an ability to remove unused ones

```
Language | Bolt | Datepicker | Moment | CkEditor  |
-------------------------------------------------------
en_GB    | 100% |      X     |   X    |     X     |   [DEL]
nl_NL    |  95% |      X     |   -    |     -     |   [DEL]
```

We also could add something like with extensions where you can add your translation… no, we wanted to be k.i.s.s.

**Comment by bobdenotter** [comment]
> If he has a problem with this mix he would probably either start translating or switch back to English if he's not completly dumb.

Yes, that's very close to what I was saying. 

> So following this logic would mean removing them, too?

Or pushing people to update them.

> Even if someone provides a translation does mean nothing. Need some proof? – Our CkEditor has only DE, EN, FR, and NL locale although we "support" all this other locale. 

Yes, that was my idea too: We should add the files for CK for locales that we support. ^_^

> Someone providing a translation file for Bolt brings us quite nothing as it get's outdated quite fast. There has to be someone that feels long term responsible for one translation otherwise we can't speak of we support that language.

You make a valid point, but I don't know a good way to improve this. Well, there's one way: Pay translators. But, since we're an Open Source project, that's not very realistic. 

> We could perhaps add a page in the translation part where we list available locale and an ability to remove unused ones

I am not looking forward to maintaining that. :-/

**Comment by rarila** [comment]
Say I would switch to German and there was no German translation. What would that mean. I would get on some rare occasions German weekdays and monthnames. No problem, I'm used to English, I'm used to German. Switching in brain would happen without any problem and in no time.

So, the other way round would mean, I get a displayed a date like 01/02/2014, that is something I'm absolutely not used to. It would cost me quite some time and brainpower to translate that to something meaningful to me. In my example it would drive me insane, because I wouldn't know if it's the first of february or the second of january.

So from a users perspective, what is more annoying (especially when I can have both by simply switching back to en_GB when all locale are there)?

Next thing, size: one of my next PRs will shave of 330 files, about 3MB from dist. I think that outweights these additional files.

And there's still the possibilty to combine all locale to one file by combining them with grunt. That would add a few duplicated 100kb, but would probably save 2 requests.

**Comment by bobdenotter** [comment]
@rarila How's your magic "making one locale file for moments, ckeditor, datepicker" coming along? I'd like that in 2.1, if possible. :-)

**Comment by rarila** [comment]
@bobdenotter not started yet. Thought this is something we won't do while :snowflake: !?

Ok, thing to check is, would preloading ckeditor be possible as it works different from moments and datepicker. Gonna investigate into this when the tabs PR is done

**Comment by bobdenotter** [comment]
Ok. I'm going to close this one, then. And i will make a new issue with better title for 2.2.
