### ISSUE TITLE
YamlUpdater find nonexistent key fatal error

### ISSUE THREAD

**Issue by CarsonF** [bolt/bolt#2611]
YamlUpdater::find on key that doesn't exist gives me:
PHP Fatal error:  Maximum function nesting level of '100' reached, aborting!

**Comment by CarsonF** [comment]
Raising the `xdebug.max_nesting_level` to 400 fixed the test.

I still think `YamlUpdater::find` should be converted from a recursive method to a loop.

**Comment by GawainLynch** [comment]
Interesting, @rossriley started us setting `xdebug.max_nesting_level` to 2,000 in `.travis.yml` hence why the Travis tests are passing but local ones bork.

**Comment by CarsonF** [comment]
Well that's probably why :)

**Comment by bobdenotter** [comment]
Ugh, why is this a recursive function to begin with?

**Comment by tobias2k** [comment]
Because recursive approaches are the right solution for traversing
trees - except when your programming language doesn't do TCO and blows
through the stack.

On Sat, Jan 31, 2015 at 05:08:06AM -0800, Bob den Otter wrote:
> Ugh, why is this a recursive function to begin with? 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/bolt/bolt/issues/2611#issuecomment-72317137

-- 
Tobias Dammers - tobias@twokings.nl - 070-3457628 - www.twokings.nl
Maandag t/m donderdag van 9.00 tot 17.30
Voor dringende vragen, mail naar support@twokings.nl
