### ISSUE TITLE
Projectnews is not pulled from the remote source

### ISSUE THREAD

**Issue by dmm1** [bolt/bolt#2629]
When i go to the dashboard (2.0.5) there's still the 2.0.3 announcement. (on 2.0.3 was the same error) the activity log shows:

News: get from cache.. / 
in: /var/www/clients/client0/web10/web/bolt/src/Controllers/Async.php::160 (dashboard)

**Comment by GawainLynch** [comment]
This is not an error.  There is no announcement for 2.0.5 (or 2.0.4 as that wasn't publicly released in the 5 minutes between it and 2.0.5).  The current approach is to not flood people with too many announcements... 

Although, personally, this triggers my OCD when the debug bar and the announcement don't line up on a stable install.  Might be time to revisit this decision...  Ping @bobdenotter 

With the cached news, it has a timeout of two hours so that it doesn't hammer the upstream server.

**Comment by dmm1** [comment]
Thanks for your answere @GawainLynch may i suggest then to display a "bolt is up to date Admin, go for a :beer: " :smile: rather then confusing the user with an (outdated) hint.

**Comment by bobdenotter** [comment]
I like this suggestion!
