### ISSUE TITLE
Insert methods

### ISSUE THREAD

**Issue by nlemoine** [bolt/bolt#2681]
My theme is based on an extended layout that uses the Twig `spaceless` tag in order to output a compressed HTML document:
```
{% spaceless %}
 <!DOCTYPE html>
<html class="no-js" lang="{{ htmllang() }}">
...
</html>
{% endspaceless %}
```

The issue doing that way is that the `insertAfter` methods can't do their job and for example adds the `meta` tags "canonical" and "generator" after the `html` closing. 

I had a look at the `insertAfterMeta` method. To do the insertion job the right way, two elements are required: 
- a `meta` tag 
- has to be indented with a tab

In my case, the compressed HTML output removes any tab before the `meta` tags, causing the method to fail. 

IMHO, those insertion methods should not be based on the presence of a tab before the `meta` tag. Actually, I think they should not rely on a hypothetical meta tag (the base theme has one but one theme couldn't). 

A Twig function that ouputs all head, footer, etc. stuff would be more performant (it wouldn't rely on potentially slow regex) and much cleaner (wouldn't assume a meta tag is already there to make it work). 

Something like this (just an example):
```
 <!DOCTYPE html>
<html class="no-js" lang="{{ htmllang() }}">
    <head>
   {{ head() }}
   </head>
   <body>
   {{ foot() }}
   </body>
</html>
```

**Comment by rarila** [comment]
If you look at the regex ``"~^([ \t]*)<meta (.*)~mi"`` you will notice that space or tab is optional (``*``). So no indention needed.

Having to have the need for ``meta`` tag is no problem either, because if you look at the function name ``insertAfterMeta()``… it does what it promises. Use ``insertStartOfHead()`` or ``insertEndOfHead()`` then. (To be true, I don't really know why that function exists and what it's usecase is)

I guess there's a simple reason why it isn't done your way. The data you want to output probably doesn't exists at the point you render that template. Think of calling ``insertAfterMeta()`` from an extension function inside the body part.

Besides your point I just want to mention that this is kind a misusage  of ``spaceless`` as it's not meant to optimize your output as the twig documentation points out. Also it just removes whitespace between tags and not inside tags or whitespace in plain text. So probably not what you wanted to achive. Could also cost some performance

**Comment by nlemoine** [comment]
> If you look at the regex "~^([ \t]*)<meta (.*)~mi" you will notice that space or tab is optional (*). So no indention needed.

My mistake, you're totally right. 

I'll try to compress the HTML ouput with an extension. Thanks for your reply.
