### ISSUE TITLE
Rare dashboard whoops (session timeout?)

### ISSUE THREAD

**Issue by GDmac** [bolt/bolt#2948]
On some occasions (rare) when visiting the dashboard a whoops is displayed. It then popups a javascript confirm if you want to open the profiler, which then show a critical error "not logged in". Visiting the dashboard url again presents the normal login form.

This is hard to reproduce. I suspect that the browser still has a valid session, but that the backend has hit a timeout on the session. And that this causes a failure somewhere mid-process during the request handling.

**Comment by GDmac** [comment]
Got one captured :-)
![dashboard-whoops](https://cloud.githubusercontent.com/assets/156334/6390769/629eefac-bdaf-11e4-9c65-80dc95c42d71.jpg)

**Comment by GDmac** [comment]
This happens when running multiple bolt sites run on same domain. 
e.g. local.dev/site1 and local.dev/site2

Delete cookie bolt_session will resume session in Users::loginAuthtoken() with help from cookie bolt_authtoken.

However, if you visit site2 it will error on the authToken from the other site (hard)

**Comment by GawainLynch** [comment]
Can you see if the changes in #3073 / 3074 fix this for you mate… I know it's a hard one to trigger, but we we're handling non-base installs properly and it makes sense that you'd see this.

**Comment by CarsonF** [comment]
Ok I've got this one figured out. 

`Users::checkValidSession` calls `logout` if the session isn't valid, but `logout` doesn't reset the current user. 
`Backend` then checks for `isAllowed` [here](https://github.com/bolt/bolt/blob/master/src/Controllers/Backend.php#L1943) which passes because it's using the _invalid_ current user for permissions check.
Then later on, `Async` checks _only_ for a valid session [here](https://github.com/bolt/bolt/blob/master/src/Controllers/Async.php#L756) which fails and *exception* :boom: 

Resetting the current user will fix the exception and redirect to login page. That doesn't fix the root problem though, which is multiple instances clobber each other's cookies. We need to make those cookie keys unique based on `base path` and `host:port`

**Comment by GawainLynch** [comment]
Addressed in commit https://github.com/bolt/bolt/commit/4840d12d957857f95715eac257a1e10892687841 which will be in 2.3
