### ISSUE TITLE
[RFC] Bolt 2.2 Refactoring

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#2967]
https://github.com/bolt/bolt/wiki/Bolt-2.2-Refactoring

**Comment by GDmac** [comment]
cherry picking: i like the one contenttype has one table principle. text, number columns, more elaborate fieldtypes should normalise to their own table (maybe have a text column in the main table for search keywords). Abstracting fieldtypes themselves into classes.

**Comment by rossriley** [comment]
Just to clarify, I wasn't suggesting that we necessarily break the one contenttype to one table principle, we can do everything without that. 

A few people have suggested that it's not ideal since changing content types then needs an update to the db schema, and it would be neater to have a system that once deployed maintains a fixed db schema.

Obviously this then comes at the expense of a simpler/easier to understand schema.

**Comment by GDmac** [comment]
As commented on IRC, i have some question regarding the direction that fieldtypes are going. 

A basic fieldtype (like input type=text) only needs very basic methods to be able to validate, prepare for storage and display it's data in a form field. It returns the data for storage. More complex fieldtypes could implement their own storage and return simple (text) data for indexing/search functionality. Like one file field (settings) that stores locally, another that communicates with dropbox. A geo field could store long-lat-info as json or text for store locator functionality.

The base field is unaware of the content. For example, for datecreated of a content entity, it can instantiate a date type of field, but this field is not directly bound to field storage, the form returns data is validated and returned to content itself, where datecreated is stored as a property of the content object itself. Decoupling fields from storage. A field validates data that has been offered, returns data for storage (or an abstract) and can handle data itself if needed.

The field can subscribe to events if needed or implement various methods, like for example postSave, to get notified the contenttype as a whole was validated and the storage was permanent. Various other methods/events probably need to be implemented, like deleteValue(), deleteField(), etc.

```php
namespace Bolt\Field;

class BaseField
{
	// setValue($data) {}
	// getValue() {}
	// validate($data) {}

	// setName($name) {}
	// getName() {}
	// displayField($data) {}

	// setSettings($settings) {}
	// getSettings() {}

	// preSave($data) {}
	// save($data) {}
	// postSave($data) {}
}
```

**Comment by rossriley** [comment]
@GDmac and others. I've got some way into refactoring the database stuff now, so I've got a bit of a better idea of where this can fit in now.

We've got three stages that a field and its content needs to go through on its journey from the database to the screen and back again. 

At the moment all fields within a contenttype are very simple, although some of the internal ones are complex, and it would be nicer if we could handle all fields using the same philosophy. 

1. Querying
2. Hydration
3. Persistence

For something very simple like a text field then all these steps are very basic, 
1. A field from the content table gets added to the select query, 
2. At hydration, the row value gets copied to the Content object
3. On persistence the key and value get passed to the update query.

At the more complex end of the scale, for something like relations then the process goes like this...

1. Add the relation table to the select part of the query and the current content id/table to a where clause on the query.
2. At hydration the values from the query need to be read into an array and set on the content object.
3. On persistence the relations array needs to be converted and added as an additional query that updates the relations along with the owning content object.

Since we're standardising on using the DBAL\QueryBiulder then steps 1 and 3 become much easier since our Query object and Persistor objects can just be wrappers for a partially built query that all the fields have the option to either ignore or modify

Hydration stage is also fairly simple now since the fields have already injected their requests into the query so they just need to look after copying them into the Content object structure.

So this is a long way of suggesting that we give each field object access to these events via three objects, a Query object, a Hydrator object and a Persistor object, as is the case now, the defaults are all very simple but by being able to provide a custom object then we open up more advanced manipulation to both built in field types as well as extensions.
