### ISSUE TITLE
Can't inherit abstract function

### ISSUE THREAD

**Issue by isularifin** [bolt/bolt#3230]
i have got error message when updated from 2.0.6. to 2.1.3.
Fatal error: Can't inherit abstract function Bolt\Extensions\ExtensionInterface::initialize() (previously declared abstract in Bolt\BaseExtension) in /home/sloki/user/xxx/sites/xxx.com/www/src/BaseExtension.... on line 13

**Comment by bobdenotter** [comment]
This looks like something went wrong with the update.. Please try the following: 

- In `app/cache/` remove all files
- If that doesn't work, try to do the upgrade again. Make sure all files are uploaded correctly.

**Comment by isularifin** [comment]
Thanks a lot bob for your comment.
I have tried googling the issue. I have found a link like this
https://github.com/zendframework/zf2/issues/2899
is it not about PHP's bug? My site server is using PHP version 5.3.7.
Thanks.

**Comment by bobdenotter** [comment]
Hi, I've been pointed out that it may have been because you have an extension that that doesn't imlement its own `initialize()` method. Could this be possible? Try backing up, and removing the extensions, to see if it works then. If so, the problem lies with on of the extensions.

**Comment by isularifin** [comment]
hi bob, you're right. i have deleted the extention before updated. No error message. Thanks.
But my site is running without extention now. I wish i could install extention.

**Comment by rossriley** [comment]
@isularifin which extension was it, we can try and get a fix pushed to whoever maintains it.

**Comment by isularifin** [comment]
Thanks @rossriley . The extensions are sitemap, simpleform and disqus

**Comment by rossriley** [comment]
Ok, I've tracked down the problem here, and it was pretty obscure. It only manifests itself on php versions lower than 5.3.10, up until this point interface methods were considered abstract too so having abstract methods in a class that implemented an interface was not allowed.

The crux is we should not have changed the signature here of the method (especially an important interface like extensions) so I think we should remove the abstract line from BaseExtension and push out a patched 2.1.x version.

**Comment by GawainLynch** [comment]
@isularifin I have PRs in to fix this, hopefully it should be included in 2.1.4 very soon.
