### ISSUE TITLE
HTML fields are behaving weirdly in master

### ISSUE THREAD

**Issue by Pinpickle** [bolt/bolt#3256]
Their internal textarea doesn't look like its getting updated, so the content isn't getting saved. To reproduce this, make a new record of a contenttype that has an HTML wysiwyg field. Save it without changing the HTML field. On the refreshed page, update the HTML field and then try to save again. The HTML field will clear and your changes won't be saved. If it doesn't clear, refresh the page and you'll see that your changes haven't persisted

It also seems like scrollbars in them have stopped working.

![image](https://cloud.githubusercontent.com/assets/3238878/6836992/4a759a94-d3ac-11e4-9644-1ae4e541ee6d.png)

As you can see, there is more content in that ckeditor, but i cannot scroll (there's about a paragraph underneath it.

Ping @rarila

**Comment by timcooper** [comment]
The scrollbar disappearing is likely due to this:
https://github.com/bolt/bolt/blob/master/app/src/js/modules/ckeditor.js#L203

In the example contenttypes.yml stuff it suggests a config like:
```
html:
    type: html
    height: 150px
```
The px is causing `Math.max(150, '150px') // NaN` Can be fixed by either `parseInt()`ing the value or changing the yaml to `height: 150`. Not sure which is preferable?

**Comment by EJanuszewski** [comment]
I think attempting to parse would be nice incase someone does put a px unit, depends what's around the rest of the config files, whether they are just integers

**Comment by EJanuszewski** [comment]
Ok, tested and all good, however you get unsaved content warning if you navigate away even after saving the changes, doesn't occur with standard text fields
