### ISSUE TITLE
Add syntactic sugar for accessing non-db versions of select fields

### ISSUE THREAD

**Issue by Pinpickle** [bolt/bolt#3294]
If you've got different select values to what is displayed when editing it on the backend, accessing those "nicely formatted" versions is pretty terse:

```
{{ attribute(content.contenttype.fields.type.values, content.type)|default(content.type) }}
```

Would be great if we could just type

```
{{ content.type.formatted }}
```

Where `type` is the name of the field in this case. It may make sense for this to be a filter, but I can't think of a straight forward way to implement that.

**Comment by bobdenotter** [comment]
Sounds good to me. :-)

**Comment by Boorj** [comment]
Maybe for each field make a special pseudo second field, for example content.type__formatted, and generate that on each post-read operation?

**Comment by bobdenotter** [comment]
Because of "Spring cleaning", we're going to close this issue. Unless somebody steps up to help out with implementing it, it's not expected that the core team will have the opportunity to work on this soon. Keeping it open might set false expectations for people stumbling upon this issue.

This is not because we don't see this feature as potentially worthwhile, it is more to do with an overload of potential new features that could be developed combined with non-limitless amounts of available time and resources. 

If you disagree, feel free to re-open for discussion.
