### ISSUE TITLE
URLs ending with slash

### ISSUE THREAD

**Issue by HonzaMikula** [bolt/bolt#3324]
I want my URLs ending with slash `www.exmaple.org/name-of-article/`, but Bolt always removing the last slash. Is there way to turn that off? Thanks.

**Comment by bobdenotter** [comment]
This is something the Symfony router does, I believe. As far as I know there's no way to turn it off. In fact, it made us scratch our head for a whil how we could make it so that both will be accepted. 

So, you can't turn it 'off', but at least bolt will recognise a url like `www.exmaple.org/name-of-article/`. May I ask why this is important to you?

**Comment by HonzaMikula** [comment]
Because before Bolt I used different CMS and I had URL endings with slash. And in articles Facebook has issue, that when Bolt redirect to article URL without slash Facebook doesn't show correct number of likes and comments. I've tried hack Facebook, but haven't been successful until now. So if I could force Bolt somehow to ends URLs with slash, my life would be much easier. But it's fine I will keep fighting with Facebook. :-)
