### ISSUE TITLE
Error when I go to template directory in Bolt

### ISSUE THREAD

**Issue by gwbonline** [bolt/bolt#3345]
When I want to edit a template, I can go to the template folder in Bolt. But when I want to access it, I get the following error:

![screenshot](https://cloud.githubusercontent.com/assets/9332608/7046805/bbaa424e-de08-11e4-88fd-62da16be0275.jpg)

This happened with 2.1.4 and still occurs after installing 2.1.5.

**Comment by GawainLynch** [comment]
Looks like you don't have the PHP POSIX extension installed or enabled.

**Comment by gwbonline** [comment]
Earlier this wasn't an issue. Did something change in Bolt that makes this happen? I contacted the provider of our website and they say that posix isn't supported.

**Comment by GawainLynch** [comment]
Shared host providers… honestly! :grinning: 

Anyway, back into sensible mode. We've been slowly migrating more file system functionality to use Flysystem — which is the library at the bottom of that error — as it allows non-local filesystems such as Dropbox, SSH, Amazon, etc.

Easiest workaround for the time being is to fallback to FTP.  Do you have any better ideas @CarsonF?

**Comment by CarsonF** [comment]
This is a bug. @rossriley wrote that code. I'm not sure how important the explicit checks for current user are.

**Comment by bobdenotter** [comment]
@gwbonline Ross PR'ed a fix for this in #3349.. Can you confirm this fix works for you?

**Comment by rossriley** [comment]
Just to add some context, #3349 will fix the issue in that the fatal error won't occur. What it won't do, probably, is provide the functionality that we need to determine permissions correctly. 

The fallback functions probably won't correctly identify the user/group permissions.

However, the world writable flag will be interpreted correctly so this will need to be the workaround for any systems that don't have the posix module installed, both the parent folder and the file requested will need to have a world writable flag of 6 or 7. 

If you don't want to do this for security reasons then FTP is the only other option. 

Since the number of Bolt users without the posix extension will probably be very small and accurately using the posix_ functions gives an added security benefit for the majority of users then hopefully this should be a good enough compromise.

**Comment by gwbonline** [comment]
Our provider won't install and enable the posix extension because it is shared hosting. Is this such an important part that it is justifiable to only make it available when someone pays more?

The fix in #3349 solved the problem for me. I can now access the template files I need through Bolt.
