### ISSUE TITLE
Sometimes we want &nbsp;

### ISSUE THREAD

**Issue by Pinpickle** [bolt/bolt#3373]
Non breaking spaces do exist for a reason and if someone is entering them intentionally in an HTML field, the automatic sanitising could get frustrating fast.

I have no idea how to get around this because for the majority of the time, they aren't intentional or wanted and there isn't really a way to detect "intentional" `&nbsp;` entities.

**Comment by svivian** [comment]
I agree. In particular, sometimes editors will press Enter a few times to make a larger gap between paragraphs, i.e. `<p>&nbsp;</p>` but it keeps getting removed.

Perhaps `&nbsp;` can be removed *except* when it starts a line?

**Comment by lexislav** [comment]
Not sure if this comment is relevant to Your discussion, but I would like to note, that editors, at least in czech, they use  ```&nbsp;``` for example for correct text flow (keeping prepositions on spot).

So if there are plans to sanitaze ```&nbsp;```, I agree with Pinpickle that the logic would need to be more complex.

**Comment by bobdenotter** [comment]
> sometimes editors will press Enter a few times to make a larger gap between paragraphs, i.e. <p>&nbsp;</p> but it keeps getting removed.

This deserves a flogging, in my book. either: 

 - The editor needs to be flogged, because they should never, ever do that.
 - The designer / frontend-dev should be flogged for using not enough line-height / paragraph spacing in the CSS. Whitespace is free, dude / gal! 

In case of doubt, i'd err on the safe side and flog them both. Never, ever, ever use a bunch of line-breaks to add more spacing. 

> I have no idea how to get around this because for the majority of the time, they aren't intentional or wanted and there isn't really a way to detect "intentional" &nbsp; entities.

But seriously.. I think @Pinpickle is right. I don't see how we could make it so that we can somehow reliably detect whether an `&nbsp;` is added accidentaly or on purpose. So, whatever we do automagically, it's going to annoy people. In my opinion we should make this a setting, so people can choose which behaviour they like best.

**Comment by svivian** [comment]
> The designer / frontend-dev should be flogged for using not enough line-height / paragraph spacing in the CSS. Whitespace is free, dude / gal!

The regular paragraph spacing is fine. Sometimes you want an extra bit of space, and there's no way for non-technical editors to add that (for example they can't go into the HTML and add a class to a specific paragraph to increase the margin). In the real world it's often just more practical to add blank space manually.

Thanks for adding the option.
