### ISSUE TITLE
Mcrypt error

### ISSUE THREAD

**Issue by gwbonline** [bolt/bolt#3379]
I just installed Bolt 2.1.6 (new installation to convert my PivotX website) and I got the following error (screenshot). What do I have to do to make this disappear? I've read something about commenting out this module in php.ini, problem is that my provider has a general php.ini file that can't be edited by me / for me specifically.

![screenshot](https://cloud.githubusercontent.com/assets/9332608/7154586/bc187b48-e357-11e4-8bce-fa9458402e06.jpg)

**Comment by rossriley** [comment]
This is most likely your host having something setup wrong, you get this message when you try and double load an extension, either in two separate php.ini files, or when you enable a module that's been compiled in already.

If you do have any local user php.ini files check that you don't have a `extension=mcrypt` or similar.

Otherwise best to send the error to your host and get them to check their setup.

**Comment by gwbonline** [comment]
Correct me if I'm wrong. Is this module loaded twice by the host or does Bolt load it for the second time?

**Comment by GawainLynch** [comment]
Host. It is not something that bolt has control over…

**Comment by gwbonline** [comment]
Luckily my hoster picked this up and corrected a server misconfiguration that caused this error. Now everything works without errors!
