### ISSUE TITLE
Too many DB queries

### ISSUE THREAD

**Issue by mikelmi** [bolt/bolt#3436]
I have created only one page after fresh installation and I see 33 queries in the profiler.
Is it normal?

**Comment by GDmac** [comment]
Yes, it's normal. But i also pondered if the number of queries can be brought down a bit. With taxonomy and entries in menu's, things easily add up to 71 queries on a entry detail page (350ms).

One option would be to look around if certain functionality can manually be turned off. e.g. 
- autoentries, autorelations and/or autotaxonomy = true/false for a certain template/route
Small optimisations like:
- update timed publish per minute, instead of at every hit.

**Comment by bobdenotter** [comment]
A lot of these are _very_ quick queries. Nothing to be worried about, it's completely normal.
