### ISSUE TITLE
issue with template specific fields (bolt 2.1.8)

### ISSUE THREAD

**Issue by prdurand** [bolt/bolt#3506]
Template Specific Fields doesn't seem to work at all, so hard to give many information.

Following this page : https://docs.bolt.cm/building-templates#template-specific-fields
-> change the content of mytheme/config.yml according the doc page (adding some heading content types)
-> go the admin section, create a new page, save it, change the template to "index.twig"
- here I should see a kinda "please refresh to see new fields" message but nothing happens
-> Save the page, refresh the browser
- Still no change, no new fied to edit

- on Mac OS 10.9.5, Firefox and Chrome (latests)
- Bolt 2.1.8
- Tried in a customed website and also with an out-of-the-box version
- Tried with custom data and with copy-pasted from the documention page
- Tired with infrx.twig and customtemplate.twig, etc

**Comment by rossriley** [comment]
@prdurand The documentation for this is a little ahead of the current version, template specific fields are going to be in 2.2 which the beta will be released imminently.

@bobdenotter and @GawainLynch in the docs for the new storage layer I also did a version meta block for the docs, do you think we should start using this because it means we can have docs for future stuff live but with some version information about it too.

**Comment by GawainLynch** [comment]
Agreed… I was hanging off on something myself for want of a good way to approach this, but your solution works for me.
