### ISSUE TITLE
Composer install issues (was "Missing js files after updating from 2.1 to 2.2")

### ISSUE THREAD

**Issue by sbani** [bolt/bolt#3551]
Hi all,

My setup: I used composer install `create-project`
Now I ran an update to *2.2-dev* by changing the composer.json file.

Then I started an `composer update` and the commands provided in the update section in the docs.

Everything seemed to be fine but in the backend I see in browser console:

    GET http://cms.dev/bolt-public/view/js/maps/lib.min.js.map 404 (Not Found)
    GET http://cms.dev/bolt-public/view/js/maps/bolt.min.js.map 404 (Not Found)

I think there are some post scripts missing for composer update?

**Comment by rarila** [comment]
Everything ok with the files. Empty your browser cache, looks like you have the old ones loaded.

**Comment by sbani** [comment]
Whats here?
https://github.com/bolt/bolt/blob/master/app/src/grunt/concat.js#L12
https://github.com/bolt/bolt/blob/master/app/src/grunt/remove.js#L41
The only places I found the file names.

Browser cache is empty (Chrome)
Firefox displays no error

**Comment by rarila** [comment]
That is just for generation of files and for distribution generation of maps should be switched off. Check your installed ``lib.min.js`` and ``bolt.min.js`` at the end of the file if there are maps referenced. They aren't in in the repro so everything should be fine.

**Comment by sbani** [comment]
I have 2 bolt.min.js (same with lib.min.js):
One in the generated public dir "web" chosen by me and one in the vendor dir.

web/bolt-public/view/js/bolt.min.js
```//# sourceMappingURL=maps/bolt.min.js.map```

vendor/bolt/bolt/app/view/js/bolt.min.js
nothing about "map"

That's why I think the view files haven't been copied with composer update

**Comment by rarila** [comment]
Pinging composer install expert @rossriley

**Comment by rossriley** [comment]
Adding this to the scripts section in `composer.json` should take care of post update stuff:

    "post-update-cmd": [
            "Bolt\\Composer\\ScriptHandler::installAssets"
     ]

**Comment by sbani** [comment]
@rossriley I updated the composer file and changed another thing

Am I correct if I say that "post-create-project-cmd" also dispatches the event "post-create-project-cmd"??

That's what I did now

**Comment by rarila** [comment]
@sbani. I'm out here. I'm only the sourcemap generation (or not generation) guy. Composer install is not the area I normally live in :-)

**Comment by Pinpickle** [comment]
@rossriley I had no idea that existed! I had just been running the composer project creation script manually every time ._.

Thanks for making a pull request on this, @sbani.

**Comment by rossriley** [comment]
@sbani I may be misunderstanding, but I don't think you want to re-run the bootstrap after update, rather just install the assets. I'd be a bit concerned about automatically re-running the bootstrap since it re-creates the php bootstrap file which you may have made changes to.

    "post-update-cmd": [
         "Bolt\\Composer\\ScriptHandler::installAssets"
     ]

Should be better in this case. Thoughts?

**Comment by sbani** [comment]
You are right. I think we need to split the tasks.

What needs to be done on installation (or create-project):
copy bootstrap, theme, assets, configs and create dirs

What needs to be done on update:
vendors, assets, only existing themes or ask for update

What files should stay untouched:
bootstrap, configs should stay untouched because I think a merge will cause problems.
But: There can be some kind of warning if they have a diff (especially useful for bootstrap)

Another option:
Put the bootstrap outside of the Bundle. Give the user two packages: One for the composer users with a symphony like preconfigured app. And one package with bootstrap and all files in base dir. Shouldn't be that much work but it's a bigger structural change.

I'll think about the task and come back with my ideas.

**Comment by rossriley** [comment]
Ok, if you want to update your PR to use installAssets for now, then we can get that merged immediately, then we can think about improvements after.

**Comment by sbani** [comment]
Sure I'll do that.

But I have to update the ScriptHandler too! I have to ask for dirs (where to setup) on asset installation too - if i don't, nothing's happening. Or we add the dirs to the composer directly...

So please wait with merge till it's done.

**Comment by sbani** [comment]
Updated bolt script handler.

Basically, the web dir is used for installation, because it already exists and is usable for this context.
And I changed "bolt-web-dir" to "./web", because I think everybody who's using it wants to have a separated web dir.

Web dir don't need to exist because we create it on installation.

Hope you like it.

**Comment by nlemoine** [comment]
Hi everyone, 

I also exprienced some issues with the composer install process, I posted various issues about it:
https://github.com/bolt/bolt/issues/2309
https://github.com/bolt/bolt/issues/2450
https://github.com/bolt/composer-install/issues/2

Some have been resolved, some have not. The assets update partially works fine on install/update by adding `post-update-cmd` and `post-install-cmd` to the composer.json file. 

## 1 

I said "partially" because if you run `composer create-project bolt/composer-install --prefer-dist`, the  `bootstrap` method from the `ScriptHandler` class doesn't handle the update of the `composer.json` file when asking for the name of the webroot. After asking the folder name, it should write the folder name value in the `extra/bolt-web-dir` attribute. 

So if you do something like: 
```
composer create-project bolt/composer-install mywebsite --prefer-dist
cd mywebsite
composer update
```
You will end up with the assets, theme, files, etc. one level above the webroot directory :-1:  In order to make this work, you have to manually update the composer.json file and set the `extra/bolt-web-dir` according to your setup. 

I see two options here:
- Forcing developers to have a webroot named `web`
- Let the freedom to choose the webroot directory name. I made some changes on my local Bolt repository on the `boostrap` method so that it writes the `extra/bolt-web-dir` composer.json file with the asked value. Depending on your decision (@rossriley?) on these options, I can submit a PR that can handle that part if you want.  

That's the first part of the composer install issue. 

## 2

Another problem concerns the Composer scripts dispatch submitted by @sbani 
https://github.com/sbani/composer-install/commit/8177cfbb4002de2633dda4bc95c93a770a7ac364
IMO, the scripts dispatch should be:

On `post-create-project-cmd` and `post-update-cmd`:
- install assets
- bootstrap

On `post-install-cmd` 
- install assets

`composer install` command is not only used on project setup, it's also the way to install project dependencies according to a very specific `composer.lock` file. That's why your bootstrap file won't change until you run a `composer update` command. 

## 3

The last Bolt composer install issue (but still related to all this) I want to raise again is the missing CLI utility (nut) when using this kind of folder structure. This can be easily resolved by copying the `nut` and `bootsrap.php` files from what I've tested. 
Maybe the `ScriptHandler` class should contain two global methods: `onUpdate` and `onInstall`, these methods would contains sub methods like installAssets, generateBootstrap, etc. It would be easier to maintain as no changes to the composer.json file is needed (composer.json file doesn't update itself). 

==============


That's a quite long issue, probably because I'm not a native english speaker, but I think there's only a few changes needed to make all this work. Let me know what you think about this and what's your decision on point 1, I can work on a PR in a short time.

**Comment by GawainLynch** [comment]
> That's a quite long issue

Nah, it's :+1:. Thank you for such thorough detail, it's always welcome and helpful :grin: 

For whomever PRs fixes for this note that a lot has changed with recent refactoring work in master and 2.2 is LTS, so changes will need to address both branches and the commits won't be compatible.

**Comment by sbani** [comment]
:+1: thank you @nlemoine for your feedback! 

In my opinion we should use the composer file. All dirs needed no install assets etc should be part of the file. And the composer events use this file. The `create-project` event should not create the dirs.

I think about this composer file:
```json
{
    "scripts": {
        "post-create-project-cmd": [
            "Bolt\\Composer\\ScriptHandler::installAssets",
            "Bolt\\Composer\\ScriptHandler::installBootstrap"
        ],
        "post-update-cmd": [
            "Bolt\\Composer\\ScriptHandler::installAssets"
        ]
    },
    "extra": {
        "branch-alias": {
            "dev-master": "2.2-dev"
        },
        "bolt-web-dir": "./web",
        "bolt-app-dir": "./app"
    }
}
```
The directories `web` and `app` will be created during `post-create-project-cmd` but not on `post-update-cmd`. You won't be asked sth. during setup anymore.
This is the setup bolt provides with the composer-install package.

## About 1
I think you mention the same solution as I do when you talk about: 
> Forcing developers to have a webroot named `web`

## About 2
I'm with you.

# About 3
> Maybe the ScriptHandler class should contain two global methods: `onUpdate` and `onInstall`

I'm against that ;)  because you describe *what event is called* instead of *what is happening*. And a dev want's to know what is happening here. I know he can lookup what's happening in the methods, but I feel more comfortable with stating the purpose directly.

**Comment by nlemoine** [comment]
Thank you both for your prompts replies! 

> You won't be asked sth. during setup anymore.

I guess you're like me, focused on getting Bolt work outside the web root directory :+1: 
But I just realized we're maybe missing a point: 

**bolt composer install ≠ bolt outside the webroot**

Or maybe it is? But someone lead dev has to state on this. This also implies changing the docs. For now, it is clearly mentioned that both type of installation (outside webroot or not) can be achieved with composer: https://docs.bolt.cm/installation-composer

## About 1

Totally agree. 
+1 for leaving no option on the folder name. 

## About 2

See the PR above. I split the installation process into multiple methods. 
- I think that app installation shouldn't be contained by the `installAssets` method, wrong name, wrong role
- installing app process is meant to be executed once whereas `installAssets` will be ran on each update. 

If merged, composer install repo has to be updated too (post-update-cmd, etc.). 

App installation process should also take care of asking what is the developer webserver and eventually propose to add an htaccess file for apache, a piece of code to paster for nginx, etc. Or at least notify user that this files will be needed in order to make everything work. 

## About 3

I see your point, you're totally right.

**Comment by nlemoine** [comment]
Hi, 

Any decision on these topics?
