### ISSUE TITLE
Possible XSS attack

### ISSUE THREAD

**Issue by Pereida** [bolt/bolt#3591]
Hi team,

I mounted a server locally and start using bolt. I noticed that any tag can be used in the title bar for Entries/Pages/Showcases. I was able to perform basic XSS attacks, I would like to mention that the attack is possible if the attacker gains access to the bolt admin dashboard and creates a new Entry/Page/Showcase and paste the code in the title bar.

A basic example is putting `<script>alert('XSS');</script> Hello!` in the title bar. This attack is simple and obvious for the admin and everyone visiting the full site, but a carefully crafted attack can be unnoticed for some time.

![cookie-stealing-page](https://cloud.githubusercontent.com/assets/6182930/7861067/a3739ac0-0556-11e5-922a-5aa7a362b2f7.png)

**Comment by GawainLynch** [comment]
Yes, this has come up before… to add this to the database you need to be a secure user and if you can't trust your users all bets are off anyway.

**Comment by bobdenotter** [comment]
I think this is a "feature, not a bug". You can also include `<iframe>` tags in the wysywig areas, as well as  javascript.

**Comment by bobdenotter** [comment]
ha, gawain beat me to it. ^_^

**Comment by rarila** [comment]
See also #1812

**Comment by GDmac** [comment]
Maybe an extra field option for ``striptags: true`` for some fields like title and text etc.?
For backend i like @jadwigo tip"
> if we have inline html in the head it should be cleaned by doing 
   ``{{ record.title|striptags }}`` in the template.

**Comment by fabschurt** [comment]
> Yes, this has come up before… to add this to the database you need to be a secure user and if you can't trust your users all bets are off anyway.

Well, IMHO you can **NEVER** trust the users (frontend users and admin users alike). Even the most benevolent admin user in the world can be dangerous, because he/she is not necessarily very tech-savvy, and this ignorance can be exploited by some malicious people. For example, let's consider this worst case scenario where, in some Internet forum, an undercover hacker tells a blogger:

> Oh, you have a blog? If you copy-paste the following code in the content of your posts, you'll be able to blah blah blah:
>
> &lt;script&gt;some_malicious_code_which_doesnt_look_malicious_to_non_technical_people();&lt;/script&gt;”

I know this will _certainly not_ happen, but it _can_ happen, and I'm not even thinking about the other possible scenarios.

I do agree that users should be able to input HTML in some fields, but even so, I think that:

* even privileged admin users shouldn't be able to use &lt;script&gt; tags (and maybe &lt;iframe&gt; tags too) in an HTML-enabled field, as I don't see a use case for this which would make such a security issue reasonably worth it;
* only `html` and `markdown` fields should be parsed as (filtered) HTML in the output.

Currently, from what I can see in `Bolt\Content\getDecodedValue()`, `html` fields are totally unfiltered by default, which I would change to at least strip &lt;script&gt; tags out. To my eyes, what's worse is that `text` and `textarea` fields are HTML-enabled **and** totally unfiltered as well, which I think is kinda bad (I'd rather use a big fat `strip_tags` on those kind of fields).

I'd be willing to do some work about this issue if we all agree upon the fact that it _is_ an issue.

So, what do you think people?

**Comment by jadwigo** [comment]
You will never be able to prevent users from reaching the limits of your system (stop users being stupid is another way of saying that, but that's not nice to say). And if a malicious person recommends something like the following on a forum, your client might just do that:
```
<script src="//example.com/emojiscript.js"></script>
<script>replace_all_smileys_with_emoji([":-)", ";-)"]);</script>
```
Your worst case scenario in practise.

On the other hand you can be equally certain that there are usecases that need `<script>`, `<style>` and `<iframe>` tags. Be it extra tracking codes for a certain page, or an embedded survey... and the cleanest way to do that sometimes is just to input those codes into an html field.

In other cases you also need text and textarea fields with html - for example if you want to use a dedicated textarea field for inserting a youtube embed code without a rich text editor in your admin interface, or even to insert a certain script block for tracking that you don't want inside your html block.

You are free to `strip_tag` all unwanted html from those fields in your front-end templates, and twig actually makes that easy for you. But in the back-end of bolt we chose to trust the users with the responsibility of keeping their site safe. 

The alternative is almost impossible to implement, you simply can't make a 100% secure system.

In reality you need to preserve the users input as much as possible, because some sites need lots of attributes for metadata, schema.org and microformats and maybe some javascript framework control codes. This is really hard to sanitize, for an illustration just refer to http://stackoverflow.com/a/1732454/1531963 .
In practice it is also also very unclear, you just need to look into the questions about the text input formats in drupal and why they do not work the way people expect them to for an indication of the resources we would have to dedicate to supporting it.

My opinion is that **not** running everything through an xml/html/regex/sanity/insanity parser happens to make for an easier and lighter CMS that reacts predictably to end-users.

The security implications are known to us, and we try to educate our clients about those too. And it is your responsibility to do the same.

So after explaining why we didn't do it yet, I agree that it is an issue. I also believe that it is unfeasible to solve this issue at the moment. If you can prove me wrong and it also passes https://docs.bolt.cm/manifesto I'll happily merge the pull request

**Comment by fabschurt** [comment]
> On the other hand you can be equally certain that there are usecases that need &lt;script&gt;, &lt;style&gt; and &lt;iframe&gt; tags. Be it extra tracking codes for a certain page, or an embedded survey... and the cleanest way to do that sometimes is just to input those codes into an html field.

Those use cases exist of course, and I agree that there's not always a clean and secure way to handle them. The cleanest solution would involve parsing the HTML, extracting the &lt;script&gt; tags and their content, statically analyzing a &lt;script&gt; content and finally allowing/denying a &lt;script&gt; according to some regularly updated whitelist rules… So in the end it's really complicated (and not necessarily worth the pain) and far beyond the scope of Bolt alone.

> You are free to strip_tag all unwanted html from those fields in your front-end templates, and twig actually makes that easy for you.

Yes, in fact, that's what really bothers me. I don't really mind &lt;script&gt; tags being input into the DB and passed to Twig output as is, but I think that auto-escaping would be far less error-prone. `Bolt\Provider\TwigServiceProvider` has `autoescape` enabled by default, but the fact that field values are wrapped with `\Twig_Markup` in `Bolt\Content\getDecodedValue()` cancels the escaping. Wouldn't it be cleaner if auto-escaping was the norm and raw output the exception?

**Comment by GawainLynch** [comment]
@fabschurt thank you, for at the very least taking the time to present a detailed argument, it is far more detailed than a lot of what — that ends up being simple hyperbole — we get on the subject.

However, the (valid) attack vectors you're pointing to are social engineering 101… and if you can talk a user into changing one area they have access to, or giving you (the nefarious hacker) access, as I said initially, all bets are off:
> Here, just add `{{ <script>there_can_be_only_one();</script> }}` to your Twig template.

We also have to consider BC. If I had my own way, I would lock down everything. But that takes a structured overview of the entire system, and is nothing short of a massive job. That, and there are far better attack vectors that can be leveraged already… that everyone seems to miss in these GitHub conversations :wink:

**Comment by fabschurt** [comment]
> However, the (valid) attack vectors you're pointing to are social engineering 101… and if you can talk a user into changing one area they have access to, or giving you (the nefarious hacker) access, as I said initially, all bets are off

Absolutely.

> If I had my own way, I would lock down everything.

Me too :smile: I'm the paranoid type.

I've been thinking about it, and indeed the best approach must be to let the Bolt core be as flexible as possible; total lockdown isn't fit for the general case. I'm planning on building a small extension or provider which would satisfy my paranoid appetites, and the thing that's really nice is that Bolt is so easily extendable, so it'll be a snap.

**Comment by GawainLynch** [comment]
Yeah, an BoltParanoid extension, I can this being very useful. I'd install it :+1:

**Comment by fabschurt** [comment]
That's exactly the name I had in mind :sweat_smile:

**Comment by jadwigo** [comment]
Hey, I'd install it too - on my personal bolt sites :smile:
