### ISSUE TITLE
Thumbs not working in localhost

### ISSUE THREAD

**Issue by zomars** [bolt/bolt#3629]
Ok this has been an issue for a while and haven't found any awnsers in the previous issues so here it goes, I'm testing this in a clean install of Bolt and even in the base theme I can't get the thumb generator to work properly.

This is my result:

![captura de pantalla 2015-06-04 a las 13 04 52](https://cloud.githubusercontent.com/assets/3504472/7992190/e23807d2-0aba-11e5-95f9-58d2fe823932.png)

And this is my the `mod_rewrite` portion of my `.htaccess`:
```
<IfModule mod_rewrite.c>
  RewriteEngine on

  RewriteRule cache/ - [F]

  # Some servers require the RewriteBase to be set. If so, set to the correct folder.
  # RewriteBase /

  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteCond %{REQUEST_URI} !=/favicon.ico
  RewriteRule ^ ./index.php [L]

</IfModule>
```

Once uploaded into a test server the thumbnails seems to be working fine, I'm pretty sure I'm missing something, me and my partner both have this problem, we are developing in OSX yosemite using the native server Apache 2.4.10 and using PHP 5.5.20.

Any guidance is deeply appreciated.

**Comment by GawainLynch** [comment]
We were just talking about this on IRC… the tie in between both seems to be OS X. Do you have some Linux hosts you can (temporarily) test this on?

**Comment by zomars** [comment]
Actually I found my problem, I'm using a grunt development environment and the server task replaced the native PHP server with it's own grunt-php package, I simply removed it from my Grunfile and that fixed the problem for me. Sorry for any inconvenience.

**Comment by GawainLynch** [comment]
Excellent… closing this then, but please feel free to reopen if needed! :grin:

**Comment by lumiworx** [comment]
I hate to revive the issue, but I'm experiencing the same thing on windows 7 with a local xampp install. No thumbnails get created or shown in a published page. The linked image displays in the popup properly, but the placeholder on the page itself is broken.

I'm using a slightly css tweaked copy of the default base-2014 theme, but aside from that I'm still using the default twig template with a new/default page. My xampp has been modified with newer php & mysql versions - so it's not a vanilla xampp install, but that shouldn't affect anything with how Bolt is running. In my case, I have PHP 5.4.4, and Apache 2.4. since these versions were set to match my production server (and updating there isn't possible).

I just updated Bolt with a fresh download to 2.2.16 after seeing the dashboard announcement, but the issue remains the same after the update. I'm not sure what the previous version was, but it was originally loaded about a month ago.

Some additional details...
On looking at a 'view source' on both an admin edit page (for adding a new 'page') and the front facing published page; the expected thumb path on both shows as "/bolt/thumbs/100x100c/2016-01/tie-wall-2.jpg' for the newly uploaded image. There was no "/bolt/thumbs" directory in place at all until I manually created one, thinking that there might have been a path issue and without it being there already, bolt could not dynamically create the further sub-directories needed to generate and link the thumbnails into. After creating it and retrying I still show it as broken. Clearing the cache - before or after an upload - had no effect. No directory or thumbs generated.

The image files themselves do, in fact, get uploaded correctly - a directory does get properly created within '/bolt/files' as "2016-01" - and everything then shows correctly as a newly created link within all the stack references, and on any page created with that embedded image. The '/100x100c' directory I presume is generated and assigned by bolt does NOT get created anywhere... not within '/files', '/thumbs', or anywhere within the cache, either by name/reference or as data.

However - I do find a generated thumb image within the cache data, and it does follow the sizing dimensions setup in the site config. File naming seems correct too, as: "bolt-thumbs[2016__01_tie__wall__2-jpg__100__100__crop][1].data"

I also just tried to edit a page on the demo site and was able to upload a new image - and get a thumbnail properly generated and displayed in the published page - so - it's obviously working there.

This all makes it difficult to get a site prepped locally and then post it to a production server with pages and associated files intact. I suppose I can retrieve the cached thumb files and move/rename them - create any sub-folders - then edit/publish pages... but that's quite a bit of extra stuff as a workaround.

If I can make a suggestion for the Devs too... Consider creating a '/thumbs' directory within the default install structure, and populate it with at least an empty index.html file. At least that will insure there's already a base directory in place and with the proper permissions assigned during the initial install.

**Comment by bobdenotter** [comment]
Hi @lumiworx 

> If I can make a suggestion for the Devs too... Consider creating a '/thumbs' directory within the default install structure, and populate it with at least an empty index.html file. At least that will insure there's already a base directory in place and with the proper permissions assigned during the initial install.

If you create a page in Bolt, it'll get a URL like `/page/lorum-ipsum`. There is no _folder_ `page/` on the webserver, it's all handled by Apache or Nginx. Same thing with the thumbnails. There doesn't have to be a `thumbs/` folder. Your webserver should handle it. 

What is the actual error you are getting if you open `/bolt/thumbs/100x100c/2016-01/tie-wall-2.jpg` in your browser? 
I am pretty sure your PHP set up is missing a library. Going to the thumbnail in your browser will likely tell you exactly what's wrong.

**Comment by lumiworx** [comment]
Opening the URL you suggested did, in fact, give me a generated error notice...

Bolt - Fatal error.

    Class: LogicException
    Message: Unable to guess the mime type as no guessers are available (Did you enable the php_fileinfo extension?)
    Code: 0

A quick check of php.ini showed the line for extension=php_fileinfo.dll was still commented out, so a simple edit and a restart of Apache had everything solved in under 30 seconds.

Thank you for the quick response - and the perfect fix.
