### ISSUE TITLE
As a web admin, I would like to be able to update bolt from the admin interface.

### ISSUE THREAD

**Issue by tomntech** [bolt/bolt#3673]
As it stands I need to either have a working knowledge of hosting, FTP etc, or I need to ask my web developer to update my website. I would like to be able to update the Bolt core from within Bolt itself. 

Developer note: Considerations towards config files, php.ini, .htaccess, index.php etc would have to be made. The approach taken with the files that have a .dist is a sensible approach and could be applied to these also.

**Comment by GawainLynch** [comment]
I actually have a branch started for this, since October 2014, but it is really hard to solve for a number of reasons:
* We have git, composer and archive file installs
* Each install has different requirements
* There is no write guarantee on anything except the cache directory

**Comment by rossriley** [comment]
I can't really see how we could do this without having some fairly big security implications.

I'm guessing that the majority of users still install Bolt in the same directory as the web root and this essentially means we'd have to hand over full write access to the codebase to the web-server.

One possible idea would be to allow the UI to schedule an update that the cron nightly job would pick up next run (since the cron will run as the app user). I'd have thought, though, that this would lose some of the instant feedback you'd be expecting by doing a UI Bolt update.

**Comment by GawainLynch** [comment]
> I can't really see how we could do this without having some fairly big security implications.

Yeah, that's part of the problem too. Mind you, it's not like it's ever created problems for WordDepress… :stuck_out_tongue:

**Comment by tomntech** [comment]
Being able to schedule something to run as a nightly job wouldn't be such a bad solution. Perhaps a scheduling assistant could be put in place. For example, an update becomes available and is advertised in the UI. A user can then accept the install of the update and it is added to a queue to be accepted by an admin. Once an admin is happy with the update he/she can process the queue which adds it to the nightly cron. As long as the user knows when the update is going to happen and gets some feedback once it is complete I would consider that as meeting requirements.

Security is a big concern here and it is important that certain protections are put in place. The main justification for this requirement is that some admins don't have SSH access and FTP can be very slow when managing multiple sites.

**Comment by CarsonF** [comment]
Users don't have SSH access but they do have crontab access? :dizzy_face:

**Comment by tomntech** [comment]
A number of my clients have cloud hosted sites which allow for cron jobs to be setup but don't have SSH. When I setup a site on a clients host I normally have access to configure cron jobs but don't have SSH once the initial job is complete.

I also know of a few hosts which run CPanel and don't allow SSH unless you pay extra for the functionality. This is normally way above the requirements of sites that are being hosted on them.

**Comment by aerth** [comment]
Checking Permissions before Update...

:red_circle: ./app/config
:red_circle: ./app/database
:green_heart: ./app/cache
:red_circle: ./src
:red_circle: ./vendor
:green_heart: ./theme/
:green_heart: ./files/

Update is not possible until issues are resolved. Please chmod/chown to allow the web server to write to the bolt directory.


^ maybe something like that. some ppl wouldn't bother using it but in many situations it would work. For example with no SSH access and everything is chown'd to ^www-data

**Comment by GawainLynch** [comment]
@aerth The problem still remains that a lot of sites/configurations will never have, and to be fair **should never have**, write access to `src/` and `vendor/`.

**Comment by tomntech** [comment]
Slightly out there idea but how about a distributed version of Bolt? The core files reside in a CDN and users have the ability to upgrade which version they are going to use by pointing at different paths on the CDN. Themes, extensions, db's etc stay on the individual web hosts, just the core files are shared...

Might not be possible, but an idea.

**Comment by GawainLynch** [comment]
> The core files reside in a CDN and users have the ability to upgrade which version they are going to use by pointing at different paths on **`<insert-storage-location-here>`**

Funny you should mention that… This crosses over with a greater idea/plan/desire that I have been chipping away at for a while now. There are foundational parts working and [documented](https://docs.bolt.cm/howto/muti-site-setup). 

I use that presently with two Bolt repositories, first one on `release/2.2` and the other on `master`. 

So to switch versions, it is a one-line change in my Nginx **site** configuration file, and a *reload* of Nginx  (full restart of Nginx not needed) and Bolt will detect the version change and flush caches… 

…away and running in seconds on different Bolt versions.

**Comment by SahAssar** [comment]
@GawainLynch Sure, but that only works on a single server, not as a distributed system for multiple FTP only webhosts.

@tomntech Pretty sure the "distributed" approach wouldn't be possible in any good way, since we're talking about server side code and as others have said above, doing the "update from web interface" approach would require excessive write access.

If you have clients that only have FTP access and you want to update them automatically you can set up a script that does that from another host by checking for new bolt versions and FTP'ing them to the client's server each night.

Closing since this does not seem solvable in a good way for the people it would help most (folks with FTP but no SSH).

Feel free to reopen if anyone cracks a good way of solving it :)
