### ISSUE TITLE
As a web designer, I would like to access a community of fellow bolt users to discuss web designs and techniques.

### ISSUE THREAD

**Issue by tomntech** [bolt/bolt#3674]
It would be great if the Bolt user base could get together to form a forum for web design thoughts discussions. Posting project pictures or links to dev sites and then gauging fellow developers feedback would help enhance the quality of Bolt sites.

**Comment by inspirebin** [comment]
There is already an IRC chat for this purpose: https://bolt.cm/page/irc

**Comment by bobdenotter** [comment]
True, there's the IRC channel, which is used a lot.. But, I can see how it could be beneficial to have a more community-like site. A place to post snippets, socialize and stuff.. IRC is very fleeting by nature, something a bit more permanent would be nice. ^_^

**Comment by inspirebin** [comment]
@bobdenotter  why dont we use something like stackoveflow

**Comment by GawainLynch** [comment]
@inspirebin we do and it is more than useless. We have had moderators remove replies by our core developers and all sort of shenanigans… To quote Obi Wan:
> You will never find a more wretched hive of scum and villainy.

**Comment by Boorj** [comment]
Yes, community will produce lots of content that is searchable by search engines, and it's good for promotion.
Is there a nice forum engine that you guys like?

and @inspirebin 's idea is nice in basics - we even can put a link in bolt's *help section* to stackoverflow's search results with ```boltcm``` tag put in, and any question could be asked there (or not, because the answer is already present on SO). Probably a conversation with moderators could solve the problem with hive of villainy. It's good for community and promotion, so seems it's worth developing.

**Comment by SahAssar** [comment]
Perhaps a subreddit would be a good solution?

**Comment by GawainLynch** [comment]
@SahAssar the push at the moment is Slack… DON'T GET ME STARTED @bobdenotter :laughing:

**Comment by SahAssar** [comment]
Since this issue has been opened we have both opened/made official a slack channel and our new [forums](https://discuss.bolt.cm), if this does not satisfy the need please feel free to reopen.
