### ISSUE TITLE
As web admin, Uninstall of an extension

### ISSUE THREAD

**Issue by mgageo** [bolt/bolt#3691]
When I try to uninstall "dsduit/big-picture-html5up - 1.0.0Derk Duit", I have this message:
Composer Error
Failed to execute git status --porcelain --untracked-files=no
error: bad index file sha1 signature
fatal: index file corrupt
%ERROR_LOCATION%

The site is in Bolt 2.2.2

**Comment by GawainLynch** [comment]
That is coming from the Composer cache, which is stored in `app/cache/composer/`. Can you try flushing the cache in the admin menu and retrying as something has become corrupt there.

Also, did you install v1.0.0 or dev-master of that theme?

**Comment by mgageo** [comment]
I have the same response after clearing the cache (web admin).
Idem after clearing with nut

It's the vesion 1.0.0

**Comment by SahAssar** [comment]
@mgageo Are you still having this issue in current (v2.2.11) bolt?

**Comment by SahAssar** [comment]
Closing since the issue seems to be "nonpresent" in current versions...

If you are still seeing it in current versions please feel free to reopen! :)

**Comment by SahAssar** [comment]
Closed #4236 and reopened this.

**Comment by SahAssar** [comment]
According to the fine people on irc this "looks like an composer <-> old git version mismatch or something". Could you update git and try again?

**Comment by mgageo** [comment]
The service is on a shared hosting, the version of git is 2.2.0 (december 2014)

**Comment by GawainLynch** [comment]
I would recommend raising an issue with your provider. This problem is coming directly from `git` itself, and has nothing to do with Bolt.

Basically what happens in that the Composer library creates a base in `app/cache/.composer/` and in there it clone repositories. If for any reason the index file is not downloaded or updates fail to build a new index, then it is marked as corrupt and the error you see is thrown.

Given that we have no control over what your host does, or how it is configured there is just absolutely nothing we can do :disappointed:
