### ISSUE TITLE
[RFC] New way of thumbnails generation

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#3703]
### Intro

Current way of thumbnails generation has several disadvantages
**1**. it's insecure to let any visitor to create any image by request. If you have /images/1.jpg, server space can be filled with requesting for 

> /thumbs/**1x1**/1.jpg
> /thumbs/**1x2**/1.jpg
> /thumbs/**1x3**/1.jpg

**2**.  If you have several implementations of your thumbnail size in twig template and willing to change resolution of the thumbs, you have to change this resolution in each place.

> {{ record.photo|showimage(800, 600) }}
> // 800 and 600 has to be changed everywhere

**3**. If you want to do some other transformations (like black and white processing or crop) - you also have to change it.

**4**. Case: you have 100mb serverspace free. Each thumbnail is about 50kb, when you have 20000 thumbnails generated, server space is busy.
Without a thumbnail generation tool (like cache:clear) or nut command - it could happen unexpectedly.

**5**. Folders for thumbnails are heavily hardcoded. It would be have flexibility to setup naming thumbnail folders.

**6**. Case: i want to let user upload huge images, but don't want them to be available in web folder. Only resized versions or versions with some watermarking. How can i restrict access to original images? i think it could be achieved with **5** by setting folder for uploads outside the web wolder.
### Proposal:

Make a thumbnail (resize , process) config  for each image/imagelist contenttype.

``` yaml
#contenttypes:
user_contenttype:
    photo:
        label: "It's a photo, dude"
        type: image
        resizes:
            resize1:
                size: [320,200] # other setting are set by default
            preview:
                size: [800,600]
                upscale: false
                format: 'jpg'
                type: 'stretch' # 'fit' / 'fill' / 'crop'
            thumbnail_renamed_and_processed: 
                size: [200,166]
                filename: "%date%_%dimensions%.%original_extension%"
                folder: "%thumbs_folder%/carrots" # relatively to %web_folder%
```

and so it will be used like

``` twig
{{ record.photo|thumb('resize1')}}
or dynamic filter generation (just a fantasy :)
{{ record.photo|preview}}
or perhaps
{{ record.photo__thumbnail_renamed_and_processed}}
```
### Backwards Compatibility

I think for a while it could be used in special mode in config, that is set by default to old style of thumbnail generation. And if you want to use the new style - just add 

``` yaml
#config.yml
new_thumbs_or_whatever: true
```

**Comment by rarila** [comment]
Disregarding all other points I wouldn't bind this to a contenttype, I would prefer a global setting in config.yml. That way named thumbnail settings could be reused for various contenttypes.

**Comment by Boorj** [comment]
indeed it could be globally set and used by name in contenttypes.
like here
https://github.com/liip/LiipImagineBundle#basic-usage

**Comment by jadwigo** [comment]
:+1: I would love something like this

I don't think the config switch is even needed for compatibility. If you create or update a site just create the thumbnail presets with the corresponding folder names and have the `{{ thumbnail }}` and `{{ image }}` twig accept the "old" way too.

**Comment by Boorj** [comment]
one of goals was to restrict that kind of generation, because anyone can create tons of thumbnails of different resolution.
One of solutions is to make a nut command to generate all thumbnails at once, and don't allow users to create thumbnails by request after that.

**Comment by jadwigo** [comment]
Such a command is cool, but it would have limited daily use. The diskspace is one of the concerns, but you cannot solve it 100% with limiting the thumbnail generation. 

New images will be added to the site in the daily running of any site. And if you have a large and active site you will run into diskspace limits anyway... the many thumbnails are just a small symptom.

The problem that will be solved by this way of generating thumbnails is that visitors can't randomly generate millions of thumbnails in other sizes than those that are used in the site and spam your diskspace that way.

And the really cool thing about this proposed thumbnail processing is that you could do presets with effects other than crop and scale. so you could add a transparent mask, a colour filter, an overlay, a transform or even more stuff to a thumbnail.

**Comment by Boorj** [comment]
yes, watermarking is one more thing that could be solved by this

**Comment by aerth** [comment]
+1 for watermarking! Good idea. I find strange things happen while thumbnailing extra wide or tall images. Would be great for editors to have a cropping tool while uploading/inserting a photo.

**Comment by SahAssar** [comment]
Moved this to the forums: https://discuss.bolt.cm/d/140-new-way-of-thumbnails-generation-continuation-of-3703

**Comment by GDmac** [comment]
I think a quick implementation to prevent runaway thumbnail generation would be possible.
Add some ``config-allowedSizes`` to the thumbnail provider (or empty array for old BC behaviour)
https://github.com/bolt/bolt/blob/master/src/Provider/ThumbnailsServiceProvider.php

and on https://github.com/bolt/bolt-thumbs catch those new settings

**Comment by Boorj** [comment]
would be nice to have any chance to close that hole.

**Comment by SahAssar** [comment]
Just found this that I hadn't seen before: http://symfony.com/doc/master/bundles/LiipImagineBundle/index.html

Seems like it does most of what has been requested in this thread, might be possible to integrate as an extension or as a part of a #574 solution?

**Comment by Boorj** [comment]
lovely idea, used that bundle in Symfony2. not sure if it's heavy for Bolt or not.

**Comment by GDmac** [comment]
This was somewhat lost on my radar 
(because i do log in to github more often than the forums)

i've started a branch to limit/control the amount om image sizes that thumbs creates
https://github.com/GDmac/bolt-thumbs/commit/4f672a0f48ce080a98a2aab4640793911922e225

The idea is to have in app config.yml an array with allowed_sizes
```
thumbnails
  allowed_sizes:
    widths:  [ 54, 80, 100, 160, 200, 400 ]
    heights: [ 41, 60, 100, 120, 150, 260 ]
```

Another suggestion was to have named sizes, ``thumb_base: [72,72]``, ``preview: [300,300]``
Would like some input on what ideas and wishes are

**Comment by bobdenotter** [comment]
@GDmac Would be a nice feature to have indeed! :-)

**Comment by sbonardt** [comment]
Nice! I favor the named sizes option. IMO it make things a bit more intuitive and clear for the user/site-builder. The widths and heights are (visually) paired as well, in that way.

I like it. It's a good addition! :+1:

**Comment by rarila** [comment]
@GDmac FYI I have responsive and high dpi aware thumbnails in the works so that multiple values (48x…, 64x…, 92, … 256) have to be added for internal use then.

**Comment by GDmac** [comment]
@rarila That initial fork/branch has basic hdpi detection for @2 images
``if (strpos($this->file, '@2x') !== false)`` 

Seems there is a whole range of scale factors
```
ldpi | mdpi | hdpi | xhdpi | xxhdpi | xxxhdpi
0.75 | 1    | 1.5  | 2     | 3      | 4
```
http://stackoverflow.com/questions/14381965/image-size-drawable-hdpi-ldpi-mdpi-xhdpi

Should these be implemented with modifiers like the ``@2`` modifier?

**Comment by rarila** [comment]
I don't use those, just ``srcset``/``sources`` and let the browser decide which is best.

**Comment by GDmac** [comment]
If you want to restrict generating arbitrary thumbs. which is the idea of this (optional) feature,
then yes, you have to define all ``allowed_sizes``. Or come with a suggestion for 
a mechanism to calculate allowed sizes.

One idea could be even to define the srcset sets in config and have it both ways.
Give thumbnail() the defined srcset and because it is defined, it is allowed.
Again, the whole purpose of this feature is just to prevent arbitrary image generation on the server.

**Comment by Boorj** [comment]
the idea with `thumbnails:  allowed_sizes` is little bit unsafe: you still can get innumerous amount of combination, enough to be insecure. 
i love an idea with `{ size1:[160,120], size2: [150, 'any']}`. So 'any' could be used to allow any height in this example. Also you can use aliases for resolution combinations.

**Comment by GDmac** [comment]
Yes boorj, i was thinking about using ``[150,0]``. 
This uses the (currently not documented) thumbs autoscale feature.
https://bolt.cm/thumbs/200x0r/2014-12/featureimg_rsponsive.png
https://bolt.cm/thumbs/400x0r/2014-12/featureimg_rsponsive.png
https://bolt.cm/thumbs/600x0r/2014-12/featureimg_rsponsive.png
is that what you mean, or did you mean opening another dos wildcard?
150x1
150x2
150x3

**Comment by cdowdy** [comment]
@GDmac that's how I do this [here](https://github.com/cdowdy/boltresponsiveimages) for a bolt responsive image extension with usage examples [here](https://github.com/cdowdy/boltresponsiveimages)  

What I'm really wondering is if the Imagine bundle is out of scope? This can limit thumbnails to certain sizes, [relative resize](http://symfony.com/doc/master/bundles/LiipImagineBundle/filters.html#the-relative-resize-filter) like the undocumented part gdmac spoke about above, store images on say S3, allow advanced users to switch from GD to Imagick, use better optimizers on our thumbnails, and this last one is really kinda why I was curious haha... allow for us to determine cropping (I'm working on a picture element extension and currently the bolt/thumbs isn't a fan of determining crop position .... unless im a derp haha )

**Comment by rarila** [comment]
@GDmac hmm, after rethinking we probably don't interfere at all as my stuff is backend contenttype listings (and later file browser thumbnails) only.

And yes, allowing arbitrary sizes does only makes sense using the ``0`` auto parameter.

**Comment by Boorj** [comment]
@GDmac , speaking in terms of wildcards, i meant that 150×* could be allowed

**Comment by bobdenotter** [comment]
> @GDmac , speaking in terms of wildcards, i meant that 150×* could be allowed

Doing that, completely defeats the purpose of this proposal. You could still "ddos" a server by requesting a million different images.

**Comment by rarila** [comment]
The idea of @C4Grey mentioned in #5016 sounds somehow like a much better idea as it frees you from having to set and maintain allowed sizrs. What do the security experts say?

**Comment by bobdenotter** [comment]
Nope, I'm not in favor of that, at all. I really like that the mapping from a file to a thumbnail is _logical_ `files/foo.jpg` -> `thumbs/400x300/foo.jpg`.

**Comment by SahAssar** [comment]
Also, adding a query parameter would break certain proxies caching.

**Comment by Boorj** [comment]
>> @GDmac , speaking in terms of wildcards, i meant that 150×* could be allowed

> Doing that, completely defeats the purpose of this proposal. You could still "ddos" a server by requesting a million different images.

Actually, I meant that you can consciously add that unsecure option. For example locally, whil developing and later, when project is finished - just set the final set of possible resolutions.

**Comment by bobdenotter** [comment]
> Actually, I meant that you can consciously add that unsecure option. For example locally, whil developing and later, when project is finished - just set the final set of possible resolutions.

But, then you would just _not_ set it before, and set the "secure" settings in your `config_local.yml` live. Allowing wildcards in this feature has no use whatsoever.

**Comment by rarila** [comment]
@SahAssar Why a parameter, why not ``thumbs/abcdef12345/400x300/foo.jpg``

**Comment by rossriley** [comment]
We've got conversation over a few places. @rarila that was the process I suggested over here: https://discuss.bolt.cm/d/140-new-way-of-thumbnails-generation-continuation-of-3703/6

I personally think that's the correct way to do it, It's how most other libraries I've used have done it as well. 

I'm pretty sure that even a basic theme will end up having so many permutations that maintaining a whitelist will be unmaintainable.

I'm not against the whitelist idea completely, just that I think it may end up being something that not many users will end up implementing.

**Comment by rarila** [comment]
@rossriley Thanks for the link.

I also think that whitelisting could be a hell of work. Might work for some simple sites. But now think of serving different sizes via ``srcset`` or ``<picture>``. And with every change in design you have to change or add values and what's most of the time more complicated do some garbage collection and find out what sizes aren't needed anymore.

I think Bolt is here to makes things easy and for me that hmac security key seems to get you security out of the box without any extrawork.

As for the cons mentioned by @GDmac on the forum:

> Somewhat unfriendly urls

Nobody has to type them or remember them, you won't even see them in the adressbar.

> Calculate hmacs for every request

The solution with subdirs was suggested just below. So if the file is there it can be served without any overhead directly by the webserver and only a missing image would cause a hmac calculation.

**Comment by SahAssar** [comment]
@rarila Well, adding a query parameter was what was sugessted in #5016, but the reason for not having it in the path would be that it wouldn't allow the image to be served directly by the webserver, right? Or is the idea to create the folders in the thumbs dir that correspond to the hashes?

**Comment by SahAssar** [comment]
reopening cause it was closed when we thought these discussions were going to be had in the forums. :smile:

**Comment by cdowdy** [comment]
I know I'm beating a dead horse it seems with the liip imagine bundle but to me it seems to solve all the mentioned issues. You set an array of sizes you want and that's it. Only those images can be generated. If you want responsive images like srcset as @rarila mentions you use a runtime config option or someone creates an extension that is either a twig function or filter to generate sizes passed in through the twig template. This also opens up better picture element usage for art directed images

**Comment by rarila** [comment]
@SahAssar the idea is to create the image directly in the hashname folder so the ``RewriteCond %{REQUEST_FILENAME} !-f`` rule (or the nginx equivalent) we already have would fire and the file is then directly served by the webserver.

The only thing todo is probably splitting the hash to multiple dirs to prevent too many files/folders in one folder. But I think that's an easy to solve implementation detail.

So that isvwhat should happen:
- request ``thumbs/abcdef12345/400x300/foo.jpg``
- webserver doesn't find the file and starts index.php
- the hash is checked -> ok
- the resized image is saved to.``thumbs/abcdef12345/400x300/foo.jpg``
- the file is served

Next request:
- request ``thumbs/abcdef12345/400x300/foo.jpg``
- webserver finds the file and serves it

Next:
- request ``thumbs/faultyhash/400x300/foo.jpg``
- webserver doesn't find the file and starts index.php
- the hash is checked -> false
- send a 404 or whatever
- optionally log the request for *fail2ban*

Am I missing anything?

**Comment by SahAssar** [comment]
@rarila Yeah, got it. For anyone else that comes along, I deleted my original comment since when I read the rest of the comments after replying I realized that the question had been answered.

**Comment by rarila** [comment]
@cdowdy That's still having to maintain a list of sizes vs. having to care for nothing. Just fire the twig function with the desired size and here we go.

Other possible problems:
- the designer is allowed to edit templates, but not the config (can this happen with our permissions?)
- support stress:"my thumbnails are not found"

**Comment by bobdenotter** [comment]
I've mentioned it before, and i will say it again: We **will not** have any sort of hashing in filelnames for thumbs. 

Two reasons: 

 - I really like that the mapping from a file to a thumbnail is logical `files/foo.jpg` -> `thumbs/400x300/foo.jpg`.
 - Adding hashes is virtually useless when it comes to "protecting CPU". Repeating calls to images are fast, because (usually) it's just a file request on the server. Requesting a _new_ one takes longer: Bolt gets bootstrapped, image gets created, cached and served. However, this bootstrapping takes the majority of the overhead, so bailing out after validating a hash makes very little difference when somebody is trying to bog down a server.

**Comment by GDmac** [comment]
For extra functionality i would like to suggest to dispatch an event "generate thumb". 

- You could then catch the process if you want to add hashes to the path or set validation callbacks etc.
- Also, you could then even use that event to auto-generate the whitelist (store every unique request during dev for easy pasting into the thumb presets for production environment).

**Comment by bobdenotter** [comment]
> You could then catch the process if you want to add hashes to the path or set validation callbacks etc.

To be honest, this sounds like overengineering. You don't need this, and it only adds complexity and overhead. Let's just go ahead with the original idea: Optionally whitelisting a set of approved dimensions.

**Comment by rossriley** [comment]
Let's see what floats in the end. We can add the preset sizes as an option, but make sure that it's turned off by default, since most users probably will not  need the extra mental overhead.

It's important to note with the hashing method that you are not hashing the images or doing anything CPU intensive. What you create is a secure message hash of the url, all you will be proving is that the code that generated a URL had the authority to generate a new thumbnail image. So what you are preventing is the CPU / resource usage of generating lots of new images (which can in some cases be up to 3-5 seconds) versus the CPU overhead of serving a 404 which is 100-200 ms.

This functionality could easily be provided as an extra addition to the bolt/thumbs package when someone has the time to work on it and it doesn't need to be in core since it's a couple of twig helper functions along with a new ThumbnailResponder controller which in itself is already a separate composer package.

**Comment by rarila** [comment]
@rossriley yep, I don't think creating the hash over those few bytes takes very much longer than comparing the sizes when, as bopp said, the bootstrap itself is the bottleneck.

And if bootstrap init + creating a hash makes one worry, is the login somehow made save as I could also hammer that one.

Not to forget that there's mentioned fail2ban that could stop that attack vector

**Comment by cdowdy** [comment]
> That's still having to maintain a list of sizes vs. having to care for nothing. Just fire the twig function with the desired size and here we go.  

@rarila  The liip imagine bundle isn't that much different than what is currently in bolts config. Its a lot more verbose though- but also gives the designer/developer more control over image quality etc.   

```yaml  
# Imagine 
 filter_sets:
        cache: ~
        my_thumb:
            quality: 75
            filters:
                thumbnail: { size: [120, 90], mode: outbound }  
```  
```twig  
{% set runtimeConfig = {"thumbnail": {"size": [50, 50] }} %}
<img src="{{ '/relative/path/to/image.jpg' | imagine_filter('my_thumb', runtimeConfig) }}" /> 
```

```yaml   
# Bolts  
thumbnails:
    default_thumbnail: [ 160, 120 ]  
```  
```twig  
<img src="{{ thumbnail(record.image, 400, 260) }}">  
```  
The difference is in the imagine case only thumbnails of 50x50 and 120x90 are going to be created. not any combination of number. Even with the config option in bolt to allow_upscale as the default of false the possibilities of what bolt can generate for thumbs increases even more because bolt will generate a file in a larger than the original directory but at the original size example: a 800px wide source image upscaled to 1000 will be put in a /thumbs/1000x0 directory but still at 800px. The imagine images are also either served straight from disk, a cdn, s3 bucket, memcached, redis etc.  

an extension author could even abstract this   
```twig  
{% set runtimeConfig = {"thumbnail": {"size": [50, 50] }} %}
<img src="{{ '/relative/path/to/image.jpg' | imagine_filter('my_thumb', runtimeConfig) }}" /> 
``` 
to something closer to or exactly like the current implementation. 
> 
> Other possible problems:
> 
> the designer is allowed to edit templates, but not the config (can this happen with our permissions?)  

This  would be no different that what is currently being shipped. If thumbnail sizes are set in the config or default image size and the designer cannot edit it but can edit the template. Bolt as it is now they can create any combination of thumbnail sizes. Add in imagine and they can still create any size they need. But generation is locked down to those sizes. No list has to be kept. This will also [hash the filename/path](https://github.com/liip/LiipImagineBundle/blob/master/Resources/config/routing.xml#L8) like you're talking about.  

I bring all this up because its a solution to all these problems that is already built, is a symfony component and goes a long way to making bolt more extensible by standing on symfonys shoulders instead of custom one off bolt code and it keeps you all from having to build something and sink time into this instead of other features you want or need. You all already do a lot of work.  

If this isn't really  something you all want, or feel is to much for bolt.. no worries.. I'll try to find some time and tinker maybe make an extension :smile:

**Comment by GawainLynch** [comment]
> The imagine images are also either served straight from disk, a cdn, s3 bucket, memcached, redis etc.

Bolt Thumbs (master) has been rebuilt to integrate with Bolt Filesystem to allow for this already.

That's not to say this is a bad idea, but I would be keen to get @CarsonF to comment as he spend a couple of months on rewriting Thumbs and knows it far better than I do right now.

**Comment by CarsonF** [comment]
I did spend a lot of time writing this implementation of thumbnail code. However, I do believe the less custom code we have the better. 

I would be all for using the Imagine library. Unfortunately, it requires a local filesystem to load the image files, where as ours uses `FilesystemInterface`. See [here](https://github.com/avalanche123/Imagine/blob/develop/lib/Imagine/Gd/Imagine.php#L87) - this class is `final` BTW. That is the deal breaker for me. I would love to see an adjustment made to that library to make this possible though; perhaps a `LoaderInterface` that's similar to Twig's.

@cdowdy I have not seen where s3 buckets, etc. can be used, although I imagine (hehe) that is just a caching layer and still needs local filesystem.

**Comment by cdowdy** [comment]
@CarsonF you're looking at the "base" imagine package. When I was talking s3 buckets etc I was referering too [liip imagine - github](https://github.com/liip/LiipImagineBundle) - [symfony page on cache resolvers like s3](http://symfony.com/doc/master/bundles/LiipImagineBundle/cache-resolvers.html).  

Liip Imagine also has separate data loaders. Specifically [Flysystem](http://symfony.com/doc/master/bundles/LiipImagineBundle/data-loader/flysystem.html). That might not be what you're talking about though haha

**Comment by CarsonF** [comment]
Hmm I do see the binary stuff from the imagine bundle. Trying to figure out how that plays into the core imagine library....seems like it should be there instead of in the bundle. I would really rather not use the bundle as it requires `symfony/framework-bundle` which pulls in a lot more stuff. I don't think @bobdenotter would approve of that.

**Comment by GawainLynch** [comment]
> I would really rather not use the bundle as it requires symfony/framework-bundle which pulls in a lot more stuff. I don't think @bobdenotter would approve of that.

Me either.

**Comment by cdowdy** [comment]
> I would really rather not use the bundle as it requires symfony/framework-bundle

yeah completely skipped over that my fault haha.... yeah thats no bueno. I see someone asked once before about decoupling it from the [framework bundle](https://github.com/liip/LiipImagineBundle/issues/643)

**Comment by rarila** [comment]
@cdowdy It’s late already and my head may be a bit of a :jack_o_lantern: but I don’t get how ``runtimeConfig`` is supposed to restrict allowed sizes, as it is defined inside a template that is not read when the image request hits the server.

**Comment by GDmac** [comment]
Please note that if the whitelist fail returns an error image instead of simple 403/404 to 
NOT generate the error image in the requested dimension (infinite generate error image dimensions)

**Comment by cdowdy** [comment]
@rarila the runtime config is singed. See the Cache and Cache manger of Liip -> https://github.com/liip/LiipImagineBundle/tree/master/Imagine/Cache so whichever sizes are defined in the template are the only sizes allowed to be generated with a runtime config.

**Comment by ToBe998** [comment]
Any news on this? Cant find any RFC ticket for Bolt/Thumbs 3 and the 2.x ticket has been closed.

**Comment by SahAssar** [comment]
@ToBe998 Well, this is basically the place to discuss it (as opposed to an RFC in bolt/thumbs). AFAIK noone has started any serious work on it, but its one of those things that we want to get done sooner or later but that none has taken on in a real way.

**Comment by ToBe998** [comment]
Ok, i'll just add my 2cents to it then. And maybe i can find some time to do a PR somwhere...

In my oppinion, a simple solution is best here. We already have our own bolt package and adding many other symfony packages just for a simple filter is way to much cost for it.

So i would add some config maybe inside config.yml, maybe in it's own config file. You could then optionally **disable** the currently free resoultions and use a alias name instead. This would result in URLs similar to the current ones just with a alias instead of the free form resolution: `/thumbs/mylargeimage/picture.jpg`. The thumbs generator would work exactly as before, just get the config from the alias in the config and not the url. So everything else stays same. We still can check cache by a simple file access and we would not have to reimpement anything.

We also need the filter insinde the templates to work with aliases though, or use a different filter:
`{{thumbnaul( '/files/picture.jpg', 'mylargeimage' )}}`

**Comment by bobdenotter** [comment]
@ToBe998 Sounds like an excellent approach to me.

**Comment by Boorj** [comment]
+1 to that solution, but i also suggest use not only "c" or "r" aliases, but also support user-friendly names stretch, fit, fill, resize, crop.. as i mentioned in the first post.  
Also, using watermarking and some image processing would be cool.

**Comment by SahAssar** [comment]
@Boorj Watermarking and so on (other more advanced image processing) seems more like extension territory to me.

**Comment by Boorj** [comment]
I agree, we're keeping the core neat. Will extensions be able to access those settings?

**Comment by SahAssar** [comment]
@Boorj Well, I guess that depends on how it's written... But IIRC in Bolt 3.2 it should be possible (but I don't know for sure at all).

**Comment by ToBe998** [comment]
https://github.com/bolt/bolt-thumbs/pull/29

**Comment by ToBe998** [comment]
Bolt PR for this is here to now.

**Comment by Maelstromeous** [comment]
Isn't this now fixed with the thumbs aliasing?

**Comment by GDmac** [comment]
Looks like almost. I think wildcards need to be addressed, as mentioned above.
like `[400,0]` or more readable `[400,auto]`.

This uses the (currently not documented) thumbs autoscale feature.
https://bolt.cm/thumbs/200x0r/2014-12/featureimg_rsponsive.png
https://bolt.cm/thumbs/400x0r/2014-12/featureimg_rsponsive.png
https://bolt.cm/thumbs/600x0r/2014-12/featureimg_rsponsive.png

**Comment by bobdenotter** [comment]
Because of "Spring cleaning", we're going to close this issue. Unless somebody steps up to help out with implementing it, it's not expected that the core team will have the opportunity to work on this soon. Keeping it open might set false expectations for people stumbling upon this issue.

This is not because we don't see this feature as potentially worthwhile, it is more to do with an overload of potential new features that could be developed combined with non-limitless amounts of available time and resources. 

If you disagree, feel free to re-open for discussion.
