### ISSUE TITLE
[INTERNALS] Guide to refactoring using the new Storage system

### ISSUE THREAD

**Issue by rossriley** [bolt/bolt#3720]
Just a brief guide to assist anyone who wants to get involved in the storage refactor.

## Step 1.
The guiding principle is that each table within Bolt will have a repository class that is responsible for all reads and writes to that table, so bolt_cron will have a corresponding Repository at `Bolt\Storage\Repository\CronRepository` 

The repositories are mapped to an Entity, and entity is a Plain PHP object that extends `Bolt\Storage\Entity\Entity` in its simplest form the CronRepository class either takes an array of Entity\Cron objects and saves them to the db, or inversely fetches some rows of bolt_cron data from the database and converts them to Entity\Cron objects.

## Step 2. 
To fetch data from the db, the Repository classes use Doctrine QueryBuilder objects to make a query. For info on how to use this see here (http://doctrine-dbal.readthedocs.org/en/latest/reference/query-builder.html) 

So our job is to make sure that any code throughout Bolt that queries the database, is moved out of the various places you find it now, and move it into the correct repository class. If the query is written currently using raw sql then it needs to be converted to a QueryBuilder query.

## Step 3. 
It may also be good practice to separate the query build and the query execute methods. Firstly this allows us to test that the queries are correctly composed, secondly it also allows users to slightly modify or extend an existing query. For example here's a simple one from the CronRepository.

```
    public function getNextRunTimes($interimName)
    {
        $query = $this->queryNextRunTimes($interimName);
        return $this->findOneWith($query);
    }
    
    public function queryNextRunTimes($interimName)
    {
        $oldname = strtolower(str_replace('cron.', '', $interimName));
        $qb = $this->createQueryBuilder();
        $qb->select('id, lastrun, interim')
            ->where('(interim = :interim OR interim = :oldname)')
            ->orderBy('lastrun', 'DESC')
            ->setParameter('interim', $interimName)
            ->setParameter('oldname', $oldname);
        return $qb;
    }
```
You'll see the bulk of the work is done in the `queryNextRunTimes` and the `getNextRunTimes` just executes the query. This would allow an extending repository to tweak the query, or if you want to just grab the query and use it elsewhere without accessing it you can.

**Comment by GawainLynch** [comment]
I was just chatting to the :koala: while he was eating some :leaves:  and we came up with a few questions/problems:

* `CronRepository::createQueryBuilder()` is it needed to replace the parent classes one?

* `$repo = $this->app['storage']->getRepository('cron');` errors with "Attempted to load mapping data for unmapped class cron" and need to use the full class name

* `$repo = $this->app['storage']->getRepository('Bolt\Storage\Entity\Cron'); `returns a `Bolt\Storage\Repository` instead of `Bolt\Storage\Repository\CronRepository`  
Ergo, should EntityManager:;getRepository() return the actual extended class, not the parent? Currently:
```php
return new Repository($this, $classMetadata);
```
* Should CronRepository::queryNextRunTimes() be protected?

* Can Bolt\Storage\Entity\Entity::__call() sanity check the function's that are being called and error if they don't? The :koala: accidentally tripped over this one and couldn't figure out why a method wasn't being called elsewhere… I tired to warn him too, those were gum leaves, right? :wink:

**Comment by rossriley** [comment]
Whoops, I blame the :koala: 

StorageServiceProvider, has the old namespace for the mapping, should be:
`  'Bolt\Storage\Entity\Cron' => 'Bolt\Storage\Repository\CronRepository'

Then: `$repo = $this->app['storage']->getRepository('Bolt\Storage\Entity\Cron');` should return the correct repo.

**Comment by rossriley** [comment]
My personal preference is to have the repository methods all public, since this allows users to re-use them in their own apps / extensions. We could feasibly leave them protected during this phase and open them up when ready for public api later.

**Comment by GawainLynch** [comment]
> My personal preference is to have the repository methods all public

Nope all good here, just applying sanity checks. The reasoning makes sense.
