### ISSUE TITLE
Allow previewing of content types with viewless: true

### ISSUE THREAD

**Issue by Pinpickle** [bolt/bolt#3726]
If a content type is viewless, it is not necessarily not displayed on the site in some form of collection. For example, an authors content type may be listed on an authors page, without a specific page for every author.

For this reason, it may be good to have a preview page for these content types individually, as they would appear on the website. Using the authors example, this may be a nice thumbnail with their bio and name next to the image.

This would then allow the live editor to be used for these records as well, which may be appropriate. It certainly is for the authors example. So I'm proposing there should be three different properties around how we can view, preview and live edit records:

- `viewless`: If set to true, records on the site won't have routes automatically generated for them, nor will there be a listing page automatically generated. Default is false
- `preview`: If it is true, you will be able to click on the preview button in the record editor. Default is the boolean not of `viewless`.
- `liveeditor`: If it is true, you will be able to enter the live editor for records of this content type. Default is the same value as `preview`. It cannot be true if `preview` is false as the live editor relies on records' previews.

**Note:** I am not suggesting a preview for the listing. While that would be nice, it's a bigger undertaking than this.

**Comment by SahAssar** [comment]
Currently (especially after #4653 (thanks for that solution!)) viewless means that when a record is viewless it is never the "entrypoint" for a rendercall or a route, but can still have all the properties of a view record. While I hope for a more robust solution to the route/searchable/viewless problem I'm going to close this one since it hasn't had any activity for about six months.

If anyone comes up with a good solution for the routing/searchable/editable/live-editable matrix I'd love to see it, or if I'm wrong about this issue please feel free to reopen! :)
