### ISSUE TITLE
Undefined class upon creation custom field

### ISSUE THREAD

**Issue by jkaan** [bolt/bolt#3773]
I've tried to create my own custom field according to [this](https://docs.bolt.cm/extensions/customfields) tutorial: 

However I keep getting the error that the class that represents the field cannot be found.

I have cloned the example project from [this](https://github.com/rossriley/bolt-extension-colourpicker) repo on GitHub but I still get the error that the ColourPickField cannot be found

**Comment by jkaan** [comment]
I've found that whenever I include the file using `include_once` then it does work.

For some reason the autoloading of files other than Extension.php/init.php by using PSR-4 doesn't work.

This is the autoloading section of my composer.json:

    "autoload": {
        "files": [
            "init.php"
        ],
        "psr-4": {
            "Bolt\\Extension\\TimOnline\\NvjmTicketsGateway": ["", "src/"]
        }
    }

**Comment by GawainLynch** [comment]
What version of Bolt?

**Comment by jkaan** [comment]
Bolt 2.2.4

**Comment by SahAssar** [comment]
@jkaan The colorpicker seems to have been broken for a while (it's been on my list of things to PR), but if you look at either raistlfiren/faiconfieldtype or sahassar/bootstrapcolorpicker (which should both work).

Closing the issue since I'm guessing that this is no longer an issue for you. Feel free to reopen if you didn't/haven't gotten it to work.
