### ISSUE TITLE
[RFC] - Audio Content Type

### ISSUE THREAD

**Issue by mhodges-cainc** [bolt/bolt#3779]
The primary objective would be to allow users to create audio file content types.

Team currently plans on building it out as an extension.

**Comment by evanestal** [comment]
Would be ideal to also allow for limits on upload size or format.

**Comment by GawainLynch** [comment]
Format is covered by file extension, currently, but could potentially be expanded.

**Comment by rossriley** [comment]
here's how to add limits to size:

https://gist.github.com/rossriley/bb16ea1b7933292a12a4

**Comment by GawainLynch** [comment]
@rossriley we should probably think about putting some of these things into a section of the documentation for advanced configuration.

**Comment by rossriley** [comment]
Yes, it's almost like an FAQ / How to Solve XX

I've started knocking up gists whenever we get asked on IRC so I've got a few to get us started.

There's another philosophical question about where to store these configurations. I'm personally of the opinion that it's best practice to write your own providers on a per-app basis that do things like this, rather than adding more and more options to the config.yml / contenttypes.yml files.

Others may feel differently though and prefer to keep everything in config.

**Comment by SahAssar** [comment]
Closing as this is also open in #4520 but that issue is also going (hopefully) have some info about the CA implementation of this.

**Comment by SahAssar** [comment]
Sorry @mhodges-cainc, did not know/remember that you are with CA so this must have come out a bit weird :D

**Comment by mhodges-cainc** [comment]
Haha - no problem at all! Our release cycle is calming, so we're starting to prep our first contributions back - the team is really excited.
