### ISSUE TITLE
how to move vendors

### ISSUE THREAD

**Issue by poznet** [bolt/bolt#3797]
Hello
maybe it's  stange question -  I'm using vagrant  for  development.   
To speed it up (in the easiest way)  i need to  move  vendor folder  somwhere outside bold  

How  to change  bootstrap.php   to  give bold  new location of  vendor  folder  (absolute path ) ?

As  far  ... i can tell, that  change in  $autodetectionMappings  won't   do the  thing

**Comment by rossriley** [comment]
I'm not 100% sure since I haven't tested a vendor path move, but most things in Bolt are figured out in automatically based on where the files are.

What I'd recommend is that you write your own bootstrap file, using the instructions here as a starter: https://docs.bolt.cm/installation-advanced#installing-bolt-composer-package

Starting Bolt with the `Composer` configuration object should take care of most of the path setup.
