### ISSUE TITLE
Potential BC/Functionality Break in Uploads

### ISSUE THREAD

**Issue by rossriley** [bolt/bolt#3831]
Pinging @GawainLynch and @CarsonF 

In the move around of the controllers I just noticed that the previous services for both `$app['upload']` and `$app['upload.container']` have been moved inside a Pimple `$app->share()` declaration.

see: https://github.com/bolt/bolt/blob/release/2.2/src/Controllers/Upload.php#L25
vs: https://github.com/bolt/bolt/blob/master/src/Provider/UploadServiceProvider.php#L21

I've not got a test case handy, but I'm pretty sure that this will disallow a lot of runtime modification, for example (when we get around to making it) modification of the upload prefix based on contenttype setting... `upload: uploads/%contentype%`` for instance.

**Comment by GawainLynch** [comment]
Forward looking, I don't think this is a problem as we can create other pimples in that provider that can host "stuff" as required… we're doing this pretty heavily with the upcoming session work… /me nudges @CarsonF 

As for BC breaks, I'm not clear on where the problem lies but I would prefer that — once identified — we don't make BC breaks with this component, unless we really need to… Carson might have more ideas.

**Comment by rossriley** [comment]
Here's another example of what I mean.

https://github.com/bolt/bolt/blob/master/src/Controller/Backend/FileManager.php#L326

Under the previous behaviour we supported things like multiple upload namespaces: eg: `upload: [files://uploads, s3://bucket]` 

I'm pretty sure that when we use `$app->share()` then it's a once only object creation, so we're always fixed to the namespace as of first object creations.

**Comment by GawainLynch** [comment]
Switching certain parts to an `$app->protect()` might be workable in that case.

**Comment by SahAssar** [comment]
Updates? (asking since I'm going for "pain in the ass" today)

**Comment by GawainLynch** [comment]
Fixed in #4835
