### ISSUE TITLE
Is php_fileinfo necessary?

### ISSUE THREAD

**Issue by mat02** [bolt/bolt#3834]
Hi!
I've downloaded and configure Bolt on my www hosting server, but the php version that is available doesn't have php_fileinfo extension. I've contacted administrator, but they said that they won't enable it in any foreseeable future.
Is there any possibility to use Bolt thumbnails without php_fileinfo?
Best regards
Mateusz

**Comment by rossriley** [comment]
From a quick check it looks as though our filesystem package, Flysystem, has fileinfo marked as a dependency. 

If you want to try without the package and are getting the error only on composer install then you can try ignoring it by using `composer install --ignore-platform-reqs` when you install Bolt.

**Comment by mat02** [comment]
Hi Ross,
As I don't have access to CLI on that server, I didn't use Composer to install Bolt.
I believe fileinfo is used by image uploader to recognize file's mimetype before creating image thumbnail, because I get "Unable to guess the mime type as no guessers are available (Did you enable the php_fileinfo extension?)" when I try to access image thumbnail (although, full image is propely uploaded to server).

**Comment by rossriley** [comment]
Ok. I see now, I'm guessing that you also have shell commands disabled on your server because there is supposed to be a fallback guesser too if fileinfo is unavailable.

If your host will let you enable some shell commands then if they will enable `passthru` and `escapeshellarg` then the fallback Mime Guesser will work for you.

If not, then you can still get it to work, but you'll need to take over responsibility for providing a file's mime type. You'd need to do two things.

1. Make a class that implements `MimeTypeGuesserInterface` this would be a class with one method, something like this:
   
    <?php
    use Symfony\Component\HttpFoundation\File\MimeType\MimeTypeGuesserInterface;

    class MyMimeGuesser implements MimeTypeGuesserInterface
    {
        public function guess($path)
        {
            ...... return mime type for path
        }

    }

Then you need to add your class to the guessers probably somewhere in your initialisation script.

    use Symfony\Component\HttpFoundation\File\MimeType\MimeTypeGuesser;

    $guesser = MimeTypeGuesser::getInstance();
    $guesser->register(new MyMimeGuesser());

How indepth you make your mime type guesser is up to you. If you only want to support images them `getimagesize()` returns the mime as one of the parameters.

**Comment by mat02** [comment]
Ok, thanks for info.
I'll try that and report back asap.

**Comment by mat02** [comment]
Hi again,
I've implemented basic mimetype guesser and now it works great :)
Thank you! I think that solves the problem.

**Comment by vgibara** [comment]
Can you help me with which files you updated or added and where to implement this mimetype guesser ? I'm having the same problem with my web host...

Thanks !

Vince

**Comment by mat02** [comment]
Hi Vince,
Bottom of my index.php looks like this:
`
require_once __DIR__ . '/vendor/MyMimeTypeGuesser.php';
use Symfony\Component\HttpFoundation\File\MimeType\MimeTypeGuesser;

$guesser = MimeTypeGuesser::getInstance();
$guesser->register(new MyMimeTypeGuesser());

if ($app) {
    $app->run();
} else {
    return false;
}
`
then in 'vendor' folder I've created file named MyMimeTypeGuesser.php with this content:
`<?php
use Symfony\Component\HttpFoundation\File\MimeType\MimeTypeGuesserInterface;

class MyMimeTypeGuesser implements MimeTypeGuesserInterface
{
public function guess($path)
{
	$data = getimagesize($path);
	return isset($data['mime']) ? $data['mime'] : null;
}

}

?>`
