### ISSUE TITLE
live edit related content data-bolt-field

### ISSUE THREAD

**Issue by sitobcn82** [bolt/bolt#3843]
I'm not sure if this is posible but I try to edit a related field in the live edit view and i can't modify the related data.

```
<div class="col-xs-12" data-bolt-field="record.relation.items.0.title">{{ record.relation.items.0.title}}</div>
```

The data appears but i can't edit this data

**Comment by Pinpickle** [comment]
Currently this isn't possible because the data isn't stored inside the current record (it's stored in a related one). The live editor, at the moment, is effectively just a different "face" for the ordinary editor (it doesn't handle any saving, just filling fields in the ordinary editor).

Saving data to other records may come later, it would be nice for listings, and this use case you just brought up, but it does open a big can of worms. It also de-CMSes Bolt somewhat which I know @bobdenotter doesn't like.

A somewhat less impressive solution may be to add an edit link to the related record:

```twig
{% if related.editlink() %}
    <a href="{{ related.editlink() }}" target="_blank">Edit</a></p>
{% endif %}
```

**Comment by SahAssar** [comment]
Closing this one as it seems out of the scope of bolt currently (and possibly indefinitely). If you like this idea the forums would be a good place for a discussion, or if you disagree that it is out of scope please feel free to reopen! :)
