### ISSUE TITLE
Confirm if saving in editcontent by enter

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#3942]
Maybe attach onSubmit listener to the form and show confirmation modal window if you save by keyboard (enter)? Sometimes people can accidently save unwanted data.

**Comment by Boorj** [comment]
Seems i'll have to do it by myself. Solution is to add a field in config.yml (off by default, as @bobdenotter told) that allows to add modal window if you're press enter while focused on input or textarea in form on contentedit page.

**Comment by bobdenotter** [comment]
Because of "Spring cleaning", we're going to close this issue. Unless somebody steps up to help out with implementing it, it's not expected that the core team will have the opportunity to work on this soon. Keeping it open might set false expectations for people stumbling upon this issue.

This is not because we don't see this feature as potentially worthwhile, it is more to do with an overload of potential new features that could be developed combined with non-limitless amounts of available time and resources. 

If you disagree, feel free to re-open for discussion.
