### ISSUE TITLE
Routing for Single Page Applications

### ISSUE THREAD

**Issue by jewe** [bolt/bolt#3989]
Please provide a possibility to use # or ? in the route path.
Currently if i config a route with 
```
path: '/#/{contenttypeslug}/{slug}'
```
the /#/ will be replaced by
```
/%23/
```
I would like to setup bolt as backend and a single page application as frontend connected through json.

**Comment by bobdenotter** [comment]
Hi, 

Paths that start with a `#` are links to internal anchors, and are handled in the browser. You cannot use them in URL's, so Bolt is right to escape them. 
The fact that they do something in your front-end app is due to the fact that it's handled by Angular or React, and it delegates it to a controller in the front-end app. 

That said, what you're looking for is probably this extension: [JSON API](http://extensions.bolt.cm/view/5f66c2bf-0eb1-11e5-9120-621e70d6e3eb). Use Angular/React/Ionic/[Foundation for Apps](http://foundation.zurb.com/apps/) or whatever to build the front-end app. In the controllers you create there, fetch the JSON from Bolt and display it in the browser. 

Using this you can even completely detach the front- and backend of your site: Put Bolt somewhere, and your frontend somewhere else.

**Comment by jewe** [comment]
Hi,
i don't understand the benefits of escaping the ```#```. My frontend application works already fine with the json api. I changed the ```.htaccess``` and integrated the SPA in bolt. Now it would be nice to have working links from the backend to the frontend. 
I think building websites as SPA is an important topic for the future - so it would be nice to have a possibility for an elegant integration.

**Comment by bobdenotter** [comment]
Because you're not allowed to use `#` in URLs. From the official spec at http://www.w3.org/Addressing/URL/uri-spec.html

```
Hash for Fragment Identifiers

The hash ("#", ASCII 23 hex) character is reserved as a delimiter to separate the URI of an object from a fragment identifier .
```

So, in short: Bolt escapes it, because you're not allowed to use them.

**Comment by jewe** [comment]
I just described a use case to implement the ```#``` as a Fragment Identifier (as indented) in a route for an SPA and emphasised because this could be important for some future bolt frontends.
Most SPA frameworks have different routing options (```#```, ```?``` etc) and of course also the possibility to use a route like ```http://server/path/to/page```, but it is quite difficult to integrate this routing into bolt because you need rules to separate frontend and backend.

**Comment by bobdenotter** [comment]
I'm sorry, but you've lost me there. What exactly is it that you want we change?

**Comment by jewe** [comment]
Just don't escape ```#``` and ```?``` in routes. So users who use a single page application as frontend can integrate it into bolt, because it is possible to link from the backend to the frontend.
You are right - it is not 'wrong' escape these chars to prevent a misconfiguration, but this is not an important benefit compared to the described new possibilities.

**Comment by bobdenotter** [comment]
Sorry, but I'm still lost.. How can we not escape these? _Where_ should we not escape these? How would this change manifest itself in Bolt? How would you see a URL like `example.org/#!/page/about` ever hitting the Bolt backend if your browser sees it as a local anchor?

**Comment by jewe** [comment]
If i write in ```routing.yml```:
```
...
contentlink:
   path: '/#/{contenttypeslug}/{slug}'
```
and i go to the backend into a page and click "View on site" the link targets to e.g.
```
http://host/%23/page/about
```
Just don't escape the ```#```.
I have a working bolt installation where i changed the ```.htaccess``` to redirect all urls with ```#``` to index.html instead of index.php and everything else works perfect.

**Comment by Pinpickle** [comment]
I'm developing a single page website myself, and I've got around this hash business by using the History API.

However, if you must use hashes...

The problem with using hashes in routes is that the `#` character and anything after it *is not sent to the server*. So if your routing explicitly requires a *non-escaped* `#` character, that route can never be fulfilled. Where your problem lies is not with the routing but the link generation - and you can override this with a custom `link` function with a [custom content object](https://docs.bolt.cm/extensions/essentials).

```php
class JSONContent extends Content {
    public function link() {
        return '#' . $this->slug; // or however you want to do link generation.
    }
}
```

[Look at how links are currently generated](https://github.com/bolt/bolt/blob/master/src/Content.php#L1095-L1132) to best do this
