### ISSUE TITLE
Screenshots are not working on Bolt extension backend

### ISSUE THREAD

**Issue by Mikescops** [bolt/bolt#3997]
There is an issue in the url, fix needed !

![image](https://cloud.githubusercontent.com/assets/4266283/9380339/f356632c-472f-11e5-8ca3-a9783e39fc7e.png)

**Comment by GawainLynch** [comment]
@bobdenotter I am not sure we can/should fix this… Parsedown just assumes that the image file location is relative to the markdown file, and Parse down offers no was to set a base URL.

The only thing we could do would be to search for `src="` and hackishly replace… but that makes my skin crawl. 

Would be better to have devs use an absolute URL to the image in the repository for this.

**Comment by SahAssar** [comment]
Going to close this one as there really does not seem to be a good way to "solve it". Getting the extension author to use absolute URL's really seems to be the best way, as @GawainLynch said.

If you feel that this is something that really should be fixed in bolt core or if you come up with a good solution please feel free to reopen :)
