### ISSUE TITLE
SVG's still processed by bolt-thumbs (was: "SVG upload results in error")

### ISSUE THREAD

**Issue by melcarthus** [bolt/bolt#4090]
I'm trying to get SVG to upload properly but have failed in every attempt. I have made test svg's to eliminate the possibility that it's the designers fault, which does not seem to be the case.

Everythime I upload an svg bolt gives me an error thumbnail in return. I have uploaded one of the files that fails in uploading ( they all fail to upload correctly ) directly to the ftp server and hardcoded the img tag into the code and the svg shows without a problem. What could be the cause of this?

I'm using version 2.2.10

I have found another issue which explains averything, thumbnail generating breaks, and is also explained.. #720

**Comment by SahAssar** [comment]
Does the SVG actually fail to upload or does it upload correctly but the thumbnail and image functions fail to generate a working resized image? Because the second scenario is expected, but the first is not.

I just tried this on 2.2.10, and I can upload an SVG to an image field correctly, and as long as I use `<img src="/files/{{record.image}}">` instead of the thumbnail functions it shows correctly.

Of course the thumbnail handler should handle SVG's correctly (pass them through without touching them), but I'm trying to see if this is the same issue as #720.

**Comment by melcarthus** [comment]
Whoops this still open ... my bad. It's the thumbnail issue, SVG's are working fine when using img src. They only display incorrectly in the bolt backend.

**Comment by SahAssar** [comment]
Opened an issue in bolt/bolt-thumbs/issues/22 since that seems like the place where we would solve this. I'll try to get a fix in soon.

**Comment by SahAssar** [comment]
I'm going to close this one since it's open in bolt/bolt-thumbs#22 and I think it only needs one open issue in the org.
