### ISSUE TITLE
Stored XSS - Homepage

### ISSUE THREAD

**Issue by joelvadodil** [bolt/bolt#4119]
Hi Team,

Bolt CMS is vulnerable to stored XSS, the "sitename" parameter is vulnerable to stored CMS. sitename parameter is present in config.yml file.

![xss](https://cloud.githubusercontent.com/assets/12528123/9979702/c276c182-5f96-11e5-9d34-01da98f80f3a.jpg)

Please confirm the same and close this security issue.

Thanks,
Joel

**Comment by bobdenotter** [comment]
Hi, 

Thanks for bringing this to our attention, but we do not consider this an issues that needs fixing. Nothing in `config.yml` is being filtered, because it's only tobe edited by people you trust. In fact, if somebody would be able to make changes to your `config.yml`, the entire site would be compromised: Database, access and all. 

`Config.yml` is on the same level as the template files in this regard. If you add 'xss code' in your template, it'll get executed in the browser as well. And that's the expected behaviour. 

And,slightly besides the point: You're getting a fatal error in the YAML parser, which is subsequently not filtered out in Xdebug, which causes the alert. I don't think this happens in the Bolt code, right?
