### ISSUE TITLE
Feature request: Comment field (just a css style or more)

### ISSUE THREAD

**Issue by evertalbers** [bolt/bolt#4121]
I sometimes use a textarea-field for internal communication between editors in the backend (e.g. "This is the text that shows up in the footer" in a resource contenttype record). 

It would be handy to have a pre-cooked style that you can apply in contenttypes.yml to this field to make it stand out as a comment field, e.g. 
``class: comment``
 giving it a 3M-ish-yellow background in the backend.

_(If you would want to take it one step further for teams, you could let a javascript automatically prepend something like "On 7 sept 2015, 10:15, Evert Albers wrote:..." 
everytime someone starts typing something new - but for my purposes, just a style would be enough.)_

**Comment by SahAssar** [comment]
To me this feels like it would fit an extension better, but that might just be me :)

An extension would probably have an easier time adding the "steps further" too.

**Comment by rarila** [comment]
Hmm, ``class: comment`` would afaik already work. Problem is adding user defined defined styling. (Just a line css inside the core of course)

Question is, is that useful for the masses to justify add that to the core or just a special case?

**Comment by SahAssar** [comment]
@rarila Well adding CSS for a specific styling would solve the basic use case, but if this is actually supposed to be a comment field and not just a temporary dump of text then it does not solve much since that would require more functionality.

I'm not against adding CSS, but if the plan/want is to actually make the field more fully fledged anyway then it seems like (in my mind) it might fit an extension better.

**Comment by SahAssar** [comment]
Going to close this as this feels like an extension could do it better than we could in core.

If this feels like something that you think should be in bolt core please feel free to reopen :)
