### ISSUE TITLE
When adding a contenttype selectfield a LONGTEXT field gets created in the database?

### ISSUE THREAD

**Issue by phpetra** [bolt/bolt#4122]
When adding a select field to a related contenttype a LONGTEXT database field (MySQL) is created.
I was expecting an INT (11) field.
Is this a bug or a feature?

Steps:
Create a select field in one contenttype to store the ids of a related entity:
Example contenttype of member:
```
teamselectfield:
    type: select
    sort: name
    values: teams/name
```

In the members table a LONGTEXT field gets created... why on earth?
It does store the id value correctly, but I would assume having an INT(11) field would be better?

If it is there because it *could* hold other field values: for instance when the keys: option was set in the field definition, [as explained here](https://docs.bolt.cm/howto/select-field-type#populating-list-contenttype) , shouldn't it then be conditional? And only set to LONGTEXT when the keys option is really set.
This could be a real performance issue for larger tables.

**Comment by GawainLynch** [comment]
OK… so this is the[ current field definition in the stable branch](https://github.com/bolt/bolt/blob/release/2.2/src/Database/IntegrityChecker.php#L629), and yes it is defined as `TEXT` for MySQL.

Short answer is that it is most certainly not an integer. Its values can be, and often are, associative array keys, e.g.:
```
values: { 'yes': "Yes", 'no': "No", 'undecided': "Well, it can go either way" }
```
In MySQL the `TEXT` type is chosen based on [column length](http://doctrine-dbal.readthedocs.org/en/latest/reference/types.html). Personally speaking, I strongly suggest that you use PostgreSQL if you have real performance concerns.

**Comment by phpetra** [comment]
Hi Gawain, thanks for the quick answer.

If the field type is that generic (meaning it could hold all sort of date) wouldnt it maybe make more sens to create a separate field type for the field that only needs to hold ids from a related table?
Because atm I cannot create an index or a foreign key for this db-field.

If I for instance would like to have a proper foreign key on this field I won't be able to create one (because the types INT -> TEXT are not the same). And creating a FK with TEXT or BLOB types this is not possible (depending on the MySQL engine)
Postgress is even stricter.

**Comment by phpetra** [comment]
Another thought: Changing the current setting to VARCHAR(255) would help with being able to crate the index for the field, but not with the FK.

**Comment by GawainLynch** [comment]
Just to follow up with the conversation on IRC here. There is a valid use-case here, however the larger problem is that there are backward compatibility issues here.

That said, I haven't tested doing this, but in 2.3 all of the contenttype tables are DI objects and can be extended, so that you potentially could do this with an extension once 2.3 is released… and I have had time to write documentation :grin:

**Comment by SahAssar** [comment]
Info for anyone that comes along: The version roadmap has changed, and since this issue mentions v2.3 (which is now 3.0) I'm posting this here https://discuss.bolt.cm/d/112-bolt-version-roadmap-changes/7

**Comment by SahAssar** [comment]
As also discussed in #4632 in 3.0 it will be possible to modify the DB structure/queries. In 2.2 that is not possible however, and will not be. I'm closing this one, but I am looking forward to seeing testing of the DI contenttype tables and the (hopefully few) bug reports that will come from it :)

Please feel free to reopen if you feel the issue was not answered adequately (and sorry if you do!).

**Comment by phpetra** [comment]
@SahAssar That's allright. And those new abilities to change things looks awesome. Want!
