### ISSUE TITLE
Add documentation for customizing twig syntax in favor of using angular.js

### ISSUE THREAD

**Issue by melcarthus** [bolt/bolt#4159]
For a project I want tot test ``material-angular`` with bolt. But for this I need to change the ``twig`` syntax so there is no conflict with angular. I need to make my own ``delimiters`` and therefor I need to make my own ``lexer`` object ( is this correct ? ) 

Any help would be appreciated. For update sake I don't want the break the customization everytime I update bolt.

Regards,

Tim

**Comment by dennschu** [comment]
@melcarthus Did you know the [`{% verbatim %}`](http://twig.sensiolabs.org/doc/tags/verbatim.html) tag of twig where you can mark template sections that should not be interpreted by twig. I had the same issue like you with [vue.js](http://vuejs.org) mustache templates that use `{{ }}` for echoing out variables which collide with twig. I solved this in case of vue.js templates in two ways without the usage of `verbatim` because its exessive usage produces for humans unreadable twig templates.

- solution 1: change the delimiter of angular (if possible), but then you loose syntax completion of your ide
- solution 2: seperate angular and twig templates.

After fiddling around with solution 1, i went the solution 2 route because custom delimiters can be a also a big pain...

**Comment by rarila** [comment]
I do know nothing about Anglar, just did a 5 minute research to see where's the problem.

So, would it be possible to use ``ng-bind`` instead of ``{{ var }}``?

**Comment by melcarthus** [comment]
Hmm, solution 2 from @dennschu looks doable, and using ng-bind I have to dig in to this myself a little but. None the less I got two great starting points :) :+1:

**Comment by rarila** [comment]
@melcarthus Another possible (hacky) solution (I don't know if you need IDE support for Angular) would be an angular macro that simply outputs its parameter with brackets before and after and gets called like ``{{ angular('var.name') }}`` … but I think I personally would prefer the ``ng-bind`` solution as it seems much more clean.

**Comment by bobdenotter** [comment]
@melcarthus another option could be to make the site "headless". Just do your angular and static files however you want to do them, and pull in the content from a Bolt installation using the JSON API extension. That way the angular stuff is seperate from Bolt, so it doesn't get messed up. 

We used this method to create this: http://itgwo.nl/#!/ using foundation.zurb.com/apps/

**Comment by SahAssar** [comment]
@bobdenotter is this something that we want to work into bolt or just something that we just want to document as a howto in the docs/forums? I vote for the latter.

**Comment by melcarthus** [comment]
@bobdenotter would love it more if it is documented, so I actually learn something. I don't need a ``htaccess`` out of the box imho.

**Comment by SahAssar** [comment]
Alright, I edited the title and changed the label to make this more actionable.

**Comment by SahAssar** [comment]
Opened issue in docs here instead: bolt/docs/issues/263
