### ISSUE TITLE
Twig dump() does not output the current context.

### ISSUE THREAD

**Issue by codesman** [bolt/bolt#4170]
Tested on Bolt 2.2.11, Chrome 45.0.2454.101, OSX 10.10.3, Nginx 1.8.0, PHP 5.6.13_3, Xdebug v2.3.3, MariaDB 10.10
## Description:

Calling Twig dump() results in **Warning: Missing argument 1 for Bolt\Twig\TwigExtension::printDump()**. 

http://twig.sensiolabs.org/doc/functions/dump.html says that calling dump() is supposed to return the current context, but it does not.

## To Recreate:

Insert {{ dump() }} into index.twig(or equivalent).  Run the app.  Get the Warning.

## The Issue:

Bolt extends Twig's dump() function with it's own printDump function in [https://github.com/bolt/bolt/blob/master/src/Twig/TwigExtension.php](https://github.com/bolt/bolt/blob/e21f6d8248cd50115034875d071efb5cce72196f/src/Twig/TwigExtension.php#L440)

printDump() requires a single argument, $var but does not return the context when the argument is empty.

**Comment by CarsonF** [comment]
We should replace our dump function with `Symfony\Bridge\Twig\Extension\DumpExtension`

**Comment by bobdenotter** [comment]
@codesman Hi, that's because we've wrapped our own Twig `{{ dump() }}` function around `Var_Dumper`. You could probably get what you want by using `{{ dump(app) }}`. 

@CarsonF Should we? Would that make things clearer / better for the average user?

**Comment by CarsonF** [comment]
@bobdenotter The extension does the same thing our code does, and we don't have to maintain it.

> You could probably get what you want by using {{ dump(app) }}

It's not the same. Twig will give you the context if you ask for it in the function definition. [Check it out](https://github.com/symfony/symfony/blob/2.7/src/Symfony/Bridge/Twig/Extension/DumpExtension.php)

**Comment by codesman** [comment]
Yes, I noticed that app worked.  The reason I reported it is that the Twig docs say that dump() is supposed to return the current context and while the Bolt docs talk about passing an argument to Bolt's dump(), it does not mention that Bolt's implementation of dump() does not support calling without an argument and will not return the current context if called without one.

**Comment by CarsonF** [comment]
^ For this reason, I'm saying it's a bug.

**Comment by codesman** [comment]
Yay, my first bug!

**Comment by bobdenotter** [comment]
As long as {{ dump(record) }} will give the same result, i'm all for getting the implementation more in line with what's in Twig's official docs. :-)

**Comment by bobdenotter** [comment]
Just as a sidenote: When I first implemented `dump`, we didn't have the var_dumper yet, and it really looked like crap. So, that's why I probably did an implementation of my own.

**Comment by CarsonF** [comment]
@bobdenotter Yeah exactly. [Here's](https://github.com/twigphp/Twig/blob/1.x/lib/Twig/Extension/Debug.php) the one built into twig.

Yeah `{{ dump(record) }}` will give the same result, _unless_ **debug** is disabled.

I'm going to tackle this in branch for other twig changes. It's going to be tricky though with "safe_twig".

**Comment by bobdenotter** [comment]
:+1:

**Comment by bobdenotter** [comment]
@CarsonF Looking into that, it seems that one still uses the boring, ugly `var_dump` from PHP, instead of Symfony's shiny [Var_dumper](http://symfony.com/doc/current/components/var_dumper/introduction.html) ? 

Wouldn't it be easier to get them in line a bit more by doing something like this? (in shiny pseudo-code)

```
public function printDump($var)
{

    if (empty($var)) {
        $var = (whatever 'context' is);
    } 
```

**Comment by CarsonF** [comment]
So a few things:
- context could be passed in, but it's more like `printDump($context, $var)` and then we would have to some conditional logic (`func_num_args()` would be best, because $var could be a "falsey" value).
- Both DebugExtension and DumpExtension support variable arguments as well `{{ dump(foo, bar) }}` and we don't - another inconsistency.
- Our dump method actually echos the data out instead of returning it like theirs does.

Using their extension instead is the best option. However, we have a dump function in `safe_twig` (which I'm ready to :fire: more and more) that just returns null. 

So two options:
1) We add our dump function for `safe_twig`, but not for `twig` as it would override the extension's version.
2) We just copy their code into our method....but you know how I feel about duplicated code.

**Comment by bobdenotter** [comment]
@CarsonF I think we're talking about slightly different things.. Being the simple person that I am, my main concern is that the output of the `{{ dump() }}` tag should look like: 

![](http://symfony.com/doc/current/_images/01-simple.png)

and not like: 

```
array(3) {
  [0]=>
  int(1)
  [1]=>
  int(2)
  [2]=>
  array(3) {
    [0]=>
    string(1) "a"
    [1]=>
    string(1) "b"
    [2]=>
    string(1) "c"
  }
}
```

I'm fine with whatever way it's implemented. :-)

**Comment by CarsonF** [comment]
@bobdenotter We're on the same page :+1:
