### ISSUE TITLE
Publish & Depublish buttons not hooked up yet

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#4243]
@rarila's awesome work gave us new shiny things, and as noted in #4242 there is more to come… Just adding this so it's tracked.

![buttons](https://cloud.githubusercontent.com/assets/1427081/10360374/23688084-6d98-11e5-9acf-01ae806ecb62.png)

**Comment by bobdenotter** [comment]
Like! :+1:

**Comment by sbonardt** [comment]
Noice!

**Comment by GawainLynch** [comment]
> Noice!

Are you channelling your inner Aussie there @sbonardt! Watch out for drop bears in that case :grin:

**Comment by rarila** [comment]
@GawainLynch cant do now, we're in freeze :snowflake: you forgot? ;-)

**Comment by sbonardt** [comment]
@GawainLynch Bonkers mate!

**Comment by rarila** [comment]
Good that @SahAssar didn't add ``Low hanging fruit`` (my first thought) label already :sweat_smile::sweat_drops:

Cause after thinking a bit about it, there is more involved than just starting an AJAX call, do the thing and return an ``200`` on success. We have to render the changed rows, return them and replace them in the list. (Custom listings could e.g. print a bold "Published" in the list or color the background yellow or whatever)

Similar error in the current delete implementation. We have to return which records were deleted successfully (as it's possible that only a part of the deletions was really successful because of permissions). Here also just returning a ``200`` and remove the selected rows from the list will do.

**Comment by GawainLynch** [comment]
> Similar error in the current delete implementation. 

Yeah… this is part of what I was hinting at on IRC this morning… We're doing those calls to the controllers on synchronous routes and knowing something failed in kind of tricky.

Do you think the AJAX part is doable in this cycle? If so I might rework the controller routes as well and give you back either JSON or rendered elements, rather than a whole pages/routes.

**Comment by rarila** [comment]
@GawainLynch The AJAX part should be not that problematic. If I have the rendered ones or a id list of the actually deleted ones …

**Comment by GawainLynch** [comment]
@rarila I have [started a branch](https://github.com/bolt/bolt/tree/hotfix/controller-record-actions) for this on `bolt/bolt` to make collaborating easier.

**Comment by rarila** [comment]
:thumbsup:
