### ISSUE TITLE
"info:" option cant override "relations:"  infos.yml content

### ISSUE THREAD

**Issue by LXLH** [bolt/bolt#4244]
Hi everyone, i want to use the "info:" option in my relationships contenttype, but this cant be override. I can use the other options like "prefix:", "label:", "postfix:", but info: doesn't override the value from infos.yml

Thanks for your hard work !

**Comment by SahAssar** [comment]
Hey @LXLH!

First of all I'd like to apologize for taking so long to respond, secondly, If you could check that the issue still exists in a new, fresh bolt version it'd be great...

Thridly: Unfortunately this is probably part of the larger translation issue, but if you could post your contenttypes.yml, your locale from your config.yml and the translation file for that locale that would be helpful.

I'm going to close temporarily, since it's probably either an issue that has been solved in the meantime or one that is a part of the larger translation problem, but I'm looking forward to seeing your error report!

Thanks!
