### ISSUE TITLE
ContentTypes should have fields that are based upon other fields

### ISSUE THREAD

**Issue by tomntech** [bolt/bolt#4250]
It would be useful if there were a fields in content types that are only displayed in the editor when certain selections/conditions are met in related fields. 

E.G: A content type has a drop down which specifies split or full screen layout options. The user selects the split option and they are presented with 3 separate text areas, if they select the full screen option they are presented with one.

**Comment by PhillippOhlandt** [comment]
I solve that with different templates and templatefields.

**Comment by SahAssar** [comment]
@tomntech Is this something that you think cannot be solved equally well with template specific fields? I mean, if you change what fields are available you probably want to change the record template too, right?

**Comment by tomntech** [comment]
This could be used for a scenario such as:
Having n number of sections on a page. A drop down between 1 and 5 is provided as the first field for the content type, the user selects the number of fields and is presented with that many text areas (for example). The template contains a loop that searches through all fields in the content type.

Might be interesting to read some documentation on template fields too.

**Comment by SahAssar** [comment]
@tomntech That sounds like a much better use case for repeating fields, which will be in 2.3 that is released pretty soon. While I can see why this is wanted, this seems like a case where actually knowing where this would be the best solution would be critical to knowing **how** to do it. Personally I think that if grouping for template specific fields was handled just like normal fields it would solve this (when we also have repeating fields), but if you have a use case where that does not fit then that needs to be taken into consideration if this is to be done.

What I'm saying is that I'd like to see an example that fit's within bolt's philosophy but is not equally solvable by template specific fields or repeatable fields, so that we have something concrete to discuss here.

**Comment by SahAssar** [comment]
Moved to the forums, see here: https://discuss.bolt.cm/d/33-field-visibility-editability-based-on-other-fields-continuation-of-4250

Looking forward too seeing more discussion there!
