### ISSUE TITLE
Can't install using: composer require 'bolt/bolt ~2.2' 

### ISSUE THREAD

**Issue by aerth** [bolt/bolt#4265]
I have composer installed obviously.

```zsh
➜ composer require 'bolt/bolt ~2.2' --update-with-dependencies
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - bolt/bolt v2.2.9 requires composer/composer dev-master -> no matching package found.
    - bolt/bolt v2.2.8 requires composer/composer dev-master -> no matching package found.
    - bolt/bolt v2.2.7 requires composer/composer dev-master -> no matching package found.
    - bolt/bolt v2.2.6 requires composer/composer dev-master -> no matching package found.
    - bolt/bolt v2.2.5 requires composer/composer dev-master -> no matching package found.
    - bolt/bolt v2.2.4 requires composer/composer dev-master -> no matching package found.
    - bolt/bolt v2.2.3 requires composer/composer dev-master -> no matching package found.
    - bolt/bolt v2.2.2 requires composer/composer dev-master -> no matching package found.
    - bolt/bolt v2.2.13 requires composer/composer dev-master -> no matching package found.
    - bolt/bolt v2.2.11 requires composer/composer dev-master -> no matching package found.
    - bolt/bolt v2.2.10 requires composer/composer dev-master -> no matching package found.
    - bolt/bolt v2.2.1 requires composer/composer dev-master -> no matching package found.
    - bolt/bolt v2.2.0 requires composer/composer dev-master -> no matching package found.
    - Installation request for bolt/bolt ~2.2 -> satisfiable by bolt/bolt[v2.2.0, v2.2.1, v2.2.10, v2.2.11, v2.2.13, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, deleting ./composer.json.
```

**Comment by GawainLynch** [comment]
OK I think something has recently changed in Composer itself, @rossriley and I are tearing our hair out about another package in `master` right now that is giving us grief in the same way.

**Comment by gerkirill** [comment]
Got the same problem today. Figured out two parameters are required in composer.json before I do 'composer require'. They are:

    "minimum-stability": "dev",
    "prefer-stable": true,

this solved issue in my case.

**Comment by SahAssar** [comment]
Was it @CarsonF that had some wisdom regarding this in IRC? If so, ping! :)

**Comment by rossriley** [comment]
We have two problems. 
1. Composer does not have a stable release
2. PasswordLib does not have a stable release

So because of these libraries refusal to mark a stable release (despite composer having been downloaded nearly 1 billion times apparently) then it's impossible for Bolt also to install as a stable version.

So the ways round it are as suggested by @gerkirill dropping minimum-stability to dev or alternatively what we do in the official composer-install package is this:

https://github.com/bolt/composer-install/blob/master/composer.json#L6-L8

where we add explicit overrides for these two packages to allow dev version installs. Personally I'd choose the latter as It's not really good practice to set your stability level to dev.

**Comment by CarsonF** [comment]
Yeah I still haven't figured out why we don't just do `@dev` for those two packages....

**Comment by gerkirill** [comment]
Explicit @dev is completely ok for those 2 packages. But this means your documentation at https://docs.bolt.cm/installation-advanced is incomplete. I believe "Installing Bolt as a composer package / Composer.json modifications" section should be altered with the packages you've mentioned.

**Comment by CarsonF** [comment]
Should be fixed in next release. Until then `^2.2@dev` can be used

**Comment by gerkirill** [comment]
Well, regarding `"composer/composer" : "dev-master@dev"` in bolt's composer.json - that will not help in a case bolt is installed as a composer package (dependency), because stability is determined by the root package only, and stability flags  (e.g. @dev) are also root-only. Flags defined in dependent packages are simply ignored. This means one should have `"composer/composer" : "dev-master@dev"` in his root composer.json, and this means documentation at https://docs.bolt.cm/installation-advanced "Composer.json modifications" - is incomplete and should be updated. 

Currently it is not possible to install bolt as composer dependency just by following instructions in the documentation.

**Comment by CarsonF** [comment]
@gerkirill You know, you're right. I'm remembering now that I added composer package along with bolt so I could specify stability
