### ISSUE TITLE
cURL Timeout on extensions.bolt.cm

### ISSUE THREAD

**Issue by rompcik** [bolt/bolt#4279]
With 2.2.x I have a cURL timeout using the extension manager on a local development box. Seems curlopt_timeout is somewhere set to 10 seconds. But on a slim line (2MBit) the connection takes longer than that, leading to cURL error 28 if I try to browse versions and/or update:
> Extension Site Error
Error connecting to the Extension Marketplace:
cURL error 28: Operation timed out after 10000 milliseconds with 0 bytes received

Environment: Windows 7, Apache 2.4.16, PHP 5.5.30, cURL with SSL enabled

**Comment by GawainLynch** [comment]
Hmm… That is set [here](https://github.com/bolt/bolt/blob/release/2.2/src/Extensions/ExtensionsInfoService.php#L94-L96) but the file it is requesting is a tiny bit of JSON and while 2 MiB line isn't the fastest going, I have not hit that problem over slower lines.

I have to wonder if the problem is not that server playing up again.

**Comment by GawainLynch** [comment]
Yeah, it's the server!

**Comment by rompcik** [comment]
Works now. Thx for fixing the server that fast. As always: superb support.

**Comment by GawainLynch** [comment]
You're very welcome!

**Comment by skinysmn** [comment]
hi, same issue again
Error connecting to the Extension Marketplace:
cURL error 28: Operation timed out after 10001 milliseconds with 0 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
