### ISSUE TITLE
Bolt not responding on virtual machine

### ISSUE THREAD

**Issue by timo002** [bolt/bolt#4428]
Hello,

I am trying to get Bolt running on a Vagrant [Primary-Vagrant] (https://github.com/ChrisWiegman/Primary-Vagrant). The VM has all needed requirements but Bolt is not running.

In Chrome I get a `ERR_EMPTY_RESONSE` message after approximately 10 seconds.

When I accidentally make an error in the `app/config/config.yml` file, bolt directly throws an error about this (Bolt - Fatal Error).

I made a copy of the `phpinfo()` output, you can view this here: https://www.postitief.nl/phpinfo.html

**Comment by yamitenshi** [comment]
Is it always 10 seconds? If so, that might indicate a problem in the configuration of Apache and/or your vhost instead of a problem with Bolt. Otherwise, this will still be a hard problem to debug without some additional information.

Is there anything in Apache's error log?

Also, is this a completely clean Bolt installation, and did you install anything on the VM that wasn't there to begin with?

**Comment by timo002** [comment]
I took a look in the Apache error log (didn't think of that myself). I'm getting this error
`Warning:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bolt.bolt_pages' doesn't exist' in /var/www/bolt.dev/vendor/doctrine`

Yes, it's a fresh Bolt installation, installed by commandline.

**Comment by yamitenshi** [comment]
The uncaught PDOException is merely a warning, that doesn't cause an empty response.
I managed to reproduce the issue, and found out that something is causing a segmentation fault in Apache. I'll run gdb on a core dump, and I'll report back once I know a bit more, but honestly a segfault smells like a bug in either PHP or Apache more than an issue with Bolt.

**Comment by timo002** [comment]
You mean an error in the VM? Wordpress or own written php based websites and scripts are running fine.

If I may ask, how did you reproduce this?

**Comment by yamitenshi** [comment]
Same thing you did - install the vagrant box, install Bolt on it, create vhost config for it, change DB settings to use MySQL. Bolt never gets to run its install script, because after ~10 seconds, Apache receives `SIGSEGV` - you can see this in `/var/log/apache2/error.log` - it contains a line like

    [Wed Nov 11 18:07:45.298178 2015] [core:notice] [pid 585] AH00051: child pid 699 exit signal Segmentation fault (11), possible coredump in /tmp/apache-coredumps

which means the Apache process handling your request triggered a segmentation fault.

It's probably a bug with PHP and some of the modules in use - I've had the issue before when using APC in combination with Doctrine and Traits (I don't yet know if this is the same issue). It's unlikely that this is a Bolt issue - PHP is an interpreted language with a garbage collector and absolutely no way to manually allocate, access or free memory, so no PHP script should *ever* trigger a segmentation fault.

**Comment by yamitenshi** [comment]
Got it! The PDOException causes XDebug to log a stack trace. This causes a segfault when a call to `memcpy()` inside `xdebug_str_add()` fails because several calls to `mmap()` fail with `ENOMEM` - so the box is out of memory, probably because XDebug's stack traces are... rather large.

The call that fails is in `xdebug_str.c` on line 41 (see https://github.com/xdebug/xdebug/blob/XDEBUG_2_3_2/xdebug_str.c):

GDB tells me that in the call to xdebug_add_str, `xs->d` is `0x0` and `xs->l` is `109`. `xs-d` is `xdebug_str`'s internal character buffer. Probably a call to `malloc()` failed, and was never checked for a null return value. Therefore, `xdebug_str_add()` tries to copy a string to memory address `0x6d`, which it can't do because that memory address is not accessible to apache, causing a segmentation fault. 

GDB also tells me that `xs->a` (`xdebug_str`'s allocated memory size according to XDebug) is 187304468 - which means that at the point where `malloc()` failed, it tried to allocate more than 187 MB - and it just so happens that this is roughly the size of the string it's trying to append to the stack trace (`str` is 187302351 characters long at that point). With sizes like that, it's no wonder a vagrant box with 993 MB of memory and no swap fails to allocate that much. It also supports my hypothesis that this is an issue caused by limited memory and XDebug's enormous stack traces.

Honestly, I'd say that this is an issue with the box you're running. Having XDebug dump full stack traces on a box with very limited memory is not the best of ideas. As an indication, the generated core dump is a whopping 663 MB - which means that at one point that one instance of Apache had that much allocated memory. It's not unthinkable that that's all that's left of the 993MB you had to begin with.

Either way, it's not an issue with Bolt, but with the box (or with XDebug because it's allocating ridiculous amounts of memory).

**Comment by timo002** [comment]
@yamitenshi, many many thanks for you effort! I will report this at the Primary-Vagrant repo, of course with your credits!

I disabled XDebug in the `php.ini` file. Now Bolt is working fine!

**Comment by SahAssar** [comment]
@yamitenshi Thank you so much for all the help, info and debugging :)

**Comment by GawainLynch** [comment]
Slightly confused... Was this on stable or master?

**Comment by timo002** [comment]
@GawainLynch, stable. But it wasn't a Bolt issue!

**Comment by GawainLynch** [comment]
@timo022 see point about wine.. stupid... or was it confu... bugger it... I'm in an an airport :grin:
