### ISSUE TITLE
Contenttype owner does not have Edit option under Actions in Overview Screen

### ISSUE THREAD

**Issue by banjovy** [bolt/bolt#4439]
Permissions are set to allow only the owner to edit a given contenttype record. As owner, you can edit the content from the frontend (you do get the Edit link ), but when working from the Dashboard using the Overview >> Contenttype as owner there is no edit option under Actions. The record is not linked as well.

If I change the permissions to allow a role to edit, the overview displays the edit option correctly, however this is not the desired configuration. Only want content owners edit ability and from the overview screen.

I didn't see any existing issues with this description so please remove or mark as dup if required. Thanks

**Comment by SahAssar** [comment]
Hey @banjovy! Sorry for the late reply, just to verify is this in 2.2 or in master?

**Comment by banjovy** [comment]
I'm using 2.2.13.

Thanks,
Cecil

**Comment by SahAssar** [comment]
@banjovy Could you post your permissions.yml file? I'm having a bit of an issue recreating this.

**Comment by banjovy** [comment]
I've attached the file.
Take a look at the cases contenttype. What I want to do is to allow the 
owner to edit their own content, but not create any new. I have a 
process which creates new content and assigns an owner for each. I don't 
want users creating content directly.

You'll notice I don't have a create permission for this contenttype 
(desired). However with this configuration the user cannot click a link 
to edit their content on the BE (admin interface). They can click the 
Edit button on the FE and it will let them edit. If I give a role create 
permissions (sam), the edit buttons display correctly on the BE, but I 
don't want users to have this ability.

Thanks,
Cecil

**Comment by SahAssar** [comment]
Sorry, Github does not seem to like attachments in email replies to issues, could you either post it here inline or use something like pastebin for it?

**Comment by banjovy** [comment]
Hopefully you can see this?
[permissions_yml.txt](https://github.com/bolt/bolt/files/45320/permissions_yml.txt)

**Comment by SahAssar** [comment]
Sorry I've been swamped lately, I have just done some basic testing on this (and couldn't recreate). Hopefully I can verify/fix tomorrow.

**Comment by SahAssar** [comment]
Alright, after some digging the issue arose in #3906 when we changed from checking each record with "isallowed()" to checking once per contenttype. Your issue comes from the fact that the users have no permissions for that contenttype, their permissions solely come from that they are the owner of a certain record. A temporary "fix" would be to give them create privileges (but that's not what you want).

The assumption seems to be that you cannot own records if you cannot create records, which in your case isn't true since the editor role would create the records and then change the ownership to the specified users.

Personally I think we need checks for each record since otherwise the owner role won't work very well, but perhaps @GawainLynch or @rarila could weigh in?

**Comment by SahAssar** [comment]
Just for the record: comparison of before and after the change with the exact same users/permissions/content:

2.2.8: http://i.imgur.com/n8umgBw.png

2.2.14: http://i.imgur.com/noyU6FY.png

**Comment by SahAssar** [comment]
Posting part of the chatlog about this here for context.
```
11:02	gawainlynch	SahAssar: That one is f'ing complex
11:04	SahAssar	Yeah, it seems like it... I understand his usecase though, and currently bolt does not act logically with it.
11:05	gawainlynch	SahAssar: Well it is, IMHO, outside of how that was originally designed… I want to re-do this in v4 though if we can
11:05	gawainlynch	But it is a *lot* of work
11:05	gawainlynch	… and we need to get better test coverage
11:08	SahAssar	gawainlynch: Sure, it's just that it worked up until 2.2.9... Technically it seems like a regression to me.
11:10	SahAssar	Not saying that we should go back to that solution, but for usecases that use the owner role the releases after that have not worked as well as the ones before it.
11:11	gawainlynch	We'd break CAs application if we did revert :-D
11:15	gawainlynch	SahAssar: OK… mildly confused here
11:16	SahAssar	Btw "outside of how that was originally designed", do you mean that users were not meant to own records for contenttypes they do not have permissions for?
11:16	SahAssar	gawainlynch: Sorry, about which part?
11:17	gawainlynch	Well to be fair it was before my time… but reading the code, "owner" isn't a "role" as such… and is only partially implemented as such…
11:18	gawainlynch	SahAssar: So it is only in the dashboard that the edit button doesn't appear?
11:19	gawainlynch	But the problem comes in the amount of database queries that are generated to check "owner" roles
11:19	SahAssar	gawainlynch: Not just that. If the owner has delete permissions on records it owns but not on the contenttype itself that won't appear either, for example. This is the same for all actions.
11:20	SahAssar	So, Each of the actions on each of the records technically needs it's own check
11:20	gawainlynch	Which is hundreds of queries
11:21	SahAssar	gawainlynch: Does it actually have to query the DB for this?
11:21	gawainlynch	BTW… not arguing this down, just trying to mentally step though this
11:21	SahAssar	Yeah, got it.
11:22	SahAssar	Did the old isallowed() function query the DB?
11:22	gawainlynch	Well the problem is what data exists, when…
11:24	SahAssar	We have the user object, content object and the permissions to cross reference them, what more data is needed for the check?
11:25	gawainlynch	Looking through the code
11:33	SahAssar	As far as I can see the old code produces no more DB queries for permissions checks than the new. (Still not saying to roll it back, just checking if a permissions check on each record would be feasible).
11:36	            SahAssar feel's like he should have brought this up after "booze'o'clock". ;)
11:36	gawainlynch	Haha… Nah, just tired and stressed about the move… and Erin just bought me some breakfast too
11:38	SahAssar	gawainlynch: We could just put this discussion on ice for a few days If you'd like. I have no issue with that.
11:40	gawainlynch	SahAssar: Just staring at it… I think your point if valid… I just suck the day before travel :-D
11:41	SahAssar	Well, let's handle this when you are settled in NL. I'm guessing this needs some input from rarila and bopp on how to handle it in the future anyways.
11:43	gawainlynch	SahAssar: Sounds like a better idea… I would want to get slick0 in on this too, as it literally has the potential to break CA's application and just end us up at Square 1
```

**Comment by SahAssar** [comment]
Reason for adding to blocking:

> we need a decision on this sooner rather than later to make it predictable for future versions.

Also #3719...

**Comment by SahAssar** [comment]
Alright, posting some more chat excerpts here, for posterity/context:

steve_mp [5:55 PM] 
@sahassar: re: your question about the Git issue. I think I agree with the points that you make in the chatlog shown on the github issue. Isn't it a matter of "if this-record.owner = currentuser then show-edit-link = true" for each record returned from the database? I don't know the Bolt core at all as I'm a complete noob, but I would guess that the array of roles with the view permission is checked before running the database query (so that if the logged-in user doesn't have one of those roles there's no point running the query at all) but if the array contains the owner role, the query would need to contain "where content.owner-id = me.id" and could then display the results as if a normal role with the view/edit permission was logged in. I don't think it would need to do any extra database queries or run a separate query per record, would it?

bob [6:00] 
I think "fixing the bug" would be preferable over "workaround in an extension". :blush:

sahassar [6:00 PM] 
@steve_mp: Actually, it's even easier than that... If you look at https://github.com/bolt/bolt/pull/3906/files#diff-e0d0f9fb3082a8d80d7f100ddd09b5c1L17 for example, we have a method that can crossreference the logged in user with a record and the permissions to see if one is allowed to edit, create, delete, publish and depublish a certain record. This was "streamlined" in  #3906 by removing the checks from each record, and checking once for each contenttype, which of course breaks the owner "role", since nobody owns the contenttypes, they own individual records. So the question here isn't if it's possible, it's more how do we make it work for all the stakeholders in this case. I've bugged gawainlynch and a few others in core about this a couple of times, but we haven't had the full discussion yet.

sahassar [6:01 PM] 
So, the problem is that we need to figure out ​*how*​ we want it to behave before we actually implement it "again"

bob [6:04 PM] 
Sahassar: I'm of the mind that ​*a*​ fix is better than no fix. I'd be willing to get it fixed, even if it's different than how I would do it.

sahassar [6:06 PM] 
bob: It's more the problem that mine/banjovy/steve_mp's way of expecting it to behave is apparently not compatible with CA's way of expecting it to behave (and breaks their app). So there really needs to be a discussion about how to fix it before a fix is done.

**Comment by GawainLynch** [comment]
> It's more the problem that mine/banjovy/steve_mp's way of expecting it to behave is apparently not compatible with CA's way of expecting it to behave (and breaks their app)

No, it is that we settled on a way forward and how it worked before was "broken" as well… and to be honest, I am not sure we should attempt to "fix" this in v2… however I am open to a discussion for v3.

Thing is, that is going to delay release (not beta), but someone should front an RFC this week (preferably before Tuesday's meeting) and then we can try to get agreement on desired **functional** approach.

If that is back-portable to v2 without breaking current functionality, separate discussion that is 100% open. :smile:

**Comment by SahAssar** [comment]
This is currently tagged as a 2.2 LTS issue (the only one open right now), and it will not get "fixed" there. I hope to PR some additional checks for a 3.X.X release and perhaps that'll make it work in a way that suits everyone.

Also, since the jury is out on whether it's a bug that one is gone too.

**Comment by SahAssar** [comment]
Notabug, will be fixed with permissions restructure. Closing.
