### ISSUE TITLE
Missing fieldtype 'audio'

### ISSUE THREAD

**Issue by viaricardo** [bolt/bolt#4520]
Hi community!

I was developing a magazine news site and when I was modeling my contenttype I missed a pretty much common type of media: the audio.

The 'under the hood' very similar to video content, with the difference of there is no image area.

To solve my problem, I created in my contenttype another video field called 'audio' to adjust later on theme source code. 

Best regards,

Ricardo

**Comment by rarila** [comment]
You could also just use ``file`` or ``filelist`` instead of misusing the video field for it. I don't think you get any additional benefit by doing so.

In the future there probably could an audio field be added. A lib to extract some extra information from audiofiles would be needed (Length, bitrate, …?!) and some player would also be neccessary. Is there something like embedly for audio or is that one already able to achieve this?

Thinking about it, things are different anyway, as the video field is not for uploaded videos … So I guess you mean to link to audiofiles on the net?

**Comment by GawainLynch** [comment]
Audio fields have been implemented by CA, but they missed freeze on 2.3 to get them in.

Should land in 2.4

**Comment by viaricardo** [comment]
Nice! I'm happy to know! 

Thanks and congratulations, Bolt is beautiful! :)

**Comment by viaricardo** [comment]
rarila: I'll try this. I think it can be done with <audio> default tags, nothing fancy, <audio> is very well handled by mobile/desktop browsers. I haven't tried to embed video until now. For video I have a dedicated server with embed generator using <iframe>. Maybe I do the same with the audio.

GawainLynch: Very good to know! :+1: I'm very happy using Bolt! Congratulations! It is just beautiful! 

:smile:

**Comment by SahAssar** [comment]
Info for anyone that comes along: The version roadmap has changed, and since this issue mentions v2.4 (which is now 3.1/3.X) I'm posting this here https://discuss.bolt.cm/d/112-bolt-version-roadmap-changes/7

**Comment by GawainLynch** [comment]
@jkazimir can you update us at some point on the status of CA upstreaming this please.

**Comment by SahAssar** [comment]
@jkazimir or @mhodges-cainc: Is this something that you are still planning to PR?

**Comment by mhodges-cainc** [comment]
Good Evening,

Funny enough we were just talking about that today with Gawain.

We will be looking to add an audio widget extension once we remove our project specific details.

Thanks,
Matt
________________________________

**Comment by GawainLynch** [comment]
Ha! My reaction when I got the email too, @mhodges-cainc :grin:

**Comment by SahAssar** [comment]
So... Since this is clearly in extensionland now I'm going to close it :) Looking forward to seeing and using the extension!
