### ISSUE TITLE
[RFC] Minimum PHP version for Bolt 3.

### ISSUE THREAD

**Issue by GawainLynch** [bolt/bolt#4671]
There is a standing proposal from the development meeting on [2016-01-05](https://github.com/bolt/bolt/wiki/Dev-meeting-2016-01-05) to bump the minimum required PHP version to 5.5.9.

Relevant links:
* http://seld.be/notes/php-versions-stats-2015-edition
* http://phpversions.info/shared-hosting/ 
* c.f. https://bolt.cm/newsitem/bolt-2-2-0-released
* c.f. https://github.com/bolt/bolt/pull/4510#issuecomment-158612476
* https://github.com/bolt/bolt/pull/4510
* http://phpversions.info/shared-hosting/

Please add further commentary here and we'll make a decision at the 2016-01-12 meeting.

**Comment by bobdenotter** [comment]
These are the stats of Bolt users, for **Q4 2015**:

 - 5.3: 6.3%
 - 5.4: 13.4%
 - 5.5: 44.5%
 - 5.6: 34.3%
 - 7.0: 1.5%

**Comment by bobdenotter** [comment]
Just to note: This version bump is strictly for the **upcoming version 3.0** of Bolt. The 2.2 LTS version will remain at PHP 5.3.3.

**Comment by skoop** [comment]
I was in doubt a  bit about this one. I was considering suggesting to bump it to 5.6, mostly because of the fact that 5.5 is not supported anymore (only security updates). But given 5.5 still has security updates until July and 3.0 will come out before that, I'd say 5.5.9 would be fine. It would be good, however, to communicate in the release message that 5.5 is running out of security support from the PHP group, and nudge people into upgrading to PHP 5.6 (for which support will also [be dropped in August](http://php.net/supported-versions.php)). Even if you keep supporting unsupported PHP versions, it would be good to communicate the potential risk people might be running by having older versions of PHP on their machines.

**Comment by CoolGoose** [comment]
Imho's :)

1. 5.5.9 will allow a smoother transition for the symfony 3 version
2. I'm not sure if it's bolt's job of communicating that php 5.5 is getting unsupported "soon". 
3. Ubuntu 14.04 lts, comes with php 5.5 by default
4. RHEL7 (so centos7) comes with 5.4.16 by default, but RHEL software collection 2 from june 2015 has PHP 5.6 as an official alternative.

**Comment by bobdenotter** [comment]
Resolved by #4698
