### ISSUE TITLE
Improve handling missing content types

### ISSUE THREAD

**Issue by marcingajda** [bolt/bolt#4699]
In the config.yml file there are default values which imply that the user uses `page` content type:
```
homepage: page/1
notfound: page/not-found
```
Because of these values when he delete that content type he gets very confusing error:
```
PHP message: PHP Catchable fatal error:  Argument 1 passed to utilphp\util::array_first_key() must be of the type array, boolean given, called in ***/src/Storage.php on line 1885 and defined in ***/vendor/brandonwamboldt/utilphp/src/utilphp/util.php on line 2149
```
What I want to propose is to detect when certain content type is missing and throw a more suitable error, so the user know what is causing the problem and that he should look for usages of not existing content type.

**Comment by SahAssar** [comment]
Hmm, In the default template you are shown the following message if the homepage content isn't found: "Content for home not found! You should set 'homepage:' in your 'app/config/config.yml' to an existing record. Make sure that the content is published, otherwise it will not be shown."

In other themes you are probably show the normal index page, but without any content. What theme are you using?

**Comment by marcingajda** [comment]
I'm using my own theme. For now it's just an empty index file so obviosly I didn't handled the error and I got a blank page which confused me strongly. In the default theme everything works as you described, so the problem occurs only for themes developers. Anyway I think the error should be handled in the CMS, not in the theme but this is for Bolt develepers to decide.

**Comment by SahAssar** [comment]
@marcingajda I'm still not sure how it turned into that error... I just tried it out, and with (a *literally* empty) index.twig file I still don't get an error, with all the debug options turned on. Could you perhaps post your index.twig here or PM it to me so that I can see what went wrong?

I personally don't think that this message should be handled by Bolt itself, if a theme decides to show the message it's localized and available from the Bolt translations, but everything on the frontend is up to the theme and decided there. But, that's just my opinion :)

**Comment by marcingajda** [comment]
You know what? Now I can't reproduce this error. Maybe because I updated last time from 2.2.14 to 2.2.16. I think the case is closed.
