### ISSUE TITLE
not able to get the right count value from pager in my template 

### ISSUE THREAD

**Issue by andreasrrr** [bolt/bolt#4711]
I need to get the number of hits to display to the user when I do a search with pagination result
I try to find a way to get the acual hits of records via the pager array and the count value. I do a search with the setcontent like this:

{% setcontent records = 'mycontent' where whereclause orderby app.request.get('order') limit 20 allowpaging printquery%}

If I do a dump(pager) in my template I will not get the right values in the array. The count will be the total number of records in db
If I do a dump(pager) in the default pager template _sub_pager.twig the values are right and the pager works fine

It doesnt matter if I do the dump(pager) in my template before or after I called the twig pager() function in my template

**Comment by SahAssar** [comment]
@andreasrrr Are you perhaps trying to paginate results from a setcontent on a listing for the same contenttype as the setcontent? Because I know from experience that can lead to unexpected results.

You should also know that the `{{dump(pager)}}` will only output stats for the current, default listing. So if you are on a listing for `pages` and you do `{% setcontent records = 'pages' where { body: '%ipsum%' } limit 2 allowpaging %}` and then `{{dump(pager)}}` that dump will not show stats for your query, but will still be for the default `pages` listing query.

It seems like what you want to do might be easiest to do with a custom route, either using a templateroute, or a custom listing route with the appropriate parameters...

**Comment by marcingajda** [comment]
I'm using my own theme. For now it's just an empty index file so obviosly I didn't handled the error and I got a blank page which confused me strongly. In the default theme everything works as you described, so the problem occurs only for themes developers. Anyway I think the error should be handled in the CMS, not in the theme but this is for Bolt develepers to decide.

**Comment by andreasrrr** [comment]
@SahAssar Your right, thats what I am trying to do. I will try a custom route when I figure out how to set that up.

**Comment by SahAssar** [comment]
@andreasrrr Try a templateroute, like the example here: https://github.com/bolt/bolt/blob/release/2.2/app/config/routing.yml.dist#L144-L148

The pager has been refactored in 3.0 so it's possible that it does not have the same behavior there. Closing this, please feel free to reopen if you have more questions about this :)

**Comment by andreasrrr** [comment]
@SahAssar Tried your recommendation regarding templateroute. The pager values are not set at all if I use custom template route for this part. I still can not figure out how to access this value in my template files.Im only able to get this value out (pager.count) in the sub_pager template file

**Comment by SahAssar** [comment]
@andreasrrr Could you try this:
```
{% setcontent pages = 'pages/latest/3' allowpaging %}
{{pager('pages')}}
{{dump(app.storage.getPager('pages'))}}
```
`app.storage.getPager()` Should give you an array with all the pagers that can have been created within the current template.

**Comment by andreasrrr** [comment]
Thanks,It works!
