### ISSUE TITLE
Error "Keys don't match. Invalidating session" on log on from mobile

### ISSUE THREAD

**Issue by dianaarnos** [bolt/bolt#4805]
**Bug summary:** when I try to log on form my mobile phone with correct user and password I get back to the log in screen with messagem "Please log on". And when I log in using a desktop, I see the error message on "latest system activity"

**Specifics:** 
url: /bolt/login
bolt version: 2.2.16
bug occurs on log in from mobile browser. Tested on mobile Chrome and default phone web browser. When I log in from desktop's Chrome it goes ok.

**Steps to reproduce:** try to log in from mobile using an existing user.

**Expected result:** I should log in successfully.

**Actual result:** I get the "please log on" message and when I log in from desktop I can see the error about session and keys.
Error screenshot attached.
![screen shot 2016-02-04 at 8 56 24 pm](https://cloud.githubusercontent.com/assets/6060754/12832681/a09bcff0-cb82-11e5-911b-8fd24bfea54f.png)

**Comment by GawainLynch** [comment]
Olá!

Try setting [`cookies_use_remoteaddr: false`](https://github.com/bolt/bolt/blob/release/2.2/app/config/config.yml.dist#L339)

The cause is that mobile operators, and some ISPs proxy connections, and that changes your IP address, so our Man In The Middle protection kicks in and invalidates your session.

**Comment by dianaarnos** [comment]
Thanks! That solved the issue :)

**Comment by padawan** [comment]
For what it's worth, I just happened to have the same issue on a brand new site. Here it's because both my own ISP and my web server are using and listening on IPv4 and IPv6 simultaneously, and the network switches randomly between those networks, confusing Bolt with requests coming with two IPs for the same user session.

**Comment by GawainLynch** [comment]
> and listening on IPv4 and IPv6 simultaneously

Oh … my! Do you know what, that has never struck me as a potential trigger in all of this. :+1:

**Comment by padawan** [comment]
Well, after deleting cookies and sessions like there is no tomorrow to no avail, when I saw my IPv6 logged in the invalidation messages I had an epiphany. Then I found this and the workaround :)

**Comment by GawainLynch** [comment]
> Well, after deleting cookies and sessions like there is no tomorrow to no avail

Oh, I have so very much I've been there! :rofl:
