### ISSUE TITLE
Bolt 3.0?

### ISSUE THREAD

**Issue by gwbonline** [bolt/bolt#4861]
I'm really looking forward to Bolt 3.0... When can we expect some more info about it? I am planning to upgrade my existing installation. I was wondering: can I after installing 3.0 do some cleaning of not needed files or isn't this necessary? And are other files such as the config file different from the files I use now and do I have to replace them manually or is this done automatically?

**Comment by GawainLynch** [comment]
We are getting close to a beta… the bug tracker is #4202 and there will no doubt be further announcements soon. Probably the biggest hold up at the moment is updating documentation.

One thing to be careful of, is that with extensions a lot has changed and Bolt 2 extensions don't work with Bolt 3, so there might be some lag there. Things like BoltForms have already been updated, but some others might take time for authors to address… and you will need to be careful upgrading sites as a result. New sites should work out of the box.

Probably most important for you @gwbonline is that template stuff is still compatible, so that part is easy :grin:
