### ISSUE TITLE
[BUG] URLs in BoltBB forum are not generated properly - Bolt is in the subdirectory

### ISSUE THREAD

**Issue by AlexL777** [bolt/bolt#4873]
Hello Developers,

I've got a problem with **bolt/boltbb** forum, although I have my Bolt Installation in subdirectory under http://internet-blogger.net/cms/bolt and the Forum is therefore under **/forums**.

But the problem is that the Forum SEO URLs are not working correctly. The forums on the Forum may not be linked correctly. It seems that it is up to the rewrite rules in the .htaccess.

My .htaccess looks like this.

    <IfModule mod_rewrite.c>
     RewriteEngine on
     RewriteBase /cms/bolt/
     RewriteRule cache/ - [F]

     # Some servers require the RewriteBase to be set. If so, set to the correct folder.
     RewriteCond %{REQUEST_FILENAME} !-f
     RewriteCond %{REQUEST_FILENAME} !-d
     RewriteCond %{REQUEST_URI} !=/favicon.ico
     RewriteRule ^ ./index.php [L]

     </IfModule>

And in the boltbb.bolt.yml file it looks to me like that.

    # The forums you want to define
    forums:
    Offtopic:
    title: Allerlei
    description: In diesem Forum gibt es allerlei Themen. Alles, was woanders nicht hineinpasst.
    OpenSourceProjekte:
    title: CMS-Wikis-Foren
    description: Das ist ein Forum fuer OpenSource Themen und Projekte sowie Tools.

    # Maximum number of topics and/or replies to list on a page
    pagercount: 10

    # The base URI to use for the forums section of your site.
    # What you define here will create the URLs as:
    # http://internet-blogger.net/cms/bolt/{base_uri}/
    base_uri: forums

How can it be, then, that the forum URLs do not work? Can you help me somehow? Thanks in advance.

**Comment by SahAssar** [comment]
Hey @AlexL777,

I might be off here, but it seems to me like you would need to set `base_uri` to `/cms/bolt/forums` or `/cms/forums` depending on if the actual bolt install is at `/cms/bolt` or at `/cms`... Could you try that?

Also, since this is an extension issue I'm going to close it, if the above does not fix it could you please open an issue in the [bolt-extension-boltbb](https://github.com/GawainLynch/bolt-extension-boltbb) repo? We try to keep this one for bolt core issues. If this turns out to be a bolt core issue I'd be more than happy to reopen and investigate :)

Thanks!
