### ISSUE TITLE
[FEATUREBUG] app.paths[root] unreachable?

### ISSUE THREAD

**Issue by GDmac** [bolt/bolt#4949]
Master:

getPath(root) in config/resourcemanager/getPathObject
actually fetches "rootpath" instead of "root"
because, first check is if (array_key_exists($name . 'path', $this->paths)
and will never return app.paths[root], always returns app.paths[rootpath]

I don't know if this is intentional, or how this is supposed to work.
but IMO this is a confusing situation, ask [root] get [rootpath]
and seeing there is a [root] on dump(paths) but is unreachable?

Changing this might have B.C. consequences because
root = '/boltdir/'
rootpath = '/Users/gdmac/Sites/boltdir/'

Needs some thinking over maybe

**Comment by GDmac** [comment]
The same goes for ``{{paths.app}}`` like used in _page.twig, ``/boltdir/app/``
vs ``getPaths('app')`` which is ``/Users/gdmac/Sites/boltdir/app/``
is it a filesystem path (which the name suggests) or a url path, relative to the domainname?

**Comment by GDmac** [comment]
Is this fixed with your PR @CarsonF ?

**Comment by CarsonF** [comment]
Not sure. Just don't use `{{ app.paths }}` or `{{ paths }}`

**Comment by rossriley** [comment]
Yes, I know about this and whilst it's not ideal it's a remnant that we're stuck with for a while.

Before I did the work on ResourceManager to allow the paths and urls to be configurable they were all put in one array with no differentiation between paths and urls, whenever there was a clash then url had first call on the name and then path had the name with `path` suffix. So that's why we have `root` and `rootpath`.

In the `ResourceManager` class this is now separated, so you can do `$app['resources']->getPath('root')` and `$app['resources']->getUrl('root')` and they are stored separately.

However the one carryover is the `paths` array that is passed into twig, which is still used all over the place and requires the paths and urls to be merged.

So the way we need to attack this is deprecate `paths` for urls and have a separate array for `urls` eg `{{ paths.files }} {{ urls.root }} ` etc.

But obviously this will take a major version deprecation cycle so it won't disappear soon.
