### ISSUE TITLE
Layout misfit in sidebar.

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#4951]
See screenshot: 

![screenshot 2016-03-03 20 10 39](https://cloud.githubusercontent.com/assets/1833361/13506000/212e6a88-e17c-11e5-9a55-1a0ab4255e7f.png)

**Comment by CarsonF** [comment]
Why not just make the width larger?

**Comment by bobdenotter** [comment]
Of the entire sidebar?

**Comment by CarsonF** [comment]
Derp nevermind. I thought this was the symfony toolbar

**Comment by rarila** [comment]
There's always [text-overflow](https://developer.mozilla.org/de/docs/Web/CSS/text-overflow) and I suggest to solve the issue completely with a simple ":information_source:" ([fa-info-circle](http://fortawesome.github.io/Font-Awesome/icon/info-circle/))  instead of ":blue_heart: About" as you can be sure that lots of translations are longer than "About" and then you're back to the same problem.
