### ISSUE TITLE
[RFC] Language folders should be named as xx_XX

### ISSUE THREAD

**Issue by horus68** [bolt/bolt#5038]
Language folders should be named as xx_XX

Country Code Language List - http://www.fincher.org/Utilities/CountryLanguageList.shtml
Locales and Language Codes | Bodeux International LLC | Denver, Colorado - http://bodeuxinternational.com/locales-and-lang-codes/

It is better to do that before 3.0 is released as it will avoid breaking language config (when updating v3.0 to v.31 or other) is it could involve changing the local setting for non english users.

Some languages already follow the xx_XX rule. Languages not updated yet:
el = el_GR
es = es_ES
fi = fi_FI
fr = fr_FR
hu = hu_HU
id = id_ID
it = it_IT
ja = ja_JP
nb = nb_NO
pt = pt_BR
ru = ru_RU

**Comment by GawainLynch** [comment]
I had also suggested this before 2.0.0 was released, I am in favour of it myself… but wasn't there a problem with something to do with fall back @rarila … or is that a thing of the past?

**Comment by CarsonF** [comment]
:-1: My biggest problem with this is it does not follow Symfony. [Form](https://github.com/symfony/symfony/tree/master/src/Symfony/Component/Form/Resources/translations) and [Validator](https://github.com/symfony/symfony/tree/master/src/Symfony/Component/Validator/Resources/translations) translations are 2 letters (with a few exceptions).

**Comment by GawainLynch** [comment]
@CarsonF you raise a good point, and I think this has a lot to do with why we didn't make the change in 2.0.0. The `xx_XX` language/country codes are relevant where there is both a language differentiation, as well as an actual translation. e.g. if we split the current `pt` into `pt_PT` and `pt_BR` without having had the `pt_PT` ones translated *properly* then we're going to offend Portuguese speakers from Portugal, and so on.

**Comment by rarila** [comment]
@CarsonF I don't see the problem, as it [falls back](http://symfony.com/doc/current/book/translation.html#fallback-translation-locales) form ``xx_XX`` to ``xx``.

**Comment by CarsonF** [comment]
@rarila You are seeing it backwards. The fallback is for the requesting translation, not the provided resources. If a `xx_XX` translation is asked for and not found, the translator will fallback to an `xx` translation. If our translation files are in the `xx_XX` format there is no `xx` to fallback to.

There is no point in us having our 4 letter locales, with the exception of `pt`, `sr` and `zh`. Bolt is saying it provides _British English_ (`en_GB`), but not a generic _English_. So if I ask for `en` or even `en_US` it would find nothing. English is the special case because we have `en_GB` as the fallback. If I ask for `nl`, I would get English, not `nl_NL`. 
There is a reason Symfony calls it the _fallback locale_, it's because it's meant to be fell back on. If we switch to specific dialects we are removing the fallback functionality.

Also, the Symfony translation files are loaded based `$app['locale']`. If a 4 letter code is used, then they won't be loaded.

Part of this debate feels more academic than useful. People are usually asking for a language, but rarely a dialect. Even if they are asking for a dialect, `en_US`, they are fine falling back to the language, `en`.

**Comment by rarila** [comment]
What makes you think that only pt, sr an zh are valid exceptions? Aren't the few millions Austrians and Swiss people not worth to be able to add their version of German? I doubt the 4 letter locale wouldn't exist if there wouldn't be a need for them.

And why would the person creating the site (the one who edits config.yml) set nl there if that one doesn't exists. He gets English as he would get when requesting xy. Anyway, I think its a behavior that can be fixed if needed

**Comment by Sphinxxxx** [comment]
Has the xx_XX -> xx fallback stopped working? If i set `locale: nb_NO` in the main configuration, I don't get any translations. If i set `locale: nb` I do get translations, but then datetime formatting doesn't work.

**Comment by SahAssar** [comment]
Did we ever reach any consensus on this (I know we didn't in this thread, but some conversations happen elsewhere)?

Seems to me like if we follow the Symfony standard and for example have `pt_PT` and `pt_BR` we'd need an additional `pt` translation, right?

**Comment by GawainLynch** [comment]
Yes, but the political problems with users can then kick off. 

For the record, I agree that English is a special case and it would be safe to have an `en` default that was the content of `en_GB` and then have an `en_US` where someone felt the desire to translate.

**Comment by horus68** [comment]
regarding portuguese example: 
`pt` and `pt_PT` are the same: Main Portuguese (or Portuguese of Portugal / Portuguese european)
`pt_BR` is a variant from Brasil

**Comment by GawainLynch** [comment]
Translation update in progress, but not scheduled to land until 3.4.
