### ISSUE TITLE
[BUG] Newly created users are always enabled

### ISSUE THREAD

**Issue by Sjord** [bolt/bolt#5190]
When creating a new user, the user is always set to enabled, even if the "User account is enabled" dropdown is set to "no".

Details
-------

 - Relevant Bolt Version: v3.0.0-beta2-43-gb78bd7d
 - Install type: Github checkout
 - PHP version: 7.0.4
 - Used webserver: Apache
 - For UX/UI issues: Chromium Version 49.0.2623.108 Ubuntu 16.04 (64-bit)

Reproduction
------------

1. Under Configuration, Users and permissions, click the button "Add a new user"
2. Fill out the form. Leave the field "User account is enabled" on "no".
3. Click the button "Save user".
4. Notice that the created user is enabled (it has no strike-through), even though we set "user account is enabled" to "no".

**Comment by AlphaRecon19** [comment]
After a few hours of looking into this it looks to me like the user will always be getting set as enabled because of the function enableUser() created in #4392 and located [here](https://github.com/bolt/bolt/blob/master/src/EventListener/StorageEventListener.php#L194). I can see that it has changed since that commit but setting that value to false disables the user that I just created. And then adding another user with the option yes for 'User account is enabled' will also have the account disabled. 

So maybe this just needs to be tweaked a bit to have some more logic added to it (or is it still needed)?
