### ISSUE TITLE
Extensions with 'custom field types' can't find templates. 

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#5237]
Extensions that add custom field types can't find the twig file for the field itself. 

Details
-------

 - Relevant Bolt Version: [  master ]
 - Install type: [ Github checkout ]

Reproduction
------------

 - Install Ross' Colourpicker: https://github.com/rossriley/bolt-extension-colourpicker/
 - add a `type: colourpicker` field to a contenttype
 - Edit a record. 
 - 🔥💥

![screen shot 2016-04-22 at 15 24 48](https://cloud.githubusercontent.com/assets/1833361/14743396/b187743e-08a1-11e6-84bb-0273be426406.png)

**Comment by GawainLynch** [comment]
For reference, setting [this line](https://github.com/rossriley/bolt-extension-colourpicker/blob/v3.0/src/Field/ColourPickField.php#L16) to 
```
        return '@Bolt/_colourpicker.twig';
```
…fixes the problem.

**Comment by GawainLynch** [comment]
So not sure if we should "fix" this in core… 

[Here we do](https://github.com/GawainLynch/bolt/blob/release/3.0/app/view/twig/editcontent/_field.twig#L16):

```twig
    {% include context.fields[field.type].template with {
        'key': key,
        'name': key,
        'contentkey': key
    } %}
```

So we'd have to do a `{% set %}` to get the template and then test to see if it starts with Bolt's admin namespace.

I can't help but feel that given we're moving toward namespaces for Twig, that we should cope with this by updating that extension, and updating associated documentation.

Thoughts @bobdenotter @rossriley @CarsonF @rarila ?

**Comment by rossriley** [comment]
Yes, it leads to a bit of a what if.

Currently the twig path is registered:

```
        return [
            'templates' => ['position' => 'prepend', 'namespace' => 'bolt'],
        ];
```

So we're saying we want our templates path to supercede the Bolt one which is great if for instance we wanted our extension to replace `_select.twig` or one of the other existing ones.

However if we're providing a new template and within the field we provide the template eg:

```
public function getTemplate()
{
        return '_colourpicker.twig';
}
```

Then there's no need to use the Bolt namespace and we could encourage a different strategy since in some cases we run the risk of accidentally replacing other templates for instance at the moment by default everythig gets registered in the `__main__` namespace but if two extensions defined an `index.twig` template then we have a clash.

So how about instead of defaulting to `FilesystemLoader::MAIN_NAMESPACE` we default to the extension name so the path would be registered and the template would be defined:

```
// In Extension
return [
    'templates' => ['namespace' => 'colourpicker'], // this could be optional and default to ext name
];

// and then in the field class
public function getTemplate()
{
        return '@colourpicker/_colourpicker.twig';
}
```

**Comment by CarsonF** [comment]
I am totally for what @rossriley suggests. It is basically the same thing as what Symfony does with their bundles. 

But what if they want to overload a template? It wouldn't work because it would be in a different namespace. I guess maybe at that point they add a path themselves?

**Comment by rossriley** [comment]
If you want to override a template within the Bolt namespace you just do what we do now:

```
return [
            'templates' => ['position' => 'prepend', 'namespace' => 'bolt'],
        ];
```

and then match your directory structure in templates to be the same as the Bolt layout.

For instance I'm just rewriting the sortable relations plugin and that replaces `editcontent/_relationships.twig` the prepend ensures the extension replaces the default.

There's no need for this to be the default behaviour since most extension devs are providing supplementary templates in which case the namespace can default to the extension name.

**Comment by martinfojtik** [comment]
this is not working if i try create custom field in Bundled extension
