### ISSUE TITLE
Search autocomplete doesn't work in the documentation page

### ISSUE THREAD

**Issue by superferenabled** [bolt/bolt#5297]
It was working well yesterday. I am using google chrome. I think is something with the change to the new version.

**Comment by PhillippOhlandt** [comment]
We already checked this. Everything seems fine on our side and it's already reported to Algolia. Should work again soon :)

**Comment by GawainLynch** [comment]
@superferenabled thank you very much for reporting this, and as @PhillippOhlandt mentioned we're nagging upstream about fixing it a.s.a.p.

I'm going to close this as it is "under control" (like a run away bus :wink:) but if you find more problems, or it isn't fixed in the morning, feel free to press the "Re-open" button :+1:
