### ISSUE TITLE
[RFC] Add check for .bolt.yml to selftest

### ISSUE THREAD

**Issue by xstable** [bolt/bolt#5333]
If .bolt.yml not exist, some things went wrong.
For example, if you create a new Folder und upload a file in the "Filemanager-Section", it will be put to /files, instead of /publish/files.

To got bolt setup (or move to another webspace) as easy as possible, it would be really nice to check if .bolt.yml exist. 
If not, throw an error, or give a message on the Bolt-Backend - Dashboard (like the advice that mail is not yet configured).

**Comment by SahAssar** [comment]
Isn't the `.bolt.yml` one of those files that are pretty much required/expected to be there in any deployment? Unless it's a git install (which is not recommended) it'll be there, right?

**Comment by rossriley** [comment]
I think it would be preferable for `.bolt.yml` to be optional, now the install types all default to a `public` folder it would make sense to just modify the ResourceManager to default to `public/files` and the theme to `public/theme` etc, it may be the case that we can switch out the resources to default to the Configuration\Composer since as far as I'm aware, that's now the standard layout for installs of both types.

**Comment by rossriley** [comment]
Pretty sure this one is taken care of now, the recent refactor makes the file optional and also renamed it to `bolt.yml` so it's not a hidden file any more.... this will make it much harder to get lost too in any uploads via ftp where some clients will not show hidden files, now it will be visible.

**Comment by SahAssar** [comment]
Adding some context to above for posterity, I think these are relevant: #5909 #5894
