### ISSUE TITLE
[RFC] Contenttype field "select" values get stored as longtext in DB

### ISSUE THREAD

**Issue by jan-t3000** [bolt/bolt#5356]
I would assume "select option" values are rather short, so I'd vouch for changeing this at least to varchar(whatever-you-see-fit).

**Comment by rossriley** [comment]
Yes, from memory this was a deliberate change since the select field is a dual field type, both for single select values but also via multiple it becomes a JSON stored field and can easily extend the 255 chars for a varchar.

In Bolt 3.0 internals we've separated these into two different types so as of the next full version (4.0) we could make the decision to disable the dual usage and at that point we can use VARCHAR fields for single selects and TEXT fields for multiples, but until then we're limited to the current implementation.

**Comment by jan-t3000** [comment]
I see, thanks for the information.
I indeed did not have multiple select options in mind, so it's "useability over performance" for now...
Fine. Having dual usage 'disabled' would be optimal, 4.0 then :D
