### ISSUE TITLE
[RFC] Should we put COMPOSER_HOME env var in bootstrap? 

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#5405]
There have been a few cases where people had issues setting up Bolt, where it could be fixed by adding this to the bootstrap: 

`putenv('COMPOSER_HOME=' . $app['resources']->getPath('cache/composer'));`

Should we just include that in Bolt itself?

**Comment by bobdenotter** [comment]
For example: #5172

**Comment by GawainLynch** [comment]
You mean like [here](https://github.com/bolt/bolt/blob/release/3.0/src/Composer/PackageManager.php#L40).

**Comment by GawainLynch** [comment]
The problem is safe mode in some hosts so doing it in PHP is useless.

**Comment by bobdenotter** [comment]
Yes, like there. 

Then what was with the guy in slack this morning, who added it to the bootstrap (in PHP), and bolt started working for him?

I'll have to look that up. :-)

**Comment by GawainLynch** [comment]
He's probably on a shared host with safe mode on, but the htaccess settings are still workable.

**Comment by rossriley** [comment]
I went down the rabbit hole on this before, from memory the problem is normally caused via the bolt.extend service provider instantiating the action classes, I think the main culprit was `Action\DumpAutoload` maybe because it's the first in the stack, or maybe because of something it does in its constructor.

So, although we have that `putenv` command in the `PackageManager` class, it hasn't been called by the time the first action is constructed so that lead me to just set the environment variable in bootstrap before the `$app->run()` method which then seems to prevent the issue.

**Comment by GawainLynch** [comment]
@rossriley: Were you previously debugging this on Bolt 2.x? The actions now all get build as a containers inside the [`$app['extend.action']`](https://github.com/bolt/bolt/blob/release/3.0/src/Provider/ExtensionServiceProvider.php#L83-L100) container and they use a single constructor from a base class that only assigns the [passed-in `$app`](https://github.com/GawainLynch/bolt/blob/release/3.0/src/Composer/Action/BaseAction.php#L34-L37)

**Comment by GawainLynch** [comment]
Never mind… found out why :laughing:
