### ISSUE TITLE
[RFC] Template field groupings by sub-tabs

### ISSUE THREAD

**Issue by Maelstromeous** [bolt/bolt#5519]
I've currently got a project that uses a lot of template fields, as the design is rather custom.

I think it would be pretty sweet if we could assign groupings to Template fields on a per-template basis. This would clean up the Template tab of the contenttype (in my case "page") editor quite significantly, and would make navigation of specific elements much easier.

Example:

---

![Example](http://i.imgur.com/JztnJOl.png)
## Details
- Relevant Bolt Version: 3.0.9
- Install type: N/A
- PHP version: N/A
- Used webserver: N/A
- For UX/UI issues: N/A

**Comment by SahAssar** [comment]
This RFC is for sub-tabs, like we spoke about in slack, right? Just keeping check here, since having them in top-level tabs is "covered" in #4875 (which I didn't remember when we talked) :laughing:

**Comment by Maelstrome26** [comment]
That's right yup :-)

**Comment by Maelstrome26** [comment]
Edited title to be a bit more clearer

**Comment by bobdenotter** [comment]
Because of "Spring cleaning", we're going to close this issue. Unless somebody steps up to help out with implementing it, it's not expected that the core team will have the opportunity to work on this soon. Keeping it open might set false expectations for people stumbling upon this issue.

This is not because we don't see this feature as potentially worthwhile, it is more to do with an overload of potential new features that could be developed combined with non-limitless amounts of available time and resources. 

If you disagree, feel free to re-open for discussion.
