### ISSUE TITLE
Escaping outputting data

### ISSUE THREAD

**Issue by ruvasik** [bolt/bolt#5551]
Details
-------

 - Relevant Bolt Version: 3.0
 - Install type:  Zip/tarball install 
 - PHP version:5.5
 - Used webserver: Nginx 1.9

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

 1. When I output the data in extension using getrepository they are unnecessarily screened for image field. In back-end field content with right format (without escaping). Sample ``avatars/demo-avatar.jpg``
 2. Using repositories manage collections of entities
 3. https://docs.bolt.cm/3.0/storage/repositories#createquerybuilder get record with image field
 4. Raw string with path to image file.
 5. Sample ``{"10":{"title":"TEST","trackid":"0","avatar":"{\u0022file\u0022:\u0022avatars\\\/demo-avatar.jpg\u0022}"}}``

**Comment by SahAssar** [comment]
The reason for this is that the image field is actually an JSON field since one can have title & alt attribs that also need to be stored in the same field. So, when you JSON encode your results you basically end up with JSON in JSON, the same as would happen with an imagelist, filelist or geolocation field for example.

Does that make sense or am I misunderstanding you?

**Comment by SahAssar** [comment]
Closing as it seems like it is Not-A-Bug™, and no reply has come in... Please reopen if I'm wrong! :)
