### ISSUE TITLE
[BUG] Setting only_aliases to true in config breaks thumbnail generation for backend CMS

### ISSUE THREAD

**Issue by Maelstromeous** [bolt/bolt#6016]
Details
-------

E.g.

Link generated is: `PATH/thumbs/200x150b/2016-11/-0.white-bull-cover.jpeg`

But in the browser that file doesn't exist and is broken. Nor does the image exist on the filesystem.

 - Relevant Bolt Version: 3.2.1
 - Install type: Composer install
 - PHP version: 5.6
 - Used web server: Apache
 - For UX/UI issues: Chrome 54

Reproduction
------------

1. Set `only_aliases` to true
2. View a contenttype with an image
3. Observe the thumbnail preview of any image broken.

**Comment by bobdenotter** [comment]
My initial thought was to add a check for a valid session here, where we set `only_aliases` in the serviceProvider: 

https://github.com/bolt/bolt/blob/release/3.2/src/Provider/ThumbnailsServiceProvider.php#L75

That doesn't work however, because it's too early in the request cycle.

Alternatively, we can't check it in `bolt/thumbs` either when generating the thumbnail, because that code is not aware of Bolt's stuff. Neither should it be. 

So, I think this is not trivial to fix.

**Comment by GawainLynch** [comment]
> That doesn't work however, because it's too early in the request cycle.

FYI that is in the registration cycle, so prior to request cycle altogether.

**Comment by bobdenotter** [comment]
Ah, yes. Of course!

**Comment by bobdenotter** [comment]
ficed in https://github.com/bolt/bolt-thumbs/issues/32
