### ISSUE TITLE
[RFC] Allow thumbnail filetype conversion (e.g. PNG -> JPG)

### ISSUE THREAD

**Issue by Maelstromeous** [bolt/bolt#6030]
I figure it may be a good idea to allow users to specify which file type they'd like to use. A typical use case may be to convert .PNG files to .JPG for numerous benefits, mainly to compress images down for mobile usage.

**Comment by GawainLynch** [comment]
For me, this is really out of scope (not rejecting it, just noting).

The CMS should make it easy for people to build sites, and publish content. Image manipulation is pretty complex and prone to problems. Add to that we can' guarantee what version of PHP extensions people might have, etc.

**Comment by Maelstromeous** [comment]
That is a good point, would it be easy to add this functionality via an extension of some kind?

**Comment by SahAssar** [comment]
Just flagging: This was sorta mentioned in #3703.

**Comment by cdowdy** [comment]
@Maelstromeous I've created an extension that will allow you to do this. Warning it's still in flux (read as still beta and lots of work still being done haha).  

It uses [Glide](http://glide.thephpleague.com/). This gives you the ability to use Imagemagick if you so choose but you really aren't gaining anything over GD, which is bolts thumbnail handler, currently.   

here is the extension: https://github.com/cdowdy/boltbetterthumbs  

to change the format as you mentioned from PNG to jpg in a template you would do:  

```twig  
{# twig template usage #}  
   {{ img(record.image, 'srcset', {
        'modifications': { 'medium': { 'w': 680, 'fm': 'jpg'   } } 
    } ) }}  
```  

or you could set it in the extensions config. 

The syntax right now is kinda rigid IMO so I'm working on that and it's very declarative which kinda stinks haha. 

You might get away with using it right now for some non-critical things since it's very much in flux and things will change

**Comment by Maelstromeous** [comment]
@cdowdy Oh sweet! And you've got srcset support as well, that's very nice! I'll be using it in my project I'm working on now, I'll let you know how it goes.

**Comment by Maelstromeous** [comment]
@cdowdy Any chance you could publish this on the Bolt Extension Store? Would make installation a tad easier for potential users.

**Comment by cdowdy** [comment]
@Maelstromeous sure can.. I was hesitant to publish this since there are still some little things that could trip up someone that isn't me since I've been working on this for a bit haha... but yeah I'll put this up here shortly!

**Comment by Maelstromeous** [comment]
@cdowdy No worries, are you on the Bolt Slack group? Might be handy to talk directly?

**Comment by GawainLynch** [comment]
Legendary, Cory … Love your work mate!

@Maelstromeous shall we call it a day on the RFC then?

**Comment by Maelstromeous** [comment]
@GawainLynch Sure, a solution has been found!
