### ISSUE TITLE
[RFC]  multi delete option on linked contenttypes

### ISSUE THREAD

**Issue by prdurand** [bolt/bolt#6032]
Hi
It could be usefull to be able to delete linked entries when deleting a content.
In concert venues websites for exemple, if the structure uses ArtistPage and EventDates contenttypes, then the webmasters would appreciate to be asked to delete also the linked dates when they choose to delete an artist page.

in contenttype configuration, it could be an option on the relation tag:
artistpage:
-- relations:
---- eventdates:
------ multiple: true
------ autodelete: true

in backend, the confirmation popin would ask:

Are you sure you want to delete the Artiste Page?
This Artist Page is linked to 3 Event Dates, and they won't be linked to anything after ArtistPage deletion.
[cancel] [Delete only the artist page] [Delete Artist Page and 3 Event Dates]

It has to be thinked further, as multiple or chained relationship could be more complicated to manage, but who knows... you already made magic until here ;)

**Comment by bobdenotter** [comment]
Because of "Spring cleaning", we're going to close this issue. Unless somebody steps up to help out with implementing it, it's not expected that the core team will have the opportunity to work on this soon. Keeping it open might set false expectations for people stumbling upon this issue.

This is not because we don't see this feature as potentially worthwhile, it is more to do with an overload of potential new features that could be developed combined with non-limitless amounts of available time and resources. 

If you disagree, feel free to re-open for discussion.
