### ISSUE TITLE
[RFC] Bolt twig templates exposing too much information even with debugging disabled

### ISSUE THREAD

**Issue by Crazybus** [bolt/bolt#6062]
With debug disabled bolt normally nicely displays a generic 'Whoops, looks like something went wrong.'

![image](https://cloud.githubusercontent.com/assets/4550136/20475358/c155b2b4-afcb-11e6-977a-f3c8c2fd39ee.png)

However if the error occurs within a twig template some debugging/bolt information is showed to the user instead. 

![image](https://cloud.githubusercontent.com/assets/4550136/20475350/b50a062c-afcb-11e6-9d20-0a06f4619e18.png)

Details
-------
- The [template](https://github.com/bolt/bolt/blob/6307ce400eb9e74b7f6140bc7a8e684ce38b50c4/app/view/twig/exception/exception.twig#L35) is configured to only hide some of the information if debug is enabled, however other things like the class, error message, line number and file_name are being still being displayed. 
- Bolt branding/logo is being showed allowing users to know which CMS is running on the website. Ideally this should be hidden with debugging disabled
- Debug config: 
```
debug: false
debug_error_level: 0
debuglog:
    enabled: false
```

Proposal
------------
No specific errors or branding are shown when twig runs into an exception. When getting a twig templating error with debugging disabled a simple "Whoops, looks like something went wrong" with no branding is displayed to the user. I'm happy to implement the changes myself however I would first like to hear what you guys think.

P.S I actually like brown M&M's

**Comment by GawainLynch** [comment]
> I actually like brown M&M's

Personally, I am more of a stroopwafel fan since moving to Netherlands :smile_cat: 

> However if the error occurs within a twig template some debugging/bolt information is showed to the user instead.

Actually, this will occur whenever Bolt gets past the registration cycle, into `boot()`.

> No specific errors or branding are shown when twig runs into an exception. 

This is an implementation choice. 

One of the design goals with the 3.2+ exception handling is to make the above extension controller & templates configurable so that an implementer could have "pictures of kittens"  shown to normal web users should they desire. But, it isn't quite there yet and the idea with 3.2.x was to let it settle and invest time knocking out bugs in the code base that we knew would start to show up having exception handling "sorted".

… all that aside …

If you'd like to help in improving the situation for extending this further, I am all :ear:  :ear: (side note, in the middle of a 11 day work trip, so excuse late responses)

**Comment by bobdenotter** [comment]
It currently looks like this in Bolt 3.3, for non logged in users:

![screen shot 2016-12-22 at 21 51 06](https://cloud.githubusercontent.com/assets/1833361/21439927/c4936a92-c890-11e6-9866-7033e544d1e1.png)

The point could be made that "leaking" the fact it's Bolt is bad practice, but I can think of a dozen other ways to determine whether a site is running Bolt or not. 

If more needs/should be done, feel free to re-open.
