### ISSUE TITLE
[BUG] Bolt logging out automatically, over and over again

### ISSUE THREAD

**Issue by siliconjohn** [bolt/bolt#6072]
I've done 2 installations of 3.2.2 on 2 different servers, each time I can create the first user and log in once or twice after that I can not log in again or can only log in for a couple of seconds before it logs me out again. Both installs were done via ftp. The only fix I have found is to change these from config.yml to false:

cookies_use_remoteaddr: false
cookies_use_browseragent: false
cookies_use_httphost: false

This fix is from  [https://www.linkedin.com/pulse/solved-bolt-cms-dashboard-login-problem-muhammad-wilson](url)

**Comment by bobdenotter** [comment]
You are most likely using a proxy somewhere in between, knowingly or not. This proxy can mess with your reported ip address or browseragent, causing Bolt to log you out if this happens. This is not a bug, but intentional behaviour. 

The "fix" you described tells bolt to be less strict about this. 👍
