### ISSUE TITLE
[RFC] Use of Symfony security component in the BO

### ISSUE THREAD

**Issue by dantleech** [bolt/bolt#6167]
@GawainLynch mentioned that Bolt would adopt the Symfony [secuty component](http://symfony.com/doc/current/components/security.html) in the backoffice.

So just creating this issue as a point of reference.

The security component would bring the following advantages:

- Firewalls (e.g. restricting access by URL)
- Different authentication mechanisms.
- .. more here

**Comment by bobdenotter** [comment]
Because of "Spring cleaning", we're going to close this issue. Unless somebody steps up to help out with implementing it, it's not expected that the core team will have the opportunity to work on this soon. Keeping it open might set false expectations for people stumbling upon this issue.

This is not because we don't see this feature as potentially worthwhile, it is more to do with an overload of potential new features that could be developed combined with non-limitless amounts of available time and resources. 

If you disagree, feel free to re-open for discussion.

**Comment by dantleech** [comment]
I see that the security component was already brought in [here](https://github.com/bolt/bolt/pull/6231). Might have a go at this - would be a big plus to use the Symfony security component imo.

**Comment by GawainLynch** [comment]
Can you coordinate with myself & @CarsonF if you want to go forward with something, as we already have a few things in (early) motion with planing.

Also, it is unlikely we'll be able to fully implement it in 3.x, but definitely in 4.0. My intent with the linked PR was to get the base parts in, so that exactly these discussions can get started :smile:
