### ISSUE TITLE
[RFC] Add direct link to file download

### ISSUE THREAD

**Issue by Maelstromeous** [bolt/bolt#6187]
Right now there's no way to directly get the full file path to allow downloads from a file contenttype. Ideally, we should have a system similar to other contenttypes which uses the `{{ record.contenttype>.link }}` syntax.

Right now we have to construct a full path to the file, such as: `{{ base_url ~ '/files/' ~ record.file }}` which in my opinion is rather messy.

E.g, with a contenttype called `file`:

`<a href="{{ record.file.link }}">blah</a>`

Or alternatively, if `.link` cannot be done:

`<a href="{{ record.file|download }}>blah</a>`

---

Version: 3.2.3

**Comment by bobdenotter** [comment]
Because of "Spring cleaning", we're going to close this issue. Unless somebody steps up to help out with implementing it, it's not expected that the core team will have the opportunity to work on this soon. Keeping it open might set false expectations for people stumbling upon this issue.

This is not because we don't see this feature as potentially worthwhile, it is more to do with an overload of potential new features that could be developed combined with non-limitless amounts of available time and resources. 

If you disagree, feel free to re-open for discussion.
