### ISSUE TITLE
UndefinedFunctionException exif_read_data on PHP-BuiltIn-Server

### ISSUE THREAD

**Issue by xstable** [bolt/bolt#6244]
If you run bolt with built-in PHP-Webserver:
```
sudo php -S localhost:80 -t . index.php
```
you got an error (e.g. if you go to Templates in Bolt-Backend) because of missing function.

> UndefinedFunctionException in Native.php line 183:
> Attempted to call function "exif_read_data" from namespace "PHPExif\Adapter".

If you catch this error, with `function_exist` Check,  it will work again with build-in PHP Webserver:
```
    /**
     * Reads & parses the EXIF data from given file
     *
     * @param string $file
     * @return \PHPExif\Exif Instance of Exif object with data
     * @throws \RuntimeException If the EXIF data could not be read
     */
    public function getExifFromFile($file)
    {       
        $sections   = $this->getRequiredSections();
        $sections   = implode(',', $sections);
        $sections   = (empty($sections)) ? null : $sections;
/* START HERE*/
if(function_exists("exif_read_data")){
        $data = @exif_read_data(
            $file,
            $sections,
            $this->getSectionsAsArrays(),
            $this->getIncludeThumbnail()
        );
}/* END HERE*/

        if (false === $data) {
            throw new \RuntimeException(
                sprintf('Could not read EXIF data from file %1$s', $file)
            );
        }

        $xmpData = $this->getIptcData($file);
        $data = array_merge($data, array(self::SECTION_IPTC => $xmpData));

        // map the data:
        $mapper = $this->getMapper();
        $mappedData = $mapper->mapRawData($data);

        // hydrate a new Exif object
        $exif = new Exif();
        $hydrator = $this->getHydrator();
        $hydrator->hydrate($exif, $mappedData);
        $exif->setRawData($data);

        return $exif;

    }
```

Please add this in the next Release.

**Comment by bobdenotter** [comment]
Your PHP interpreter on the command line must be a different one than your webbrowser. You can check this by running `php -v` on the CLI, and checking `phpinfo();` in the browser. 

The php-exif module is required for Bolt (as specified in the docs), and the CLI version is missing it. So, this  is not really a Bolt error. 

I'm not really a fan of adding this to PHP thumbs, because it will only cause it to fail silently for people who don't have this required php module. 

Feel free to re-open, if you disagree. :-)
