### ISSUE TITLE
Content type repeater does not work

### ISSUE THREAD

**Issue by markoffk** [bolt/bolt#6272]
Hello.
Today I met some strange bug: if I define new content type with complex name with spaces (in my case singular name "Radio Station") then any repeater field for this content type is always an empty array in twig templates. You can still modify this repeater from admin panel, and it correctly saves added values, but when you try to access it from frontend - it is always empty.

Workaround: make is one-word: "Radiostation" - then repeaters behave correctly in twig templates.

**Comment by SahAssar** [comment]
@markoffk How are you accessing it in twig?

**Comment by rossriley** [comment]
This issue is noted, but it is a case of Bolt not throwing an error since we do not support spaces in contenttype or field names, the only valid character is an underscore. For display purposes use the `name` and `singular_name` options eg:

```
radiostation:
    name: Radio Stations
    singular_name: Radio Station
    fields:
        title: 
......
```

We'll add an appropriate warning message in the next version if you do use spaces in the contenttype name.

**Comment by markoffk** [comment]
Thanks, @rossriley !
