### ISSUE TITLE
[RFE] Add a 'diff' option to the editor

### ISSUE THREAD

**Issue by leggewie** [bolt/bolt#6326]
It would be nice if the editor had a third button other than "Save" and "Revert changes", namely that of "Show changes" between the two. I always like to inspect changes I make before saving them.

**Comment by GawainLynch** [comment]
There is already the built-in [change log](https://github.com/bolt/bolt/blob/release/3.2/app/config/config.yml.dist#L178-L183) and there is [CA's revert extensions](https://github.com/ca-team-sulley/bolt-extension-content-revert) that could be combined.

**Comment by bobdenotter** [comment]
Because of "Spring cleaning", we're going to close this issue. Unless somebody steps up to help out with implementing it, it's not expected that the core team will have the opportunity to work on this soon. Keeping it open might set false expectations for people stumbling upon this issue.

This is not because we don't see this feature as potentially worthwhile, it is more to do with an overload of potential new features that could be developed combined with non-limitless amounts of available time and resources. 

If you disagree, feel free to re-open for discussion.
