### ISSUE TITLE
Crash using "Setcontent search"

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#6752]
It seems the "Setcontent search" is broken, on Bolt 3.2 and Bolt 3.3.

To reproduce, add the following to a template of choice: 

```
        {% setcontent records = 'pages/search' where { filter: 'lorem' } %}
```

It'll throw an error: 

![screen shot 2017-06-14 at 17 31 18](https://user-images.githubusercontent.com/1833361/27140998-51884926-5127-11e7-89a0-1daf19016a0e.png)

Full stack trace on Bolt 3.3.0 b 10: 

![download](https://user-images.githubusercontent.com/1833361/27141040-69603eb4-5127-11e7-964d-b18de203975e.png)

@rossriley I've taken the liberty of assigning this one to you. :-)

**Comment by GawainLynch** [comment]
This is *very* new, it was introduced in https://github.com/bolt/bolt/commit/7020b1f4cec0122dcb75c2d568f553068d01526b on 8 Aug 2013.

**Comment by anketwokings** [comment]
Haha, you mean, the docs have been out of date since 2013?

**Comment by GawainLynch** [comment]
Haha … Nah, just that it is PHP "warning" that we never used to see before, as if you were lucky they would end up in your web server logs, or just disappear … in 3.2 we allow one to see them if debugging is turned on. i.e. that error on the exact same set up will _not_ appear with debugging turned of for production.

I just love how many of these have come out of the woodwork since we fixed error/exception handling.

**Comment by GawainLynch** [comment]
Just a note that I am removing "regression" from this issue, as it was introduced here https://github.com/bolt/bolt/commit/1016eb3009471dec6874123571f53165c6a0bdf9 on August 2nd, 2013.
