### ISSUE TITLE
[RFC] Extension Breaking Changes/ Major Version Changes Notices

### ISSUE THREAD

**Issue by cdowdy** [bolt/bolt#6794]
[RFC] Extension Breaking Changes Notices

Right now if an extension has a breaking change (v1 to v2) there is no notice nor is there an extension available if you hit the "Run update check" button to the right.  

The only way you'll know an extension has an update available with a major version change is to use the "manage" dropdown and select install different version. 

This keeps major version changes from installing and breaking extensions but it also keeps updated extensions from being easily found/noticed. Catch 22.  

I've mocked up some changes that could be made to the UI - the colors are just placeholders - that make it easier to tell if an extension has a major version increase.  

Since **most** extensions should be following semantic versioning if it's a major version change you'd apply a few visually distinct changes to the "installed" extensions panel. 

1) change the panel header color (info/warning/danger etc)
2) add a button next to mangage or somewhere else
3) this button opens a modal and details the changes.  
4) disable any updates not coming from the modal ¯\\_(ツ)_/¯

These visual cues will also need to be applied to any major version changes found in "run update check" list that is appened above the installed extensions.  

the panel changes:  
![bolt-ext-update-notices](https://user-images.githubusercontent.com/5969974/27920678-6c2614c0-6243-11e7-9749-d994227df22c.png)  

The modal for "see breaking changes" - wording could be more "accessible" to non developers to be honest.   
![bolt-extensions dev-bolt-extend laptop with hidpi screen](https://user-images.githubusercontent.com/5969974/27920724-88eb610a-6243-11e7-9e7b-3a76f4969495.png)

From the modal screenshot if you can't see there are two buttons. One says "don't update" and the other "I'm ready to update". 

If don't update is chosen then nothing happens and the extension stays at the current version. Update is chosen then the package is updated.  

I **think** forcing a major change update to go through a readme/changelog update modal would stop a lot of "your thing broke" requests but we all know people don't like to read haha. 

-------------------------  

These changes to the UI also bring up some pain points. If no changelog or release notes are found then nothing is rendered in the modal and the user will not know what changed. So there would be additional changes needed.  

__The Marketplace__  

Since the modal would show a changelog or release notes theese need to be supplied. If you look at the "top ten most downloaded" extensions only 4 have release notes. You get outside of the top 10-20 in extensions and 40% number falls a bunch more. Out of the top ten most downloaded themes only 1 has release notes.

The marketplace could refuse to notifiy or retreive and update from github if an extension is a major version change and keep it at it's latest tagged version if there are no release notes attached to the payload retrieved from Github.  

Since Github's api is being used, if the payload doesn't contain release notes or a changelog then an issue could be opened at the extension/themes repo when an update is triggered/found. 

-------------------------  

This isn't an easy problem to solve right off the bat as Gawain mentioned in slack. I know everyone is pressed on time so i wanted this to be here just for future refernce or a spring board!

**Comment by GawainLynch** [comment]
> Since Github's api is being used, if the payload doesn't contain release notes or a changelog then an issue could be opened at the extension/themes repo when an update is triggered/found.

Leaving [this here](https://developer.github.com/v3/repos/contents/) to remind myself of that point.

**Comment by GawainLynch** [comment]
Just adding a thought or two.

While I like the overall approach, and certainly nudged the right person to RFC that is for sure, one concern is that at a guess most people who are publishing extensions struggle with SemVer, let along even tagging releases … or recording change logs.

Not that I object to a little more "nudging" in the process myself, but I think the majority would suffer if we were too strict … my 5€ cents.

**Comment by GawainLynch** [comment]
Oh, and there are some things that can be done now if someone has the time … so anyone competent in Doctrine ORM, Silex 2 & Symfony 3 want to have a go at it, I'm happy to be the point-:princess:

**Comment by cdowdy** [comment]
I agree about semver and tagging but I figured I'd err on the side of developers knowing what their thing is doing over an end user.  

If it's not a major change then release notes are kind of a secondary nice to have and we wouldn't need to worry about breaking existing installs. 

If it is a major version bump and someone did it by accident then if a issue was automatically created they might be able to delete the latest tag and rerelease as an incremental update. 

This is though a giant bag of gotchas haha. And trying to find a balance between easy implementation, easy for developers and easy for regular users is haaaard. I'd rather it be a little harder for a dev to supply either a good readme, release notes or market description then leave a user in the dark

**Comment by lenvanessen** [comment]
I like the approach, but since a lot of developers dont properly tag releases or understanding semver as @gawainlynch said, i'd say the using the github api to open issues for extensions is a good starting point!

**Comment by cdowdy** [comment]
I'm here to "nudge" a little bit haha. 

There needs to be at least something to stop and not let extensions upgrade / update through minor BOLT version updates.   


Bolt recently has had a pattern of updating / changing / removing things between minor versions. For example https://github.com/bolt/bolt/pull/6156 between 3.2 and 3.3 the back end extension pages were at ``/bolt/extend/``  and changed to ``/bolt/extensions/``. This breaks a lot of extensions that use back end pages. Same thing happened in the 3.2.x series. The html sanitizer was changed in between what one would think would be a "patch" in semver. I know I wouldn't expect this breaking change in a minor version

**Comment by bobdenotter** [comment]
> The html sanitizer was changed in between what one would think would be a "patch" in semver. 

Hey, @cdowdy. What did we change in this, that you'd consider breaking?

**Comment by cdowdy** [comment]
hey @bob ! .. 

It was "breaking" because it worked before then you all actually implemented it the right way (aka fixed it) and then it no longer worked how it always worked. Where that was no one really knows. This all "worked" from at least around 3.2.4 prior.   

https://boltcms.slack.com/archives/C094GL7ME/p1497533590128403  
https://boltcms.slack.com/archives/C094GL7ME/p1497535563844370  for instance.  

if you add all the options as mentioned https://docs.bolt.cm/3.3/fields/html#options it works... until you add allowtwig: true and use an extension that works in the contenttype edit screen to the contenttype or have mixed content. like twig and HTML.  

at the try bolt site if you edit a contenttype with mixed html and twig contnet you'll escaped entities..  

![ct-edit](https://user-images.githubusercontent.com/5969974/29752613-94751f06-8b2f-11e7-8929-98d38e86c7c2.png)
![ct-edit-result](https://user-images.githubusercontent.com/5969974/29752614-9881330a-8b2f-11e7-9fa5-444014c5e755.png)

**Comment by GawainLynch** [comment]
> There needs to be at least something to stop and not let extensions upgrade / update through minor BOLT version updates.

There is, it is called Composer version constraints and is the responsibility of the extension author to define the Bolt version, and as a site implementer to define the constraints of the extension in return. It gets seriously complex past that.

> Bolt recently has had a pattern of updating / changing / removing things between minor versions.

![it ends tonight](https://user-images.githubusercontent.com/1427081/29756902-106f875e-8ba8-11e7-89d6-a2f1887a0d18.gif)

I've debated this back-and-forth with different team members, each of whom having a differing opinion, and to frame the **overall** point I keep arguing … _"Some breaks need to happen, most should **not** happen."_ But yeah, where it _should not happen_, I'm personally going to push back harder on things.

However … we do need help from people identifying some of these problems, and "only" a screenshot is not enough, a simple test case can make these things easier to track down.

Case in point, I manually had to type out your example, but it's 4 am and I am starting on my second :coffee: so about the limit of my brain power right now :rofl: 

OK, so If I save the following (complete) text into a HTML field's "source" frame:
```
<pre><code>
  <h1>Heading 1</h1>
  {{ twig }}
</code></pre>

<pre><code>
  &lt;h1&gt;Heading 1&lt;/h1&gt;
  &lbrace;&lbrace; twig &rbrace;&rbrace;
</code></pre>
```
… and hit "save", the end result is:
```
<pre>
<code>
  </code></pre>

<h1><code class="hljs">Heading 1</code></h1>

<p><code class="hljs">{{ twig }} </code></p>

<pre>
<code>
  &lt;h1&gt;Heading 1&lt;/h1&gt;
  &amp;lbrace;&amp;lbrace; twig &amp;rbrace;&amp;rbrace;
</code></pre>
```
A clear, and reproducible, issue in the tracker would have been addressed … long ago. :wink: 

P.S. There was a very grumpy :koala: is the development channel a couple of days ago about the sanitiser, said :koala: feels your pain

**Comment by GawainLynch** [comment]
For what it is worth, #6018 seems to be (partly) the culprit here

**Comment by cdowdy** [comment]
> There is, it is called Composer version constraints and is the responsibility of the extension author to define the Bolt version, and as a site implementer to define the constraints of the extension in return. It gets seriously complex past that. 

I brought up what I did because most extension authors probably assume bolt follows semantic versioning and a minor version update would do things in a backwards compatible way.  So we could follow the extension starters and use the "v3" constraint and not worry about anything breaking in. So going from 3.2 to 3.3 nothing should break that was used in 3.2. That's not the case. 


I should have brought this up (the sanitizer) in an issue tracker before you're right but I did multiple times in slack and it never went anywhere so I figured you all were swamped so I'll get to it later and each time no one could point to any changes done that would have produced this since it wasn't in any release notes or pulls

**Comment by GawainLynch** [comment]
> I brought up what I did because most extension authors probably assume bolt follows semantic versioning 

FWIW, we aim to follow SemVer and are working on improving where we fall down. 

A huge problem we ran into was internal pressure to release 3.0.0 months before it was ready. At least two core team members (and myself) nearly quit the project as a result. The fall out of the early release was that there was so much "in flux" and otherwise broken that some hard decisions had to be made, and there is still internal disagreement on whether such changes should have not just been new majors.

But … If we had gone for major releases, the Bolt version landscape would have ended up looking like:
- 3.1 === 4.0
- 3.2 === 5.0
- 3.3 === 6.0
- 3.4 === 6.1

What that would have meant in a practical sense is that every few months **every** extension would need to be updated to adjust SemVer constraints, every bit of our documentation would need review, etc. It's a hard balance to strike when people are just volunteering their time. That shouldn't give us an excuse, but it does point to where this is really a hard problem to solve.

The other massive problem we hit with SemVer is upstream libraries taking license on what qualifies as SemVer. A case-in-point here is Doctrine and the release of DBAL 2.6. Now it is fair to say that in a pure sense they followed SemVer in terms of their own library. But when you look at that as a consumer of the library that **must** support 5 different database platforms (Sqlite, PostgreSQL, MySQL & MariaDB 10.1 & MariaDB 10.2 — you want really messed up versioning, that :hankey: called MariaDB), across what is now 5 different PHP versions (5.5, 5.6, 7.0, 7.1, and 7.2) then you will see they completely and utterly screwed the proverbial pooch on semantic versioning … a take that even further, with their leadership team publicly — and childishly — ridiculing anyone who dares call that into question.

The end result of that is that I have a rather not-insignificant PR in queue at the moment that needs to go into a stable release version of Bolt to keep up support for 5 DB platforms & 5 PHP versions. But if a SemVer break occurs, it isn't Doctrine that will be called into question :wink: 

> I should have brought this up (the sanitizer) in an issue tracker before you're right but I did multiple times in slack 

I know you know, but I am including this here so that it is in broader public view. 

Slack & IRC are where people hang out and discuss. Issues are only actionable if there are in the issue tracker. We haven't gotten the bot's AI to a point where it can know what is a valid issue and open a ticket here yet … but given how self-opinionated that bot is, I am surprised it doesn't swear at me most mornings when I show up :rofl: 

Respect my friend, I appreciate your candid raising of these issues! Please know that we're all listening and trying hard to improve. Personally speaking it makes my heart sink to read this, and in turn more determined to make things better!

**Comment by cdowdy** [comment]
I know you all are 😀 and I know you all put a lot of work in which is why I "nudged" instead of YO GIMME THIS lol.  I get the semver constraints it places on you all and when someone upstream goes all will nilly (dbal etc) 

Don't get down (easy for me to say haha) I just wanted to bring it up which is why I added it to this rfc instead of taking on another issue you all already put in a butt-ton of work and there's only so many hours in a day... Speaking of which you go get some rest @GawainLynch haha

**Comment by GawainLynch** [comment]
![rest is for the weak](https://user-images.githubusercontent.com/1427081/29758451-fdb41fba-8bb3-11e7-8f1e-1d168f4e0274.jpg)
![caffeinated koalas](https://user-images.githubusercontent.com/1427081/29758454-ff6b2434-8bb3-11e7-8945-7df5f136355d.jpg)

**Comment by SahAssar** [comment]
I think this one should be kept open, Mr. Stale ;)

**Comment by robsonsobral** [comment]
Shouldn't this be kept open?

**Comment by bobdenotter** [comment]
@robsonsobral In an ideal world, yes. I think everybody agrees that there's an improvement to be made here. In practice though, turns out that none of us have been able to make the time to work on it. We're only fooling ourselves if we keep issues open that we're realistically not going to work on anytime soon. :-)

**Comment by GawainLynch** [comment]
Also, while this is a nice to have, it is something that should be done upstream in Composer.
