### ISSUE TITLE
[RFC] Cross site scripting vulnerability in SVG document

### ISSUE THREAD

**Issue by rixbeck** [bolt/bolt#6833]
https://vuldb.com/?id.103707

> A vulnerability classified as problematic has been found in Bolt CMS 3.2.14. This affects an unknown function of the component SVG Document Handler. The manipulation with an unknown input leads to a cross site scripting vulnerability (Stored)

**Comment by GawainLynch** [comment]
Actually this is the epitome of incompetence on the part of the moron that reported it.

This was reported to us, and we were able to demonstrate to the reporter that (by design) you needed a fully authenticated back-end session to do this, his demonstration even included the Symfony debug toolbar to prove how incompetent he was … He then desperately tried to find others without success.

NOTABUG

**Comment by bobdenotter** [comment]
The same applies to this one, by the way: https://vuldb.com/?id.103708

**Comment by lenvanessen** [comment]
Oh god... Can administrators add javascript to a template? Gonna have to put that one in to vuldb as well..

I

**Comment by rixbeck** [comment]
Cool... that was my morning birdy in my Bolt related mail packages... :D

**Comment by bobdenotter** [comment]
@lenvanessen I've even heard people whisper that you can write an extension for bolt **IN PHP**, and that it will execute arbitrary code. In PHP even, the unsafest of all languages!

**Comment by lenvanessen** [comment]
@bobdenotter PHP indeed is a toy language, accidently chosen to power 80% of the web. Let's create a new branch and start rewriting Bolt to Objective-c.

**Comment by rixbeck** [comment]
@lenvanessen, rather in oCaml please! BTW I haven't checked what is about and glad about you guys already did. Sorry... I'm hiding again... ;-)

**Comment by GawainLynch** [comment]
@rixbeck You're fine mate … This one just pissed me off as the little moron is, well a moron.

**Comment by SahAssar** [comment]
IMO this is something we should fix though. We deliberately block JS from being added to other backend html by an editor (for example pre/postfix html has it's html cleaned), why should we not do the same for SVG's? Authenticated or not, just presenting a image field to an editor should not allow that editor to run scripts on that backend page for any other editor/admin visiting that page.

**Comment by GawainLynch** [comment]
> In PHP even, the unsafest of all languages!

Funnily enough @bobdenotter, speaking of people's assumptions about language and safety, this came across my view recently: https://daniel.haxx.se/blog/2017/03/27/curl-is-c/ (hit tip to @jkazimir)

PHP & C (et al) have their problems, but the real problem is too often the programmer, not the language.

> IMO this is something we should fix though. We deliberately block JS from being added to other backend html by an editor (for example pre/postfix html has it's html cleaned), why should we not do the same for SVG's?

@SahAssar please see the first part of this comment as intended to be humours, and directed to you as a good and long time friend … "PRs welcome" :wink: 

On track though, sure there are some things we _could_ do, but it starts to head down the path of security though obscurity … and a host of related concepts. 

Anything containing data can be a potential risk, and GIF, JPEG, PNG, "pick a video format", etc all have had various weaknesses over time. More will appear given time.

Files on a shared host should **never** be considered safe. 

Files on a system you have full control over should **never** be considered safe without valid digest check sums generated in isolation and never stored attached to a networked device. 

Seriously, after years of forensic work in this area, I have seen so many of these different vectors exploited in way that just make you smile … Not because I take joy in someone's system being compromised, but because there are some seriously smart people out there that do bad things, and looking into their minds and applied approach is truly fascinating to me.

There is a point where risk needs to be properly assessed, and balanced measures taken. An personal example was years ago when a third party had built a highly secure data centre complete with a Faraday cage around the data storage … that myself and a colleague were able to just walk directly into, logged onto a console (that our organisation owned), and accessed protected data. All without being questioned!

Massive amounts of money spent to protect "secured" systems, and two guys in suits just walked into and out of without ever being questioned. :wink: 

All that said, as I mention in my first point, I am happy to review and merge a decent PR that adds a layer around some of this, but it will only serve to give people a false sense of security that will not protect them from themselves … let alone the _real_ risks.

**Comment by SahAssar** [comment]
@GawainLynch I'm sorry, but I don't see how talking about physical security ("just walked into and out") or bugs in file formats ("GIF, JPEG, PNG, etc all have had various weaknesses over time") have anything to do with wanting to restrict a specified part (JS) of a file format specification that we aim to support (SVG).

Besides saying "everything is vulnerable" I really don't get what your point is, and ridiculing people who bring (what they at least perceive to be) security issues seems like the worst possible way to deal with this.

**Comment by GawainLynch** [comment]
Running with the assumption that your comment is a polite request to expand and clarify my points … let me try to do that :wink: 

## PRs Welcome

I'll happily review and merge a PR to core that covers the following use-cases & requirements:

* Files uploaded via the back-end file manager: All support formats please, they're all vulnerable to similar exploits
* Files uploaded via FTP/SFTP/Rsync/etc (read: the most common way I have observed it done by people)
* Files located on a CDN or physical path that are served directly by the web server, not invoking PHP
* Files that fail a secure and modern checksum (that is generated and stored non-network attached) though whatever means of deployment
* Functionality that is in a separate service class
* Functionality that comes with unit test that extend `PHPUnit\Framework\TestCase` and cover the above use cases, reasonable input scenarios, and reasonable LoC count

## Security, Risk Mitigation & Grandstanding

A major problem I have here is that as you put it, "everything is vulnerable". Welcome to security. It isn't a matter of defining a perfect way of doing things … That **does not exist**, and anyone telling you otherwise **has not worked in the area**.

Further, I draw on physical security anecdotes to try to highlight that these assumptions matter. You can strip JavaScript from an SVG file on upload via the file manager, you can't do that if it is uploaded via FTP, on a CDN, or numerous of way of putting a file on a web site.

My anecdote was meant to highlight that you can literally spend millions of dollars on every other security measure, but you're likely to miss — and in this case **have** missed — the proverbial obvious, as we're all human and all make mistakes. There was even a security guard signing people in and out of said building … that didn't stop a combination of techniques getting us access … simply for shits and giggles, and professional curiosity.

You can still inject vulnerabilities into any file format, so an attacker is only going to keep modifying their scope and strategy until they get what they want … all they need to do in this case is convince you to neither check the downloaded file from a random un-trusted location (i.e. false sense of security that doesn't protect a person from themselves).

Security *is* about striking a reasonable balance based on risk … and given that we carry questionable libraries already … this whole thing is nothing more that Blog Post Security and grandstanding.

## Unreasonable Demands for People's Time

People continually making demands of the free time of a small group of developer in a rather entitled fashion is starting to get old, ridiculous, and currently has more than half of the core development team ready to quit this project.

As above, this whole thing is grandstanding. Initially on the part of the person reporting (will get to that below).

One of the reasons I abandoned Members was the level of incompetent stupidity in demands by a former friend and colleague, that just made a MITM vector (that still exists in BoltAuth) **more** exploitable … So maybe people should look at things like that first, and **fix them** before throwing demands around for people's free time that make little to no difference in practicality.

## Professional Incompetence

The person who reported this, was dealt with kindly and respectfully on several interactions. This is an important point!

However, this person not only belongs to a company that sells their services in this area, they themselves are also selling themselves as "experts" in the area. When their mistakes were pointed out, they still chose to escalate this. They violated ethical guidelines and only served to display professional incompetence … Something I have never been tolerant of.

Anyone pointing out potential security flaws will receive kind, respectful, and friendly greetings and interaction. That has always been the case.

However, if you want to take this to the next level, please be correct in your assertions and ethics. If you are, you will get a continuation of the respect, including thanks and recognition.

… if you act like a dick … you'll get what you're asking for.
