### ISSUE TITLE
[bug?] Publish time is one hour earlier than real time

### ISSUE THREAD

**Issue by gwbonline** [bolt/bolt#6881]
I use the newest Bolt release (3.3.0) and noticed that the publication time on the meta tab is one hour earlier than the real time. For example: when I edit a new entry at 3:00 PM, Bolt says the publication time is 2:00 PM. I have to change this manually. I checked my system time and everything is ok. Why does Bolt register the wrong time?

**Comment by jadwigo** [comment]
Have you checked if your server uses the correct timezone or DST setting?

**Comment by gwbonline** [comment]
How to do this? It's a German company that is also active in The Netherlands. It would be strange if the time zone is wrong.

**Comment by jadwigo** [comment]
It is not unusual for servers in Germany or the Netherlands to be set to UTC by default. And UTC is at least one timezone off.

How to check a timezone setting is a question for google, an example result would be https://www.tecmint.com/check-linux-timezone/

**Comment by gwbonline** [comment]
The server is set to Europa/Berlin timezone and that should be the right one. Even setting a timezone in .htacces didn't help Bolt to display the right time on the meta tab when creating a new entry.

**Comment by jadwigo** [comment]
The AM/PM stuff.. that's locale dependent.
See how to set the current locale here: https://docs.bolt.cm/3.3/other/locales

Please try to search online for your problem in stackoverflow and the documentation that is available for php, your webserver and the bolt cms _before_ raising the alarm about a bug. This way you will prevent a lot of people panicking about something that might be broken and which ends up being a false alarm. It also makes you look less like someone who just expects that the github issues are your personal helpdesk.

**Comment by gwbonline** [comment]
> It also makes you look less like someone who just expects that the github issues are your personal helpdesk.

This is totally not my intention. I'm a Bolt (and Pivot, PivotX) enthusiast for many years. I'm not an expert when it comes to programming, I do am curious about how it works and like to contribute by reporting issues and think about usability at the users side. Maybe some issues aren't issues like you developers are used to.

**Comment by GawainLynch** [comment]
Yeah, no stress. I am probably the least patient person in the community (it is rarely shows publicly) when it comes to these things, but some days we just get stressed out by pretty much anything :smile: 

Mainly what triggered @jadwigo on this one (and he's one of the patient ones) is just that the problem is actually a very basic PHP setting that a simple Google query will answer. But "simple" is subjective.

What I would recommend is grabbing a [Slack invite](https://slack.bolt.cm/) and calling out in the #general channel when you hit problems. There are nearly 1,000 users in there now, and depending on the time of day a number of "bar fly" people hanging around who love Bolt & the community and are happy to lend a hand, and help you get things sorted very quickly. 

Bug reports are **always** welcome, we do try to keep "questions" out of the issue tracker, as we take any "suggestion" of a bug really seriously, and jump straight into action! It can up the blood pressure some days when we get the notification of a new report with s thought of "Darn it! What did we get wrong this time?!?!" internal reaction :laughing: 

But yeah, come join us in Slack and have a chat with the broader community from around the world, it's gezellig, and even some days gezzelig.
