### ISSUE TITLE
[BUG] bolt admin interface listing shows current user as owner for null fields

### ISSUE THREAD

**Issue by jadwigo** [bolt/bolt#6904]
- Relevant Bolt Version: [ 3.3.1 ]

If you have entries in a content type that have a zero or null value as ownerid the bolt listing will show the username of the currently logged in user instead of something sensible like 'no owner' or 'unknown'.

So suppose you have the following content in the pages contenttype:
![image](https://user-images.githubusercontent.com/1488214/29372673-16e2970c-82ac-11e7-8f5c-a3646d4a8bd7.png)

The listing in the back-end will show the following if the user Lodewijk is logged in:

![image](https://user-images.githubusercontent.com/1488214/29372606-e9426994-82ab-11e7-98f1-e9a2c0752272.png)

I know it's a theoretical problem, but it will be weird for logged in editors who have no access to imported pages if the pages look as if they are the owner of content they have nothing to do with

**Comment by GawainLynch** [comment]
Haha … You've got my mind ticking over as to what is the title on the first one :wink:

**Comment by jadwigo** [comment]
You'll must have to cope with that 😎

**Comment by GawainLynch** [comment]
OK, this is actually fixed in 3.4 (beta soon!) and was introduced in https://github.com/bolt/bolt/commit/0b70a2204167847025a0dddfbfe3e76694d6fbcb back in April 2013.

As it is fixed in the upcoming stable, is a problem in legacy that has been there for every stable Bolt release, and would probably break things in 3.3, I'm going to call it a day on this one :wink:
