### ISSUE TITLE
Templateselect Field silent fails when the selected template has an error

### ISSUE THREAD

**Issue by Rzial** [bolt/bolt#7047]
Details
-------

 - Relevant Bolt Version: 3.3.6
 - Install type: Composer install
 - PHP version: 7.0
 - Used web server: Apache | Nginx

Reproduction
------------

[Test Case](https://github.com/Rzial/bolt-template-silent-fail)

You can notice there are 2 pages on the backoffice (sqlite database commited). One renders the 'Template' tab, the other don't.

### Bug summary

If the selected template has an error (for example, try to extends an unexisting template), the backoffice silently fails.

### Expected result

I see two viable solutions:

- Flash Error / Warning when the template with an error is selected.
- Don't check the template and let the error pass until it gets rendered.

**Comment by GawainLynch** [comment]
So it turns out I had forgotten why this was such a PITA … This comes down to the way Twig works.

We need to [load the template](https://github.com/bolt/bolt/blob/3.3/src/Storage/Field/Type/TemplateFieldsType.php#L134) into the Entity that it is defined for. The template chooser will correctly return an array of templates that might be the one needed. `resolveTemplate()` calls [`loadTemplate()`](https://github.com/twigphp/Twig/blob/1.x/lib/Twig/Environment.php#L587) which then tried to instantiate the [compiled template](https://github.com/twigphp/Twig/blob/1.x/lib/Twig/Environment.php#L487) but throws a generic `\Twig_Error_Loader` exception that `resolveTemplate()` ignores, as that is its job.

We could certainly add the tab at this point, but we have no *valid* knowledge of the fields, and no way to save them into the entity.
