### ISSUE TITLE
"Manage" box on /bolt/bolt/extensions always pull-down

### ISSUE THREAD

**Issue by leggewie** [bolt/bolt#7075]
bolt 3.3.6 with FF 56 on Ubuntu Trusty

Clicking on the "Manage" pop-up of /bolt/bolt/extensions results in the respective box always being pulled down.  The "bug" is that it should pull-up when this happens close to the bottom of the screen to avoid the pop-up box ending up invisible.

My apologies for the poor choice of wording.  I hope the screenshot makes my explanations clearer. 

![manage](https://user-images.githubusercontent.com/2387015/31532628-fe19bca8-b020-11e7-8572-322cb66dcead.png)

**Comment by bobdenotter** [comment]
This is something that we can't easily fix: Stupid Bootstrap 3 doesn't have an automatic toggle for it. So, for now we just have to scroll down a bit after opening it.. 

Hopefully when we revamp the backend on Bootstrap 4 for Bolt 4, it'll work better. I'll close this issue now. Not because I don't think it has merit, but more because we can't really fix it for now. :-)
