### ISSUE TITLE
[BUG] Image field cannot be edited manually

### ISSUE THREAD

**Issue by svivian** [bolt/bolt#7256]
If you have an image field on a content type, you cannot type in a path to an image, or edit the path of an image already selected.

Details
-------

 - Relevant Bolt Version: 3.4.3
 - Install type: Composer
 - PHP version: 7.1
 - Used web server: Apache
 - For UX/UI issues: Chrome 63.0.3239.84

### Steps to reproduce

1. Use a ContentType with an image field, ie `type: image`
2. Select an image for the field and Save.
3. Edit the image field manually, e.g. change the image (to another one that exists)
4. Save or just click outside the field.

### Expected result

The new image to be saved.

### Actual result

It's not saved. When you click outside the field it reverts to the original value. If you clicked Save or pressed enter the field doesn't change, but the new value is still not saved.

I don't know what the intended behaviour is, but if we're not supposed to edit the field manually then it should not allow editing at all rather than allowing it and silently ignoring. However, I see no reason why we shouldn't edit the field manually, very often that is much quicker than going through the 'select from server' popup.

**Comment by bobdenotter** [comment]
Hi @svivian,

The behaviour is a bit quirky, but not _really_ broken, I think. The quirky part is that you need to select an item from the autocomplete in order to make it "stick". Like this: 

![screen shot 2017-12-31 at 09 22 41](https://user-images.githubusercontent.com/1833361/34460364-30c19bca-ee0c-11e7-9077-771c802177b3.png)
