### ISSUE TITLE
AND lookups don't work

### ISSUE THREAD

**Issue by igoradamenko** [bolt/bolt#7276]
Hi!

It was impossible to use AND on relationship/join searches, e.g.:

```
setcontent records = 'items' where { 'tags': 'book && shelf' }
```

But there is a PR with fix this problem: #6401. The problem was fixed in v3.3. But I've installed 3.4.2 some days ago and search on tags with AND does not work here.

And when I use `printquery` param I see queries like this:

```
SELECT bolt_entries.* FROM bolt_entries WHERE (`id` IN (SELECT content_id AS id FROM bolt_taxonomy where `bolt_taxonomy`.`taxonomytype` = 'tags' AND ( ( `bolt_taxonomy`.`slug` = 'evolyuciya' AND `bolt_taxonomy`.`slug` = 'postnauka' ) OR ( `bolt_taxonomy`.`name` = 'evolyuciya' AND `bolt_taxonomy`.`name` = 'postnauka' ) ) AND `bolt_taxonomy`.`contenttype` = 'entries') AND `bolt_entries`.`status` = 'published') ORDER BY `id` DESC LIMIT 9999
```

Was it fixed or not? Am I doing something wrong?

Details
-------

 - Relevant Bolt Version: 3.4.2
 - Install type: Composer install
 - PHP version: 5.6.30
 - Used web server: Apache 2.4.18

**Comment by bobdenotter** [comment]
Hi @igoradamenko, 

The difference here is that it was fixed in the "new" storage layer, and not in "legacy". We're still making the full cutover, so edge cases like this might show up. 

In Bolt 3.4 the _backend_ (as in "in PHP") uses the new one, but the _frontend_ (as in "in twig") uses the legacy one by default. 

You might try switching near the bottom of config.yml, but beware that you might bump into other quirks: 

```yaml
compatibility:
    # Set to 'false' to enable using a newer version of the setcontent parser.
    setcontent_legacy: false

```

**Comment by igoradamenko** [comment]
@bobdenotter, I've tried this feature, it didn't work for me. So I'm going to wait for next release with it. 

Thanks!
