### ISSUE TITLE
[BUG] printquery won´t work with search and where filter

### ISSUE THREAD

**Issue by develth** [bolt/bolt#7324]
Hi,

i´m using 
https://docs.bolt.cm/3.4/templating/content-search#setcontent-search
to get some content and wanted to debug the Query, because i get no results on taxonmies, but printquery won´t output anything.

Details
-------

 - Relevant Bolt Version: [3.4.7 ]
 - Install type: [ Composer install ]
 - PHP version: [ 5.6 ]
 - Used web server: [ Apache  ] version [ 2.4.10 ]

Reproduction
------------

    {% setcontent results = 'pages/search' where { filter: 'Test' } printquery %}

### Bug summary

Query won´t be printed

### Specifics

No output on all browsers and sytems, even after cache clear

### Steps to reproduce

Use the setcontent call describe in Reproduction

### Expected result

The printed Query 

### Actual result

No printed Query

**Comment by rossriley** [comment]
Looks like this is another bug since the beginning of time that has slipped through the net. 

Printquery is only run on a normal getContent query and not on a searchContent query.

For reference this is fixed in the new storage layer but it probably should be done here too since it's a relatively simple fix.
