### ISSUE TITLE
Management of db columns for custom field types set's wrong NOT NULL option

### ISSUE THREAD

**Issue by ToBe998** [bolt/bolt#7389]
If you create a custom field class, there is some inconsistencies and handling of storage options, that create exceptions when doing a db check/update and when saving values in these fields:

**Documentation**
The documentation for 3.4 still suggests to set the `getStorageOptions()` method. The method is marked as deprecated and will produce errors, when used as shown in the docs.
```
    public function getStorageOptions()
    {
        return [
          'default' => ''
        ];
    }
```

Suggested Solution: Remove the method from documentation

**Setting empty default**
If you use the method as shown above with a field of storage type `text`, the db update will fail for this column. @twwd did some research here:
Doctrine sets the default value to an empty string and therefore sets the column to NOT NULL.
In MySQL, text types cannot have a default value and therefore the default value of an empty string is ignored.

Suggested Solution: Remove the method from documentation or give advice on affected storage types.

**Columns are set to NOT NULL**
If you remove the crashing method `getStorageOptions()` completely, the db update will work again, but doctrine will set the field to `NOT NULL`. This will create fatal exceptions when you try to save a record with an empty field of this type, making it in essence a dangerous mandatory field.

`SQLSTATE[23000]: Integrity constraint violation: 1048 Column ‘mycustomfield’ cannot be null`

Suggested Solution: I could not find a way to make the column `ALLOW NULL`. Even manually setting it in SQL will trigger Bolt's db check/update and remove it again. Strangely, Bolt's own fields with exactly identical contents and types do not have this error and allow null.

Details
-------

 - Relevant Bolt Version: 3.4.7
 - Install type: Composer install
 - PHP version: 5.6
 - Used web server: Apache 2.4
- MySQL: mysqld 10.1.26-MariaD

Reproduction
------------

Create a custom field with this content:
```
<?php
namespace Bolt\Extension\My\Custom\Field;
use Bolt\Storage\Field\Type\FieldTypeBase;
use Doctrine\DBAL\Types\Type;
class CustomField extends FieldTypeBase{
    public function getName(){
        return 'customfield';
    }

    public function getTemplate(){
        return 'customfield.twig';
    }

    public function getStorageType(){
        return Type::getType('text');
    }
}

```

**The NULL/NOT NULL thing**
 - Do a DB check/update
 - the column in your MySQL db now has "NOT NULL"
 - Manually set the column to "ALLOW NULL"
 - Repeat ... it get's removed again

**The db update error**
 - Add below storage options method as specified in docs to the custom class
 - Do a DB check/update
 - It did not update
```
    public function getStorageOptions()
    {
        return [
          'default' => ''
        ];
    }
```

**Comment by rossriley** [comment]
can you try in the getStorageOptions returning:

```
['notnull' => false]
```

As far as i can see this gets passed to the schema creator, you can possibly add default => '' but if you allow null values hopefully that won't be necessary.

**Comment by ToBe998** [comment]
The fix from @rossriley solves the problem.
As the documentation still shows the problematic method, i would like to keep this bug open. Also it's unclear how to solve this issue in the future as the getStorageOptions method is marked deprecated.

**Comment by ToBe998** [comment]
Any news on how to resolve this in the docs and when deprecation hits?

**Comment by rossriley** [comment]
OK, been thinking about this one a bit. I think the crux of this is that we probably won't deprecate the `getStorageOptions()`at least until we've got something viable to replace it with.

The overall goal for Bolt 4.0 and beyond is to try and reduce the amount of work that each field has to do, because there's a danger of them turning into the mini-God objects of Bolt since fields like blocks, repeaters and relations etc end up doing a lot of work at each stage of the lifecycle.

That being said, it's essential that a field is able to specify whether it is written to the DB and what happens when it needs to be so when we finally get around to deprecating the current setup it will probably be enhancing the current `getStorageType()` to be able to return a more descriptive type than what we currently do via mapping directly to DBAL Types.

So for now consider `getStorageOptions()` fine to use until we announce that there's a new way to start using.
