### ISSUE TITLE
Taxonomies that start with digits, admin interface

### ISSUE THREAD

**Issue by nealmarques** [bolt/bolt#7426]
If taxonomies are created that start with numbers, the admin interface does not automatically select them from the dropdown list.  Re saving the record will result in loss of taxonomy.

 

Details
-------

 - Relevant Bolt Version: [3.4]
 - Install type: [ Zip/tarball install  ]
 - PHP version: [ 7.0  ]
 - Used web server: [ Apache ] version [ 2 ]
 - For UX/UI issues: [ Chrome  65.0.3325.181 ]

Reproduction
------------

1. Create the Taxonomy:

years:
    slug: years
    singular_slug: year
    behaves_like: grouping
    options: [ 2017, 2018]

2. Assign it to a content type.

3. Save
4. Go to Listing page
5. Select Record again
6. Click on Taxonomy 
7. Or resave record to see the taxonomy type vanish from record.

**Comment by bobdenotter** [comment]
This is an issue with PHP not dealing to well with numerical keys. This is a duplicate of #7411, so i'll close this to keep the list tidy.

**Comment by Boorj** [comment]
@bobdenotter i disagree.
 In #7411 the problem is not in PHP, it's in incorrect usage. And also in that issue problem is in `Form\Resolver\Choice.php`, and it doesn't relate to taxonimies. It **looks like** this issue, but it **doesn't equal**. See more details in that issue.
So, i suppose, this deserves to be reopen, sorry.. 😊  😢
