### ISSUE TITLE
Checkbox field improvement

### ISSUE THREAD

**Issue by eduardomart** [bolt/bolt#7467]
Currently checkbox fields make no use of the `variant: inline` property
If we were to, we should display the checkbox on the left side of the label
This would allow for longer strings in the label, at the moment it only takes a couple of words before the label gets squished on the left side of the checkbox.

![checkbox_field](https://user-images.githubusercontent.com/1833020/39601111-c508c752-4ed5-11e8-9902-5360054c4e55.png)

If devs are ok with this proposed change I wouldn't mind trying to submit a PR.

**Comment by ozzywalsh** [comment]
I think the label should always be right of the control, as you've suggested.

I did a bit of research and this tends to be the [predominant thinking](https://ux.stackexchange.com/questions/5080/should-checkbox-labels-be-to-the-right-or-the-left)

**Comment by bobdenotter** [comment]
Sounds good to me! A PR would be great, @eduardomart 👍

**Comment by Boorj** [comment]
Please, make this feature optional. That will definitely break standard behavior. 
If all labels are placed in one column, and one small checkbox will be at left, some not experienced users can miss that.

If you put checkbox at left on this draft (taken from #6229 ) :
![image](https://user-images.githubusercontent.com/2145313/40788975-873160c2-651b-11e8-80fc-b560a1feb79b.png)
this will break the design.

### suggestions

1. you could do `position: left`

2. add special "control comment" property, close sense to `postfix` / `prefix`. Which will add additional comment to checkbox (i prefer this option).
It could be useful in many cases, for example if you want to enable/disable header, and need additional explanation for not experienced users:

```yml
# contenttypes.yml ...
fields:
    header:
        type: checkbox
        variant: inline-left
        label: Page Header
        control_label:  Show header
```

could produce: 

> **Page Header**
    [  ] Show header on page

Because sometimes people don't understand well  - what will happen, if they select checkbox.

**Comment by SvanteRichter** [comment]
@Boorj This wouldn't break anything. It just adds functionality that is currently not present, the default remains the same.

**Comment by Boorj** [comment]
1
---

@SahAssar that was a kind of dialog:

> I think the label should **always** be right of the control

> Please, make this feature optional

Will be it marked with `variant-left` ? 

2
---
Btw i suggested extra field, which adds comment to checkbox. What do ya thing about it?

**Comment by eduardomart** [comment]
@Boorj 
Did you read the original message? the idea is to simply use the `variant: inline` property that is currently not being used for checkboxes. This would keep the available options in field types consistent.

Adding comments is already possible with `prefix` and `postfix`

**Comment by Boorj** [comment]
2 - @eduardomart  sometimes you need to explain what will happen exactly, if box is chosen. And yes, i'm using postfix for that. And sometimes it goes nicer, when it goes like `[ ] enable some stuff`

If that doesn't break typical behaviour and is optional - i'm ok with that.

**Comment by eduardomart** [comment]
I honestly don't understand what you're talking about, in your example:
`[ ] enable some stuff`

"enable some stuff" is the `label`, nothing is changing there.

**Comment by GwendolenLynch** [comment]
What @eduardomart said.

This doesn't currently use Symfony Forms, but in v4 it will. That is not negotiable. At that point, it is either an upstream improvement or an implementation detail.

**Comment by Boorj** [comment]
whats up ?

**Comment by sbonardt** [comment]
#7610

**Comment by Boorj** [comment]
nonono
