### ISSUE TITLE
Generate slug (/async/makeuri)

### ISSUE THREAD

**Issue by psanchezg** [bolt/bolt#7695]
When you click "Generate slug" the method "/async/makeuri" always returns an empty response.

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 3.6.0
| Install type                   |  Composer install
| PHP version                 | 7.0 / 7.1
| Web server                  | Apache / Nginx / Built-in

Reproduction
------------

Edit a content and click that option.

### Bug summary

The issue doesn't exist in 3.5.7

### Specifics

The problem is in the function makeUri from Controller/Async/General.php
Using the old 3.5.7 function works well

### Expected result

Slug uri

### Actual result

Empty response ("")

**Comment by bobdenotter** [comment]
Hi, @psanchezg. I'm not able to reproduce this just yet.. In my attempts, it works as it should.

Have you got more details? Errors in the browser's developer tool, or elsewhere? Screenshots?

**Comment by psanchezg** [comment]
Hi @bobdenotter. Finally I found how to reproduce this issue in a new bolt installation. Just change 'title' by 'titulo' (spanish translation) in pages contenttype, and change use in slug by 'titulo'.

You see nothing except the slug field empty (no errors in console)

**Comment by Thibault-MTZ** [comment]
Hello !
**To begin, thank you all for this CMS ! Bolt is very cool ;)**

(sorry I'm french and my english is not very good)

So I have the same problem with SLUG.
When it comes to using a slug from another field than "title" then it does not work.

I have the same problem on 3.6.0 and 3.6.1

If on the other hand we use "title" it works and the field "slug" is filled again.
The URL called async is async/makeuri?Title=TitreEnCours&contenttypeslug=contentType&id=& slugfield=slug&fulluri=true

Is it possible to know which bowl control handles this response? (Because I think this is the process that always gets the "title" field instead of the field set in "uses"

This problème is identical in case of multi "slug"

I remain available if you have questions.

**Comment by bobdenotter** [comment]
@psanchezg @mt24 I can reproduce the issue, thanks! 

Expect a fix, and a subsequent Bolt 3.6.2 soon. (Can't promise it'll be tomorrow, but it'll be before the weekend)

**Comment by Thibault-MTZ** [comment]
Thx @bobdenotter !
To improve my knowledge on "bolt" I will follow the resolution of this problem.
