### ISSUE TITLE
[3.6] Config.yml with environment variables are not parsed before Extensions boot time

### ISSUE THREAD

**Issue by lardyNiji** [bolt/bolt#7704]
There is a problem with boot time order for Services Providers, indeed ExtensionServiceProvider is initialized before ConfigServiceProvider then when an extension need some config from Bolt that embed environment variables, those config have not yet been replaced.

I've the case with animal/translate extension that init database connection at extension boot time.

I’ve tried to move
```
// Extension 2nd phase: Run extension's boot code.
$this->register(new Provider\ExtensionServiceProvider(false));
```
after the initConfig() Phase in the vendor/bolt/bolt/src/Application.php and that seems to work for me, but perhaps it’s not as simple as that because changing bootstrap order can have consequences

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 3.6
| Install type                   | Composer install
| BC Break                     | yes
| PHP version                 | 7.2
| Web server                  | Nginx
| For UX/UI issues        | Browser name and version

**Comment by rossriley** [comment]
There's a little helper that we use elsewhere in the Bolt codebase that might be useful for you here. For instance in storage:

```
        $app['storage.config.taxonomy'] = $app->share(
            function ($app) {
                return new ConfigurationValueProxy($app['config'], 'taxonomy');
            }
        );
```

So instead of initialising the config at register time you store a link to the future value within config which allows you to still use the computed value at boot time. This is also important if you want to use config stored in environment variables / other extensions which are also unavailable until boot.
