### ISSUE TITLE
Error after clearing cache : cache/production/data is not writable

### ISSUE THREAD

**Issue by Boorj** [bolt/bolt#7728]
This issue looks close to #6562, but i haven't found more relevant issues.

#### Problem is: 
1. clear cache with `php vendor/bolt/bolt/app/nut cache:clear`
2. reload webpage
3. it shows "Whoops...":
  > logger.system.CRITICAL: The directory "/var/www/html/yoursite/app/vars/cache/production/data" is not writable. {"event":"exception","exception":"[object] (InvalidArgumentException(code: 0): The directory \"/var/www/html/yoursite/app/vars/cache/production/data\" is not writable. at /var/www/html/yoursite/vendor/doctrine/cache/lib/Doctrine/Common/Cache/FileCache.php:92)"}

4. i have to delete production folder in cache.

Problem appeared for a long time for several versions of bolt.

Is there a cure for that?

**Comment by rossriley** [comment]
Long running issue here, there is a workaround but it depends on using access control features rather than standard permissions.

The cause is that most people use a separate user to run `nut` commands than the user that runs the web server, and when a user creates a new directory the system default `umask` normally means that other users cannot write to it.

The workaround is to add your site user (the one that runs nut commands from ssh) to the web server group, (normally `www-data`) and allow the entire group read-write access to the `app/cache` directory.

Example command here:

`setfacl -R -m group:www-data:rw app/cache`

**Comment by JarJak** [comment]
My workaround if you don't have setfacl:
```
mkdir -p var/cache
chmod -R a+rw var/cache
rm -rf var/cache/*
mkdir -p var/cache/production/data
app/nut cache:clear
chmod -R a+rw var/cache
```
