### ISSUE TITLE
Using `class: Foo\Bar` doesn't work in 3.6

### ISSUE THREAD

**Issue by bobdenotter** [bolt/bolt#7764]
You can define a `class` to use in contenttypes.yml, to override the Class used for a ContentType. Using `class: \Bundle\Site\MyContent`, you'd have:

```php
<?php

namespace Bundle\Site;

class MyContent extends \Bolt\Legacy\Content
{

}
```

And that should work. However, this is broken in 3.6: 

![Schermafbeelding 2019-03-26 om 14 32 58](https://user-images.githubusercontent.com/1833361/55001046-12e26a00-4fd4-11e9-937b-636b0437b2e5.png)

This is because `src/Legacy/Content.php` expects a `$app` when contructed:

```php
    public function __construct(Silex\Application $app, $contenttype = '', $values = [], $isRootType = true)
    {
        $this->app = $app;
        $this->isRootType = $isRootType;

```

While the builder in `src/Storage/Entity/Builder.php` doesn't pass it in: 

```php
    public function getEntity($entity = null)
    {
        if ($entity === null) {
            $class = $this->class;
            $entity = new $class();
        }
```

Either we change `Content.php` to magically conjure an `$app` if none is given, or we change `getEntity` to pass in the `$app`. Neither is very elegant, but we should fix it for backwards compatibility.

**Comment by StevendeVries** [comment]
On the frontend I resolved the issue by using a custom Builder which adds `$app` to the exact class (using a classname comparison, nothing fancy but it works).
However the Backend (`/bolt`) still fails due to the fact the `\Bolt\Storage\EntityManager::getEntityBuilder` creates a new Instance instead of using the one provided from $app
![Screenshot 2019-04-03 at 11 39 20](https://user-images.githubusercontent.com/6906996/55469154-28274c00-5605-11e9-88c3-0efe6c91987d.png)

**Comment by JarJak** [comment]
Shouldn't there be separate builder for legacy entities?
