### ISSUE TITLE
Laravel Integration

### ISSUE THREAD

**Issue by omzy** [bolt/bolt#7779]
I am trying to integrate Bolt with an existing Laravel 5.8 application. However I have failed at the first hurdle. I tried doing `composer require bolt/bolt ^3.6` and got this error:

![image](https://user-images.githubusercontent.com/8927010/59358220-16a8a180-8d24-11e9-8a7f-3dc30291a8b5.png)

So firstly, how do I overcome this error?

And secondly, what is the correct way of integrating Bolt with Laravel?

**Comment by bobdenotter** [comment]
> what is the correct way of integrating Bolt with Laravel

I don't think that's possible. Bolt is a Silex app, with a bunch of Symfony 2.8 components. I doubt you'll get that working in a Laravel stack.

**Comment by omzy** [comment]
Thanks for your reply @bobdenotter 

So the idea is, I want to use Bolt as a CMS for an existing Laravel application. I want the user to be able to manage content within Bolt and then I will use the Bolt hooks to fetch content and display it within the Laravel application.

Is this not possible at all?

**Comment by bobdenotter** [comment]
@omzy83 Depending on the timeline (days? weeks? a few months?) it might be worthwhile to check Bolt 4, which is "almost beta", and perhaps use that decoupled, just to pull in the content as JSON in your app.. 
Or, similarly, use Bolt 3 with the JSON-API extension?

**Comment by rossriley** [comment]
@omzy83 there's probably just some mixed dependency requirements between Bolt and Laravel here, the one in the error is SwiftMailer since Laravel requires a 6.x version and Bolt requires a 5.x version.

So, the chances are that you might be able to get away with this inconsistency, it all depends on whether Bolt uses anything in Swiftmailer 5 that is broken in 6, you can at least test this by adding a replacement in your composer.json to do this you need two steps:

1. Require swiftmailer in your application explicitly, eg run `composer require swiftmailer/swiftmailer ^6.0`
2. Tell composer that you're looking after swiftmailer so the Bolt install won't fail. 

```
"replace": {
    "swiftmailer/swiftmailer": "*"
}
```

After that you can try installing Bolt again normally, `composer require bolt/bolt ^3.6` and hopefully it won't fail because of the Swiftmailer conflict.
