### ISSUE TITLE
Relative to absolute URLs in feed

### ISSUE THREAD

**Issue by hansfn** [bolt/bolt#78]
I don't think this is currently done. (In PivotX we used the function relativeToAbsoluteURLS.) The feed should contain URLs with hostname (and protocol) to be make it 100% portable.

PS! I just added $paths['hosturl'] which should be used.

**Comment by givinalis** [comment]
hey, how do I get image src links in description to have absolute urls rather than relative? please help

**Comment by SahAssar** [comment]
Hey @givinalis, I'm not really sure what you mean, but if you either open a new issue, join us in the IRC channel or ask it on stackoverflow with the tag #boltcms I'm sure we can help you. This issue has been closed since over two years ago, so it might not be the best place to ask.

Looking forward to helping you out :)

**Comment by hansfn** [comment]
> hey, how do I get image src links in description to have absolute urls rather than relative?

 @givinalis: At least provide an example of you get (or link to a feed that has the problem) and what you expect. IMHO: Don't create a new issue before we see what the problem is.
