### ISSUE TITLE
Allow a blank password for the database

### ISSUE THREAD

**Issue by WilliamVercken** [bolt/bolt#863]
Hi !

I really want to test this CMS, but I can't install it without creating a new user for my database, and I don't want to (local server) or I can't (distant server).
Can you just allow us to install it without forcing us to do that ?

A comment from this issue https://github.com/bolt/bolt/issues/184#issuecomment-32758135 : 

<blockquote>Forcing the user/dev to have a password set is really not a good idea. Many many developers have mysql locally installed to debug/test etc. They usually don't have a password set because the server is bound to loopback interface or hostname is restricted to "localhost" and therefore its useless to set a password. Also some cloud provider does not set a mysql password but limit the access on TCP level, which is usually more secure. (which is sometimes needed to automatically boot new load-balancer slave instances while not saving the password in the repository/image)

MySQL and PostgreSQL do support also more authentication methods than the good old password login. Restricting that isn't a good idea IMHO.</blockquote>

Thanks a lot ! I'm eager to test it !! :)

**Comment by humaxi** [comment]
To everyone that says that you should just use Sqlite, are you stupid? What if you are using someone else's database. What if you do not want a password for whatever reason on your root. There is not a single PHP CMS that forces you to set a MySQL password... How do you remove this "security" because otherwise I cannot use this cms.  There is no point to this besides annoyance, what do you think about a firewall? I think everyone has a firewall on their local environment.. MySQL and Apache are blocked from external reach. So setting a password is not needed. Developers should be able to decide for themselves.  Otherwise, just make this a paid CMS and delete it from github.

**Comment by bobdenotter** [comment]
> Otherwise, just make this a paid CMS and delete it from github.

Pay me, and i'll "fix" it for you. 

(I happened to notice your comment on https://github.com/ghosh/Micromodal/issues/209, and let me tell you: You really have a misconception about what you're entitled to from Open source developers. Please keep in mind that we're people too.)

**Comment by humaxi** [comment]
Meh, I'm not entitled to anything, but since this is open source I can also give my opinion on things and I will if you make something bad imo.

**Comment by cMurschall** [comment]
The beauty of open source is that you can 'fix' it easily yourself. Have a look at the change # 5120a7b and you can figure out what to do.
For the majority of the users, I agree with @bobdenotter that it is good as it is.

**Comment by SvanteRichter** [comment]
@vacoup95 You said to implement your changes or "make this a paid CMS and delete it from github", That is not just giving an opinion, that is making a demand (whether you meant it as that or not).

Regarding the question at hand if you really think that a firewall is a substitute for proper access control then you really don't get how security works. If you asked for a development mode that didn't have these restrictions that is one thing, but clearly that isn't it since in a development mode you'd control the database enough to create a user, making the point moot.

Replying to a five year old thread with a hostile demand is simply not how you interact with a community in a productive manner.

**Comment by humaxi** [comment]
> @vacoup95 You said to implement your changes or "make this a paid CMS and delete it from github", That is not just giving an opinion, that is making a demand (whether you meant it as that or not).
> 
> Regarding the question at hand if you really think that a firewall is a substitute for proper access control then you really don't get how security works. If you asked for a development mode that didn't have these restrictions that is one thing, but clearly that isn't it since in a development mode you'd control the database enough to create a user, making the point moot.
> 
> Replying to a five year old thread with a hostile demand is simply not how you interact with a community in a productive manner.

Guess what, I don't care if it's productive or not. This is why bolt will never be successful, it's just crap only idiots wants to deal with this. It has literally nothing to do with security, there's not a single good CMS in the world that has this "feature".

@SahAssar Give me one good reason why a firewall is not enough of a security feature. Why does bolt decide about how you must use other software? MySQL does not force you to set a password.
