### ISSUE TITLE
Allow Tags with spaces in them

### ISSUE THREAD

**Issue by sbonardt** [bolt/bolt#868]
When using a taxonomy of type 'tags' it is not possible to add tags with a space in it, e.g. 'Den Haag' or 'Belgian Beers'

The tagging function splits it automatically into two tags. Could tags be separated by comma?; or allow creation of tags with space be between quotes like "tags with spaces"?

**Comment by XusBadia** [comment]
Hope this doesn't get forgotten. ;) I'm trying to get tags with spaces and copy and paste sometimes works, but sometimes doesn't, which is a bit frustrating.

**Comment by bobdenotter** [comment]
I - personally - don't give a rat's ass about this. This will either get implemented because a (paying) client needs it, or somebody from the community steps up, and makes a Pull Request for it. \*hint\* \*hint\*

**Comment by leup** [comment]
You could say that this is not a priority and so that you don't - personally - intend to implement it but that you don't give a rat's ass is not a valid argument. I had to go with a different CMS because of that issue and that was unfortunate because I really wanted to give Bolt a chance "in production". That did not happen. It was too much a job at the time to give a go to Bolt over another CMS. As you stated in the last development roadmap that you want Bolt to be as user friendly as possible, this is an issue that is definitely not user friendly (to my opinion). My comment here has nothing to do with the paying customer or community involvement part, I do understand your comment on that. Good luck with the hint ;)

**Comment by XusBadia** [comment]
I understand your position and that there are more important issues to tackle right now, but I still think this is not a niche feature, as well as the Capital letters for tags.

Hope someone follows the *hint*, though!

**Comment by bobdenotter** [comment]
@leup >  I had to go with a different CMS because of that issue and that was unfortunate because I really wanted to give Bolt a chance "in production".

Sorry, but I don't buy that. You're telling me that Bolt fit _all_ your needs perfectly, and you decided _not_ to use it because you couldn't use spaces in tags? That's blackmail, you know it, and I will have none of it. 

> As you stated in the last development roadmap that you want Bolt to be as user friendly as possible, this is an issue that is definitely not user friendly (to my opinion).

I do, but our collective time as developers is unfortunately limited. We choose to spend this time on stability fixes for 2.2, and adding new (often requested) features like inline editing and template-specific fields. You're absolutely right that there's room for improvement, but I'm sure the things we _did_ work on are more important for a lot of people. 

@XusBadia 

> Hope someone follows the hint, though!

So do I. Just to re-iterate, we'll gladly accept code-contributions for this. Including helping out with feedback and troubleshooting if needed.

**Comment by leup** [comment]
@bobdenotter 
Blackmail ? Man you should relax. At the time (don't remember exactly but I think it was still the version 2 in beta) Bolt has other flaws, but some that we could work around, some that we could fix with module(s). This one was not fixable (space in tags but also special characters like #, see my other comment above) without a good amount of job. And indeed, between two CMS we had to choose. We had time and budget constraints too and so we choose the other one (which has his flaws too but that we could all work around or fix). We have used Bolt for other projects since then, projects with other requirements and constraints. We did not stay on "Hou Bolt don't do that, we won't use it never again ! Bah !". So please don't take my comment the wrong way. I just say that this is a real issue (I repeat: in my opinion), I do hope that this we'll be fixed someday. Not by us for the time being as we are too much busy right now. Keep up the good work !

**Comment by bobdenotter** [comment]
> I do hope that this we'll be fixed someday. Not by us for the time being as we are too much busy right now. 

That's the thing that rubs me the wrong way, I think. To me this sounds like "This is very important for us. Just not important enough to fix ourselves, but still very important." 

Yeah, i might come off a bit strong occasionally, but that's only because I care about Bolt, and I spend a _lot_ of time working on it, and we do many feature requests. We just can't please everybody all of the time.

**Comment by aerth** [comment]
Tags should have no spaces, and should be case insensitive. I think if you want spaces in your tags the best way is to have some kind of twig filter that changes dashes to spaces

**Comment by leup** [comment]
Is there a way to keep the tag management as-is and use the translation engine to have a formated label on the presentation side, may be as a twig filter as you suggest ? Could it be a workaround ? Just to be clear, it was not just spaces in tags but also some special characters (as the #). It's been a while that I take a look at this and a lot have changed since then so not sure what's possible or not nowadays. So having a tag "c-sharp" for example in the database but that could come out as "C#" via a text string translation: "c-sharp => C#'

@bobdenotter 
> To me this sounds like "This is very important for us. Just not important enough to fix ourselves, but still very important." 
My 2 cents here were to say that other CMS offer this kind of ability and I think this could be a drawback for certain projects as I gave example by my experience.

**Comment by GawainLynch** [comment]
Done thanks to @hannesl
